/*
 *  last change 2003-11-10 
 */

/**
 * Title:        GRMG Scenario
 * Description:
 * Copyright:    Copyright (c) 2002
 * Company:      SAP AG
 * @author       Pavel Kojevnikov
 * @version 1.1
 */

package com.sap.util.monitor.grmg;
import java.io.ByteArrayOutputStream;

/**
This class is a wrapper for Exception generated by GrmgRequest object  
*/
public class GrmgRequestException extends Exception
{
	private String lineEnd=System.getProperty("line.separator");
	private transient ByteArrayOutputStream output=new ByteArrayOutputStream();
	/**
	Constructor for GrmgRequestException using Message string
	*/
	public GrmgRequestException(String mess)
	{
		super(mess);
	}
	/**
	Constructor for GrmgRequestException
	*/
	public GrmgRequestException()
	{
		super();
		
	}
	/**
	Getting well-formed XML output proper for GRMG framework
	*/
	public ByteArrayOutputStream getByteArrayOutputStream()
	{
		
		println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
		
		println("<scenario>");
		println("<scenname>");
		println("</scenname>");
		println("<sceninst>");
		println("</sceninst>");
		
		println("<scenversion>");
		println("</scenversion>");
	   			println("<messages>");
    			println("<message>");
    				println("<messalert>"+"ERROR"+"</messalert>");
    				println("<messseverity>"+"255"+"</messseverity>");
    				println("<messarea>"+"</messarea>");
    				
    				println("<messnumber>"+"</messnumber>");
    				println("<messparam1>"+"</messparam1>");
    				println("<messparam2>"+"</messparam2>");
    				println("<messparam3>"+"</messparam3>");
    				
    				println("<messparam4>"+"</messparam4>");
    				println("<messtext>"+getMessage()+"</messtext>");
    				println("</message>");
  
    			println("</messages>");
    	println("</scenario>");
		return output;
	}
	
	private void println(String s)
	{
		output.write(s.getBytes(),0,s.length());
		
		output.write(lineEnd.getBytes(),0,lineEnd.length());  
	}
	
	
}