/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 31 10:07:41 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.persistent;

/**
 * Schema complexType Java representation.
 * Represents type {}load-selected-objectsType
 */
public  class LoadSelectedObjectsType implements java.io.Serializable,java.lang.Cloneable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Attribute field for attribute {}lock
  private com.sap.engine.lib.descriptors.persistent.Lock _a_Lock;
  /**
   * Set method for attribute {}lock
   */
  public void setLock(com.sap.engine.lib.descriptors.persistent.Lock _Lock) {
    this._a_Lock = _Lock;
  }
  /**
   * Get method for attribute {}lock
   */
  public com.sap.engine.lib.descriptors.persistent.Lock getLock() {
    return _a_Lock;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof LoadSelectedObjectsType)) return false;
    LoadSelectedObjectsType typed = (LoadSelectedObjectsType) object;
    if (this._a_Lock != null) {
      if (typed._a_Lock == null) return false;
      if (!this._a_Lock.equals(typed._a_Lock)) return false;
    } else {
      if (typed._a_Lock != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_Lock != null) {
      result+= this._a_Lock.hashCode();
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
