export const constantValues = {
    
    SAVE_AND_CHECKIN_BUTTONLABEL : 'Save & Check-In',
    HOME_CONSTANT : 'Home',
    NEW_VISITOR_CONSTANT : 'New Visitor',
    REPLACE_CARD_CONSTANT : 'Replace Card',
    STRING_TRUE: 'true',
    STRING_FALSE:'false',
    STRING_CHECKINSUCCESS : 'checkInSuccess',
    STRING_DUPLICATEINTERACTION : 'DuplicateInteraction',
    STRING_GENERATEERRORMESSAGE : 'generateErrorMessage',
    STRING_MAXREACHED:'maxReached',
    STRING_ERROR : 'error',
    STRING_SWITCH_ATTENDANCE:'Switch_Attendance',
    STRING_SEMICOLON : ';',
    STRING_DISPLAY_BLOCK : 'display:block',
    STRING_DISPLAY_NONE: 'display:none',
    STRING_STICKY : 'sticky',
    STRING_DISMISSIBLE : 'dismissible',
    STRING_SUCCESS : 'success',
    STRING_WARNING: 'warning',
    STRING_CLOSESCANCARDMODAL :'closescancardmodal',
    STRING_CLOSEINACTIVEMEMBERMODAL:'closeinactivemembermodal',
    STRING_SUCCESS_MSG:'Success!!',
    STRING_DUPLICATEINTLIST:'duplicateIntList',
    STRING_NOTIFICATIONLIST:'notificationList',
    STRING_SCANCARD_EVENTNAME:'scancardevent',
    STRING_PAGEREFTYPE:'standard__namedPage',
    STRING_HOME_PAGE:'home'
}