<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>Blackbox_Customization_Request_Approval_Owner</fullName>
        <description>Blackbox Customization Request Approval - Owner</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Approval</template>
    </alerts>
    <alerts>
        <fullName>Blackbox_Customization_Request_Approval_Resources</fullName>
        <description>Blackbox Customization Request Approval - Resources</description>
        <protected>false</protected>
        <recipients>
            <field>Business_Process_Owner__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>Primary_Technical_Resource__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Approval</template>
    </alerts>
    <alerts>
        <fullName>Blackbox_Customization_Request_Deferred_Owner</fullName>
        <description>Blackbox Customization Request Deferred - Owner</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Deferred</template>
    </alerts>
    <alerts>
        <fullName>Blackbox_Customization_Request_Deferred_Resources</fullName>
        <description>Blackbox Customization Request Deferred - Resources</description>
        <protected>false</protected>
        <recipients>
            <field>Business_Process_Owner__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>Primary_Technical_Resource__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Deferred</template>
    </alerts>
    <alerts>
        <fullName>Customization_Approval_Email_Related_Users</fullName>
        <description>Customization Approval Email - Related Users</description>
        <protected>false</protected>
        <recipients>
            <field>Business_Process_Owner__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>Primary_Technical_Resource__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Approval</template>
    </alerts>
    <alerts>
        <fullName>Customization_Approval_Notification_Owner</fullName>
        <description>Customization Approval Notification - Owner</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Approval</template>
    </alerts>
    <alerts>
        <fullName>Customization_Approval_Owner</fullName>
        <description>Customization Approval - Owner</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Approval</template>
    </alerts>
    <alerts>
        <fullName>Customization_Approval_Resources</fullName>
        <description>Customization Approval - Resources</description>
        <protected>false</protected>
        <recipients>
            <field>Business_Process_Owner__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>Primary_Technical_Resource__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Approval</template>
    </alerts>
    <alerts>
        <fullName>Customization_Deferred_Owner</fullName>
        <description>Customization Deferred - Owner</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Deferred</template>
    </alerts>
    <alerts>
        <fullName>Customization_Deferred_Resources</fullName>
        <description>Customization Deferred - Resources</description>
        <protected>false</protected>
        <recipients>
            <field>Business_Process_Owner__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>Primary_Technical_Resource__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Deferred</template>
    </alerts>
    <alerts>
        <fullName>Customization_Rejection_Email</fullName>
        <description>Customization Deferred Email - Related Users</description>
        <protected>false</protected>
        <recipients>
            <field>Business_Process_Owner__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>Primary_Technical_Resource__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Deferred</template>
    </alerts>
    <alerts>
        <fullName>Customization_Request_Rejection_Notification</fullName>
        <description>Customization Request Rejected - Owner</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Deferred</template>
    </alerts>
    <alerts>
        <fullName>Off_Platform_Customization_Request_Approval_Owner</fullName>
        <description>Off-Platform Customization Request Approval - Owner</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Approval</template>
    </alerts>
    <alerts>
        <fullName>Off_Platform_Customization_Request_Approval_Resources</fullName>
        <description>Off-Platform Customization Request Approval - Resources</description>
        <protected>false</protected>
        <recipients>
            <field>Business_Process_Owner__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>Primary_Technical_Resource__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Approval</template>
    </alerts>
    <alerts>
        <fullName>Off_Platform_Customization_Request_Deferred_Owner</fullName>
        <description>Off-Platform Customization Request Deferred - Owner</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Deferred</template>
    </alerts>
    <alerts>
        <fullName>Off_Platform_Customization_Request_Deferred_Resources</fullName>
        <description>Off-Platform Customization Request Deferred - Resources</description>
        <protected>false</protected>
        <recipients>
            <field>Business_Process_Owner__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>Primary_Technical_Resource__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>BME_Templates/Customization_Request_Deferred</template>
    </alerts>
    <fieldUpdates>
        <fullName>Status_Update_to_Approved</fullName>
        <field>Status__c</field>
        <literalValue>Approved</literalValue>
        <name>Status Update to Approved</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update_Approval_Status</fullName>
        <field>Status__c</field>
        <literalValue>Approved</literalValue>
        <name>Update Approval Status</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update_Status_Deferred</fullName>
        <field>Status__c</field>
        <literalValue>Deferred</literalValue>
        <name>Update Status Deferred</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update_Status_to_Approved</fullName>
        <field>Status__c</field>
        <literalValue>Approved</literalValue>
        <name>Update Status to Approved</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update_Status_to_Approved1</fullName>
        <field>Status__c</field>
        <literalValue>Approved</literalValue>
        <name>Update Status to Approved</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update_Status_to_Deferred</fullName>
        <field>Status__c</field>
        <literalValue>Deferred</literalValue>
        <name>Update Status to Deferred</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update_Status_to_Deferred1</fullName>
        <field>Status__c</field>
        <literalValue>Deferred</literalValue>
        <name>Update Status to Deferred</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update_Status_to_Deferred2</fullName>
        <field>Status__c</field>
        <literalValue>Deferred</literalValue>
        <name>Update Status to Deferred</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
</Workflow>
