/*
 * Generated by SAP SchemaToJava Generator NW05 on Tue Mar 14 18:01:52 EET 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors5.webjsptld.frm;

/**
 * Schema complexType Java representation.
 * Represents type {http://java.sun.com/xml/ns/javaee}tld-attributeType
 */
public  class TldAttributeTypeSD extends com.sap.engine.services.webservices.jaxrpc.encoding.GeneratedComplexType {

  public java.lang.String _d_originalUri() {
    return "http://java.sun.com/xml/ns/javaee";
  }

  public java.lang.String _d_originalLocalName() {
    return "tld-attributeType";
  }


  // Model group nested serializer.
  public static class Choice1 extends com.sap.engine.services.webservices.jaxrpc.encoding.GeneratedModelGroup {

    public Choice1() {
    }


    // Model group nested serializer.
  public static class Sequence1 extends com.sap.engine.services.webservices.jaxrpc.encoding.GeneratedModelGroup {

    public Sequence1() {
    }


    // Model group nested serializer.
  public static class Sequence2 extends com.sap.engine.services.webservices.jaxrpc.encoding.GeneratedModelGroup {

    public Sequence2() {
    }

    // Returns model Group Type
    public int _getModelType() {
      return 3;
    }

    // Field information
    private static com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] FIELDINFO;

    private synchronized static void initFields() {
      // Creating fields
      if (FIELDINFO != null) return;
      FIELDINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[2];
      FIELDINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
      FIELDINFO[1] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
      // Field 0
      FIELDINFO[0].defaultValue = null;
      FIELDINFO[0].fieldJavaName = "Rtexprvalue";
      FIELDINFO[0].fieldLocalName = "rtexprvalue";
      FIELDINFO[0].fieldModel = 1;
      FIELDINFO[0].fieldUri = "http://java.sun.com/xml/ns/javaee";
      FIELDINFO[0].isSoapArray = false;
      FIELDINFO[0].maxOccurs = 1;
      FIELDINFO[0].minOccurs = 0;
      FIELDINFO[0].nillable = false;
      FIELDINFO[0].soapArrayDimensions = 0;
      FIELDINFO[0].soapArrayItemTypeJavaName = null;
      FIELDINFO[0].soapArrayItemTypeLocalName = null;
      FIELDINFO[0].soapArrayItemTypeUri = null;
      FIELDINFO[0].typeJavaName = "com.sap.engine.lib.descriptors5.javaee.GenericBooleanType";
      FIELDINFO[0].typeLocalName = "generic-booleanType";
      FIELDINFO[0].typeUri = "http://java.sun.com/xml/ns/javaee";
      FIELDINFO[0].getterMethod = "getRtexprvalue";
      FIELDINFO[0].setterMethod = "setRtexprvalue";
      FIELDINFO[0].checkMethod = null;
      // Field 1
      FIELDINFO[1].defaultValue = null;
      FIELDINFO[1].fieldJavaName = "Type";
      FIELDINFO[1].fieldLocalName = "type";
      FIELDINFO[1].fieldModel = 1;
      FIELDINFO[1].fieldUri = "http://java.sun.com/xml/ns/javaee";
      FIELDINFO[1].isSoapArray = false;
      FIELDINFO[1].maxOccurs = 1;
      FIELDINFO[1].minOccurs = 0;
      FIELDINFO[1].nillable = false;
      FIELDINFO[1].soapArrayDimensions = 0;
      FIELDINFO[1].soapArrayItemTypeJavaName = null;
      FIELDINFO[1].soapArrayItemTypeLocalName = null;
      FIELDINFO[1].soapArrayItemTypeUri = null;
      FIELDINFO[1].typeJavaName = "com.sap.engine.lib.descriptors5.javaee.FullyQualifiedClassType";
      FIELDINFO[1].typeLocalName = "fully-qualified-classType";
      FIELDINFO[1].typeUri = "http://java.sun.com/xml/ns/javaee";
      FIELDINFO[1].getterMethod = "getType";
      FIELDINFO[1].setterMethod = "setType";
      FIELDINFO[1].checkMethod = null;
    }



    public com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] _getFields() {
      return FIELDINFO;
    }

    public int _getNumberOfFields() {
      return (FIELDINFO.length+super._getNumberOfFields());
    }

    static {
      initFields();
    }
  }

    // Returns model Group Type
    public int _getModelType() {
      return 3;
    }

    // Field information
    private static com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] FIELDINFO;

    private synchronized static void initFields() {
      // Creating fields
      if (FIELDINFO != null) return;
      FIELDINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[3];
      FIELDINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
      FIELDINFO[1] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
      FIELDINFO[2] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
      // Field 0
      FIELDINFO[0].defaultValue = null;
      FIELDINFO[0].fieldJavaName = "SequenceGroup2";
      FIELDINFO[0].fieldLocalName = null;
      FIELDINFO[0].fieldModel = 3;
      FIELDINFO[0].fieldUri = null;
      FIELDINFO[0].isSoapArray = false;
      FIELDINFO[0].maxOccurs = 1;
      FIELDINFO[0].minOccurs = 0;
      FIELDINFO[0].nillable = false;
      FIELDINFO[0].soapArrayDimensions = 0;
      FIELDINFO[0].soapArrayItemTypeJavaName = null;
      FIELDINFO[0].soapArrayItemTypeLocalName = null;
      FIELDINFO[0].soapArrayItemTypeUri = null;
      FIELDINFO[0].typeJavaName = "Sequence2";
      FIELDINFO[0].typeLocalName = null;
      FIELDINFO[0].typeUri = null;
      FIELDINFO[0].getterMethod = "getSequenceGroup2";
      FIELDINFO[0].setterMethod = "setSequenceGroup2";
      FIELDINFO[0].checkMethod = null;
      FIELDINFO[0].objectValue = new Sequence2();
      // Field 1
      FIELDINFO[1].defaultValue = null;
      FIELDINFO[1].fieldJavaName = "DeferredValue";
      FIELDINFO[1].fieldLocalName = "deferred-value";
      FIELDINFO[1].fieldModel = 1;
      FIELDINFO[1].fieldUri = "http://java.sun.com/xml/ns/javaee";
      FIELDINFO[1].isSoapArray = false;
      FIELDINFO[1].maxOccurs = 1;
      FIELDINFO[1].minOccurs = 0;
      FIELDINFO[1].nillable = false;
      FIELDINFO[1].soapArrayDimensions = 0;
      FIELDINFO[1].soapArrayItemTypeJavaName = null;
      FIELDINFO[1].soapArrayItemTypeLocalName = null;
      FIELDINFO[1].soapArrayItemTypeUri = null;
      FIELDINFO[1].typeJavaName = "com.sap.engine.lib.descriptors5.webjsptld.TldDeferredValueType";
      FIELDINFO[1].typeLocalName = "tld-deferred-valueType";
      FIELDINFO[1].typeUri = "http://java.sun.com/xml/ns/javaee";
      FIELDINFO[1].getterMethod = "getDeferredValue";
      FIELDINFO[1].setterMethod = "setDeferredValue";
      FIELDINFO[1].checkMethod = null;
      // Field 2
      FIELDINFO[2].defaultValue = null;
      FIELDINFO[2].fieldJavaName = "DeferredMethod";
      FIELDINFO[2].fieldLocalName = "deferred-method";
      FIELDINFO[2].fieldModel = 1;
      FIELDINFO[2].fieldUri = "http://java.sun.com/xml/ns/javaee";
      FIELDINFO[2].isSoapArray = false;
      FIELDINFO[2].maxOccurs = 1;
      FIELDINFO[2].minOccurs = 0;
      FIELDINFO[2].nillable = false;
      FIELDINFO[2].soapArrayDimensions = 0;
      FIELDINFO[2].soapArrayItemTypeJavaName = null;
      FIELDINFO[2].soapArrayItemTypeLocalName = null;
      FIELDINFO[2].soapArrayItemTypeUri = null;
      FIELDINFO[2].typeJavaName = "com.sap.engine.lib.descriptors5.webjsptld.TldDeferredMethodType";
      FIELDINFO[2].typeLocalName = "tld-deferred-methodType";
      FIELDINFO[2].typeUri = "http://java.sun.com/xml/ns/javaee";
      FIELDINFO[2].getterMethod = "getDeferredMethod";
      FIELDINFO[2].setterMethod = "setDeferredMethod";
      FIELDINFO[2].checkMethod = null;
    }



    public com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] _getFields() {
      return FIELDINFO;
    }

    public int _getNumberOfFields() {
      return (FIELDINFO.length+super._getNumberOfFields());
    }

    static {
      initFields();
    }
  }

    // Returns model Group Type
    public int _getModelType() {
      return 2;
    }

    // Field information
    private static com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] FIELDINFO;

    private synchronized static void initFields() {
      // Creating fields
      if (FIELDINFO != null) return;
      FIELDINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[2];
      FIELDINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
      FIELDINFO[1] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
      // Field 0
      FIELDINFO[0].defaultValue = null;
      FIELDINFO[0].fieldJavaName = "SequenceGroup1";
      FIELDINFO[0].fieldLocalName = null;
      FIELDINFO[0].fieldModel = 3;
      FIELDINFO[0].fieldUri = null;
      FIELDINFO[0].isSoapArray = false;
      FIELDINFO[0].maxOccurs = 1;
      FIELDINFO[0].minOccurs = 1;
      FIELDINFO[0].nillable = false;
      FIELDINFO[0].soapArrayDimensions = 0;
      FIELDINFO[0].soapArrayItemTypeJavaName = null;
      FIELDINFO[0].soapArrayItemTypeLocalName = null;
      FIELDINFO[0].soapArrayItemTypeUri = null;
      FIELDINFO[0].typeJavaName = "Sequence1";
      FIELDINFO[0].typeLocalName = null;
      FIELDINFO[0].typeUri = null;
      FIELDINFO[0].getterMethod = "getSequenceGroup1";
      FIELDINFO[0].setterMethod = "setSequenceGroup1";
      FIELDINFO[0].checkMethod = "isSetSequenceGroup1";
      FIELDINFO[0].objectValue = new Sequence1();
      // Field 1
      FIELDINFO[1].defaultValue = null;
      FIELDINFO[1].fieldJavaName = "Fragment";
      FIELDINFO[1].fieldLocalName = "fragment";
      FIELDINFO[1].fieldModel = 1;
      FIELDINFO[1].fieldUri = "http://java.sun.com/xml/ns/javaee";
      FIELDINFO[1].isSoapArray = false;
      FIELDINFO[1].maxOccurs = 1;
      FIELDINFO[1].minOccurs = 0;
      FIELDINFO[1].nillable = false;
      FIELDINFO[1].soapArrayDimensions = 0;
      FIELDINFO[1].soapArrayItemTypeJavaName = null;
      FIELDINFO[1].soapArrayItemTypeLocalName = null;
      FIELDINFO[1].soapArrayItemTypeUri = null;
      FIELDINFO[1].typeJavaName = "com.sap.engine.lib.descriptors5.javaee.GenericBooleanType";
      FIELDINFO[1].typeLocalName = "generic-booleanType";
      FIELDINFO[1].typeUri = "http://java.sun.com/xml/ns/javaee";
      FIELDINFO[1].getterMethod = "getFragment";
      FIELDINFO[1].setterMethod = "setFragment";
      FIELDINFO[1].checkMethod = "isSetFragment";
    }



    public com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] _getFields() {
      return FIELDINFO;
    }

    public int _getNumberOfFields() {
      return (FIELDINFO.length+super._getNumberOfFields());
    }

    static {
      initFields();
    }
  }

  private static com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] ATTRIBUTEINFO;

  private synchronized static void initAttribs() {
    // Creating attribute fields
    if (ATTRIBUTEINFO != null) return;
    ATTRIBUTEINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[1];
    ATTRIBUTEINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    // Attribute 0
    ATTRIBUTEINFO[0].fieldLocalName = "id";
    ATTRIBUTEINFO[0].fieldUri = "";
    ATTRIBUTEINFO[0].fieldJavaName = "Id";
    ATTRIBUTEINFO[0].typeName = "ID";
    ATTRIBUTEINFO[0].typeUri = "http://www.w3.org/2001/XMLSchema";
    ATTRIBUTEINFO[0].typeJavaName = "java.lang.String";
    ATTRIBUTEINFO[0].defaultValue = null;
    ATTRIBUTEINFO[0].required = false;
    ATTRIBUTEINFO[0].setterMethod = "setId";
    ATTRIBUTEINFO[0].getterMethod = "getId";
    ATTRIBUTEINFO[0].checkMethod = null;
  }

  // Field information
  private static com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] FIELDINFO;

  private synchronized static void initFields() {
    // Creating fields
    if (FIELDINFO != null) return;
    FIELDINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[4];
    FIELDINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    FIELDINFO[1] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    FIELDINFO[2] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    FIELDINFO[3] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    // Field 0
    FIELDINFO[0].defaultValue = null;
    FIELDINFO[0].fieldJavaName = "Description";
    FIELDINFO[0].fieldLocalName = "description";
    FIELDINFO[0].fieldModel = 1;
    FIELDINFO[0].fieldUri = "http://java.sun.com/xml/ns/javaee";
    FIELDINFO[0].isSoapArray = false;
    FIELDINFO[0].maxOccurs = 2147483647;
    FIELDINFO[0].minOccurs = 0;
    FIELDINFO[0].nillable = false;
    FIELDINFO[0].soapArrayDimensions = 0;
    FIELDINFO[0].soapArrayItemTypeJavaName = null;
    FIELDINFO[0].soapArrayItemTypeLocalName = null;
    FIELDINFO[0].soapArrayItemTypeUri = null;
    FIELDINFO[0].typeJavaName = "com.sap.engine.lib.descriptors5.javaee.DescriptionType[]";
    FIELDINFO[0].typeLocalName = "descriptionType";
    FIELDINFO[0].typeUri = "http://java.sun.com/xml/ns/javaee";
    FIELDINFO[0].getterMethod = "getDescription";
    FIELDINFO[0].setterMethod = "setDescription";
    FIELDINFO[0].checkMethod = null;
    // Field 1
    FIELDINFO[1].defaultValue = null;
    FIELDINFO[1].fieldJavaName = "Name";
    FIELDINFO[1].fieldLocalName = "name";
    FIELDINFO[1].fieldModel = 1;
    FIELDINFO[1].fieldUri = "http://java.sun.com/xml/ns/javaee";
    FIELDINFO[1].isSoapArray = false;
    FIELDINFO[1].maxOccurs = 1;
    FIELDINFO[1].minOccurs = 1;
    FIELDINFO[1].nillable = false;
    FIELDINFO[1].soapArrayDimensions = 0;
    FIELDINFO[1].soapArrayItemTypeJavaName = null;
    FIELDINFO[1].soapArrayItemTypeLocalName = null;
    FIELDINFO[1].soapArrayItemTypeUri = null;
    FIELDINFO[1].typeJavaName = "com.sap.engine.lib.descriptors5.javaee.JavaIdentifierType";
    FIELDINFO[1].typeLocalName = "java-identifierType";
    FIELDINFO[1].typeUri = "http://java.sun.com/xml/ns/javaee";
    FIELDINFO[1].getterMethod = "getName";
    FIELDINFO[1].setterMethod = "setName";
    FIELDINFO[1].checkMethod = null;
    // Field 2
    FIELDINFO[2].defaultValue = null;
    FIELDINFO[2].fieldJavaName = "Required";
    FIELDINFO[2].fieldLocalName = "required";
    FIELDINFO[2].fieldModel = 1;
    FIELDINFO[2].fieldUri = "http://java.sun.com/xml/ns/javaee";
    FIELDINFO[2].isSoapArray = false;
    FIELDINFO[2].maxOccurs = 1;
    FIELDINFO[2].minOccurs = 0;
    FIELDINFO[2].nillable = false;
    FIELDINFO[2].soapArrayDimensions = 0;
    FIELDINFO[2].soapArrayItemTypeJavaName = null;
    FIELDINFO[2].soapArrayItemTypeLocalName = null;
    FIELDINFO[2].soapArrayItemTypeUri = null;
    FIELDINFO[2].typeJavaName = "com.sap.engine.lib.descriptors5.javaee.GenericBooleanType";
    FIELDINFO[2].typeLocalName = "generic-booleanType";
    FIELDINFO[2].typeUri = "http://java.sun.com/xml/ns/javaee";
    FIELDINFO[2].getterMethod = "getRequired";
    FIELDINFO[2].setterMethod = "setRequired";
    FIELDINFO[2].checkMethod = null;
    // Field 3
    FIELDINFO[3].defaultValue = null;
    FIELDINFO[3].fieldJavaName = "ChoiceGroup1";
    FIELDINFO[3].fieldLocalName = null;
    FIELDINFO[3].fieldModel = 2;
    FIELDINFO[3].fieldUri = null;
    FIELDINFO[3].isSoapArray = false;
    FIELDINFO[3].maxOccurs = 1;
    FIELDINFO[3].minOccurs = 1;
    FIELDINFO[3].nillable = false;
    FIELDINFO[3].soapArrayDimensions = 0;
    FIELDINFO[3].soapArrayItemTypeJavaName = null;
    FIELDINFO[3].soapArrayItemTypeLocalName = null;
    FIELDINFO[3].soapArrayItemTypeUri = null;
    FIELDINFO[3].typeJavaName = "Choice1";
    FIELDINFO[3].typeLocalName = null;
    FIELDINFO[3].typeUri = null;
    FIELDINFO[3].getterMethod = "getChoiceGroup1";
    FIELDINFO[3].setterMethod = "setChoiceGroup1";
    FIELDINFO[3].checkMethod = null;
    FIELDINFO[3].objectValue = new Choice1();
  }


  // Returns model Group Type
  public int _getModelType() {
    return 3;
  }

  private static boolean init = false;
  public synchronized com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] _getFields() {
    if (init == false) {
      com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] parent = super._getFields();
      FIELDINFO =  _insertFieldInfo(parent,FIELDINFO);
      init = true;
    }
    return FIELDINFO;
  }

  public int _getNumberOfFields() {
    return (FIELDINFO.length+super._getNumberOfFields());
  }

  public com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] _getAttributes() {
    return ATTRIBUTEINFO;
  }

  public int _getNumberOfAttributes() {
    return ATTRIBUTEINFO.length;
  }

  static {
    initFields();
    initAttribs();
  }
}
