export function getDetailFormLayout(){
    const detail = [
        {label: 'Medical Claims Number', mapping: 'sMedicareId', value: ''},
        {label: 'Application Channel', mapping: 'sApplicationChannel', value: ''},
        {label: 'First Name', mapping: 'sFirstName', value: ''},
        {label: 'Web unique ID', mapping: 'sWebUniqueId', value: ''},
        {label: 'Last Name', mapping: 'sLastName', value: ''},
        {label: 'OEC Confirmation', mapping: 'sOECConfirmationId', value: ''},
        {label: 'Date of Birth', mapping: 'sDOB', value: ''},
        {label: 'Effective Date', mapping: 'sCovEffDt', value: ''},
        {label: 'Contact', mapping: 'sContact', value: ''},
        {label: 'End Date', mapping: 'sEndDate', value: ''},
        {label: 'PBP', mapping: 'sPBP', value: ''},
        {label: 'Raw OEC Year', mapping: 'sRawOECYear', value: ''},
        {label: 'Group ID', mapping: 'sGroupId', value: ''},
        {label: 'Details', mapping: 'details', value: ''},
        {label: 'BSN', mapping: 'sBSN', value: ''},
        {label: 'Application', mapping: 'application', value: ''},
        {label: 'Segment ID', mapping: 'sSegmentNumber', value: ''}
    ];
    return detail;
}

export function getBenifitsInfoLayout(){
    const detail =[{Title:'Demographic',gridSize:'5',
                data:[{section:'Member Demographics',label: 'Medicare Claim #', mapping: 'sMedicareId', value: ''},
                    {section:'Member Demographics',label: 'Social Security', mapping: 'sSolSecurity', value: ''},
                    {section:'Member Demographics',label: 'Permanent Address Apt #', mapping: 'sPermanentAddress', value: ''},
                    {section:'Member Demographics',label: 'Mailing Address  Apt #', mapping: 'sMailaddr', value: ''},
                    {section:'Member Demographics',label: 'Zip Code', mapping: 'sMailZip', value: ''},
                    {section:'Member Demographics',label: 'Last Name', mapping: 'sLastName', value: ''},
                    {section:'Member Demographics',label: 'Date Of Birth', mapping: 'sDOB', value: ''},
					{section:'Member Demographics',label: 'City', mapping: 'sCity', value: ''},                    
                    {section:'Member Demographics',label: 'County Name', mapping: 'sCountyName', value: ''},
                    {section:'Member Demographics',label: 'Home Phone', mapping: 'sHomePh', value: ''},
                    {section:'Member Demographics',label: 'First Name', mapping: 'sFirstName', value: ''},
                    {section:'Member Demographics',label: 'Medicaid #', mapping: 'sMedicaidId', value: ''},
                    {section:'Member Demographics',label: 'State', mapping: 'sState', value: ''},
                    {section:'Member Demographics',label: 'City', mapping: 'sMailCity', value: ''},
                    {section:'Member Demographics',label: 'Work Phone', mapping: 'sworkPh', value: ''},
                    {section:'Member Demographics',label: 'Gender', mapping: 'sGender', value: ''},
                    {section:'Member Demographics', label: 'Member Language Preference', mapping: 'sMemberLangPreference', value: ''},                    
					{section:'Member Demographics',label: 'Zip Code', mapping: 'sZip', value: ''},
					{section:'Member Demographics',label: 'State', mapping: 'sMailSt', value: ''},
					{section:'Member Demographics',label: 'Race', mapping: 'sRace', value: ''},
                    {section:'Member Demographics',label: 'Ethnicity', mapping: 'sEthinicity', value: ''}
                    ]},
        
        { Title:'POA & Agent Information',gridSize:'2', 
                            data:[{section:'POA',label: 'Last Name', mapping: 'sPOALastName', value: ''},
                                {section:'POA',label: 'First Name', mapping: 'sPOAFirstName', value: ''},
                                {section:'POA',label: 'Relationship to Applicant', mapping: 'sPOARelationType', value: ''},
                                {section:'POA',label: 'Phone Number', mapping: 'sPOAPhone', value: ''},
                                {section:'Agent Information',label: 'Member Plan Rep', mapping: 'sSalesRepName', value: ''},
                                {section:'Agent Information',label: 'Agent Broker Type', mapping: 'sSalesType', value: ''},
                                {section:'Agent Information',label: 'Agent SSN', mapping: 'sSalesRepSSN', value: ''}
                                ]
                                },
		{ Title:'Application Election',gridSize:'2', 
                        data:[{section:'Benefits Information',label: 'Contract', mapping: 'sContractId', value: ''},
                            {section:'Benefits Information',label: 'Group ID', mapping: 'sGroupId', value: ''},
                            {section:'Benefits Information',label: 'Effective Date', mapping: 'sCovEffDt', value: ''},
                            {section:'Benefits Information',label: 'PBP', mapping: 'sPBP', value: ''},
                            {section:'Benefits Information',label: 'BSN', mapping: 'sBSN', value: ''},
                            {section:'Benefits Information',label: 'Received Date', mapping: 'sReceivedDate', value: ''},
                            {section:'Benefits Information',label: 'OSB Pkg ID', mapping: 'sOSBPackage', value: ''},
                            {section:'Benefits Information',label: 'Segment ID', mapping: 'sSegmentId', value: ''},
                            {section:'Benefits Information',label: 'Group Employer ID', mapping: 'sEmployerId', value: ''},
                            {section:'Benefits Information',label: 'Billing Payment Option', mapping: 'sPymtOpt', value: ''},
                            {section:'Benefits Information',label: 'Signature Type', mapping: 'sSignatureType', value: ''},
                            {section:'Benefits Information',label: 'Billing Payment Option Type', mapping: 'sPymtOptType', value: ''},
                            {section:'Benefits Information',label: 'Signature Date', mapping: 'sSignatureDate', value: ''},
                            {section:'Health Indicators',label: 'Smoker Indicator', mapping: 'sSmokingIndicator', value: ''},
                            {section:'Health Indicators',label: 'Disability Indicator', mapping: 'sDisabledIndicator', value: ''},
                            {section:'Health Indicators',label: 'End Stage Renal Disease', mapping: 'sESRDIndicator', value: ''},
                            {section:'Primary Care Physician',label: 'Member PCP #', mapping: 'sPCPNumber', value: ''},
                            {section:'Primary Care Physician',label: 'PCP Name', mapping: 'sPCPName', value: ''}]
                            },
        { Title:'Medicare Entitlement & Misc',gridSize:'2', 
                                data:[{section:'Election',label: 'ETC', mapping: 'sElectionTypeCd', value: ''},
                                    {section:'Election',label: 'SEP Reason', mapping: 'sSepReasonCode', value: ''},
                                    {section:'Election',label: 'SEP DATE', mapping: 'sSEPDate', value: ''},
                                    {section:'Medicare Entitlement',label: 'Part A', mapping: 'sPartAEligibleDate', value: ''},
                                    {section:'Medicare Entitlement',label: 'Part B', mapping: 'sPartBEligibleDate', value: ''},
                                    {section:'Application Misc',label: 'File Date', mapping: 'sFileDt', value: ''},
                                    {section:'Application Misc',label: 'Processed Date', mapping: 'sProcDt', value: ''},
                                    {section:'Application Misc',label: 'Time Stamp', mapping: 'sCreationTs', value: ''},
                                    {section:'Application Misc',label: 'Application Channel', mapping: 'sApplicationChannel', value: ''},
                                    {section:'Application Misc',label: 'OEC Confirmation', mapping: 'sOECConfirmationId', value: ''},
                                    {section:'Application Misc',label: 'Bar Code', mapping: 'sBarCodeBase', value: ''}
                                    ]
                                    },
                        ];
    return detail;
}