/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 31 10:05:11 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.webj2eeengine;

/**
 * Schema complexType Java representation.
 * Represents type {}ejb-local-refType
 */
public  class EjbLocalRefType implements java.io.Serializable,java.lang.Cloneable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Element field for element {}ejb-ref-name
  private java.lang.String _f_EjbRefName;
  /**
   * Set method for element {}ejb-ref-name
   */
  public void setEjbRefName(java.lang.String _EjbRefName) {
    this._f_EjbRefName = _EjbRefName;
  }
  /**
   * Get method for element {}ejb-ref-name
   */
  public java.lang.String getEjbRefName() {
    return this._f_EjbRefName;
  }

  // Element field for element {}jndi-name
  private java.lang.String _f_JndiName;
  /**
   * Set method for element {}jndi-name
   */
  public void setJndiName(java.lang.String _JndiName) {
    this._f_JndiName = _JndiName;
  }
  /**
   * Get method for element {}jndi-name
   */
  public java.lang.String getJndiName() {
    return this._f_JndiName;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof EjbLocalRefType)) return false;
    EjbLocalRefType typed = (EjbLocalRefType) object;
    if (this._f_EjbRefName != null) {
      if (typed._f_EjbRefName == null) return false;
      if (!this._f_EjbRefName.equals(typed._f_EjbRefName)) return false;
    } else {
      if (typed._f_EjbRefName != null) return false;
    }
    if (this._f_JndiName != null) {
      if (typed._f_JndiName == null) return false;
      if (!this._f_JndiName.equals(typed._f_JndiName)) return false;
    } else {
      if (typed._f_JndiName != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_EjbRefName != null) {
      result+= this._f_EjbRefName.hashCode();
    }
    if (this._f_JndiName != null) {
      result+= this._f_JndiName.hashCode();
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
