/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 31 10:05:11 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.webj2eeengine;

/**
 * Schema complexType Java representation.
 * Represents type {}response-statusType
 */
public  class ResponseStatusType implements java.io.Serializable,java.lang.Cloneable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Element field for element {}status-code
  private int _f_StatusCode;
  /**
   * Set method for element {}status-code
   */
  public void setStatusCode(int _StatusCode) {
    this._f_StatusCode = _StatusCode;
  }
  /**
   * Get method for element {}status-code
   */
  public int getStatusCode() {
    return this._f_StatusCode;
  }

  // Element field for element {}reason-phrase
  private java.lang.String _f_ReasonPhrase;
  /**
   * Set method for element {}reason-phrase
   */
  public void setReasonPhrase(java.lang.String _ReasonPhrase) {
    this._f_ReasonPhrase = _ReasonPhrase;
  }
  /**
   * Get method for element {}reason-phrase
   */
  public java.lang.String getReasonPhrase() {
    return this._f_ReasonPhrase;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof ResponseStatusType)) return false;
    ResponseStatusType typed = (ResponseStatusType) object;
    if (this._f_StatusCode != typed._f_StatusCode) return false;
    if (this._f_ReasonPhrase != null) {
      if (typed._f_ReasonPhrase == null) return false;
      if (!this._f_ReasonPhrase.equals(typed._f_ReasonPhrase)) return false;
    } else {
      if (typed._f_ReasonPhrase != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    result+= (int) this._f_StatusCode;
    if (this._f_ReasonPhrase != null) {
      result+= this._f_ReasonPhrase.hashCode();
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
