/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Apr 06 17:27:59 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors5.appclient;

/**
 * Schema complexType Java representation.
 * Represents type {http://java.sun.com/xml/ns/javaee}application-clientType
 */
public  class ApplicationClientType implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Attribute field for attribute {}version
  private java.lang.String _a_Version;
  /**
   * Set method for attribute {}version
   */
  public void setVersion(java.lang.String _Version) {
    this._a_Version = _Version;
  }
  /**
   * Get method for attribute {}version
   */
  public java.lang.String getVersion() {
    return _a_Version;
  }

  // Attribute field for attribute {}metadata-complete
  private java.lang.Boolean _a_MetadataComplete;
  /**
   * Set method for attribute {}metadata-complete
   */
  public void setMetadataComplete(java.lang.Boolean _MetadataComplete) {
    this._a_MetadataComplete = _MetadataComplete;
  }
  /**
   * Get method for attribute {}metadata-complete
   */
  public java.lang.Boolean getMetadataComplete() {
    return _a_MetadataComplete;
  }

  // Attribute field for attribute {}id
  private java.lang.String _a_Id;
  /**
   * Set method for attribute {}id
   */
  public void setId(java.lang.String _Id) {
    this._a_Id = _Id;
  }
  /**
   * Get method for attribute {}id
   */
  public java.lang.String getId() {
    return _a_Id;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}description
  private java.util.ArrayList _f_Description = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}description
   */
  public void setDescription(com.sap.engine.lib.descriptors5.javaee.DescriptionType[] _Description) {
    this._f_Description.clear();
    if (_Description != null) {
      for (int i=0; i<_Description.length; i++) {
        if (_Description[i] != null)
          this._f_Description.add(_Description[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}description
   */
  public com.sap.engine.lib.descriptors5.javaee.DescriptionType[] getDescription() {
    com.sap.engine.lib.descriptors5.javaee.DescriptionType[] result = new com.sap.engine.lib.descriptors5.javaee.DescriptionType[_f_Description.size()];
    _f_Description.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}display-name
  private java.util.ArrayList _f_DisplayName = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}display-name
   */
  public void setDisplayName(com.sap.engine.lib.descriptors5.javaee.DisplayNameType[] _DisplayName) {
    this._f_DisplayName.clear();
    if (_DisplayName != null) {
      for (int i=0; i<_DisplayName.length; i++) {
        if (_DisplayName[i] != null)
          this._f_DisplayName.add(_DisplayName[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}display-name
   */
  public com.sap.engine.lib.descriptors5.javaee.DisplayNameType[] getDisplayName() {
    com.sap.engine.lib.descriptors5.javaee.DisplayNameType[] result = new com.sap.engine.lib.descriptors5.javaee.DisplayNameType[_f_DisplayName.size()];
    _f_DisplayName.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}icon
  private java.util.ArrayList _f_Icon = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}icon
   */
  public void setIcon(com.sap.engine.lib.descriptors5.javaee.IconType[] _Icon) {
    this._f_Icon.clear();
    if (_Icon != null) {
      for (int i=0; i<_Icon.length; i++) {
        if (_Icon[i] != null)
          this._f_Icon.add(_Icon[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}icon
   */
  public com.sap.engine.lib.descriptors5.javaee.IconType[] getIcon() {
    com.sap.engine.lib.descriptors5.javaee.IconType[] result = new com.sap.engine.lib.descriptors5.javaee.IconType[_f_Icon.size()];
    _f_Icon.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}env-entry
  private java.util.ArrayList _f_EnvEntry = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}env-entry
   */
  public void setEnvEntry(com.sap.engine.lib.descriptors5.javaee.EnvEntryType[] _EnvEntry) {
    this._f_EnvEntry.clear();
    if (_EnvEntry != null) {
      for (int i=0; i<_EnvEntry.length; i++) {
        if (_EnvEntry[i] != null)
          this._f_EnvEntry.add(_EnvEntry[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}env-entry
   */
  public com.sap.engine.lib.descriptors5.javaee.EnvEntryType[] getEnvEntry() {
    com.sap.engine.lib.descriptors5.javaee.EnvEntryType[] result = new com.sap.engine.lib.descriptors5.javaee.EnvEntryType[_f_EnvEntry.size()];
    _f_EnvEntry.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}ejb-ref
  private java.util.ArrayList _f_EjbRef = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}ejb-ref
   */
  public void setEjbRef(com.sap.engine.lib.descriptors5.javaee.EjbRefType[] _EjbRef) {
    this._f_EjbRef.clear();
    if (_EjbRef != null) {
      for (int i=0; i<_EjbRef.length; i++) {
        if (_EjbRef[i] != null)
          this._f_EjbRef.add(_EjbRef[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}ejb-ref
   */
  public com.sap.engine.lib.descriptors5.javaee.EjbRefType[] getEjbRef() {
    com.sap.engine.lib.descriptors5.javaee.EjbRefType[] result = new com.sap.engine.lib.descriptors5.javaee.EjbRefType[_f_EjbRef.size()];
    _f_EjbRef.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}service-ref
  private java.util.ArrayList _f_ServiceRef = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}service-ref
   */
  public void setServiceRef(com.sap.engine.lib.descriptors5.javaee.ServiceRefType[] _ServiceRef) {
    this._f_ServiceRef.clear();
    if (_ServiceRef != null) {
      for (int i=0; i<_ServiceRef.length; i++) {
        if (_ServiceRef[i] != null)
          this._f_ServiceRef.add(_ServiceRef[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}service-ref
   */
  public com.sap.engine.lib.descriptors5.javaee.ServiceRefType[] getServiceRef() {
    com.sap.engine.lib.descriptors5.javaee.ServiceRefType[] result = new com.sap.engine.lib.descriptors5.javaee.ServiceRefType[_f_ServiceRef.size()];
    _f_ServiceRef.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}resource-ref
  private java.util.ArrayList _f_ResourceRef = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}resource-ref
   */
  public void setResourceRef(com.sap.engine.lib.descriptors5.javaee.ResourceRefType[] _ResourceRef) {
    this._f_ResourceRef.clear();
    if (_ResourceRef != null) {
      for (int i=0; i<_ResourceRef.length; i++) {
        if (_ResourceRef[i] != null)
          this._f_ResourceRef.add(_ResourceRef[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}resource-ref
   */
  public com.sap.engine.lib.descriptors5.javaee.ResourceRefType[] getResourceRef() {
    com.sap.engine.lib.descriptors5.javaee.ResourceRefType[] result = new com.sap.engine.lib.descriptors5.javaee.ResourceRefType[_f_ResourceRef.size()];
    _f_ResourceRef.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}resource-env-ref
  private java.util.ArrayList _f_ResourceEnvRef = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}resource-env-ref
   */
  public void setResourceEnvRef(com.sap.engine.lib.descriptors5.javaee.ResourceEnvRefType[] _ResourceEnvRef) {
    this._f_ResourceEnvRef.clear();
    if (_ResourceEnvRef != null) {
      for (int i=0; i<_ResourceEnvRef.length; i++) {
        if (_ResourceEnvRef[i] != null)
          this._f_ResourceEnvRef.add(_ResourceEnvRef[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}resource-env-ref
   */
  public com.sap.engine.lib.descriptors5.javaee.ResourceEnvRefType[] getResourceEnvRef() {
    com.sap.engine.lib.descriptors5.javaee.ResourceEnvRefType[] result = new com.sap.engine.lib.descriptors5.javaee.ResourceEnvRefType[_f_ResourceEnvRef.size()];
    _f_ResourceEnvRef.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}message-destination-ref
  private java.util.ArrayList _f_MessageDestinationRef = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}message-destination-ref
   */
  public void setMessageDestinationRef(com.sap.engine.lib.descriptors5.javaee.MessageDestinationRefType[] _MessageDestinationRef) {
    this._f_MessageDestinationRef.clear();
    if (_MessageDestinationRef != null) {
      for (int i=0; i<_MessageDestinationRef.length; i++) {
        if (_MessageDestinationRef[i] != null)
          this._f_MessageDestinationRef.add(_MessageDestinationRef[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}message-destination-ref
   */
  public com.sap.engine.lib.descriptors5.javaee.MessageDestinationRefType[] getMessageDestinationRef() {
    com.sap.engine.lib.descriptors5.javaee.MessageDestinationRefType[] result = new com.sap.engine.lib.descriptors5.javaee.MessageDestinationRefType[_f_MessageDestinationRef.size()];
    _f_MessageDestinationRef.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}persistence-unit-ref
  private java.util.ArrayList _f_PersistenceUnitRef = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}persistence-unit-ref
   */
  public void setPersistenceUnitRef(com.sap.engine.lib.descriptors5.javaee.PersistenceUnitRefType[] _PersistenceUnitRef) {
    this._f_PersistenceUnitRef.clear();
    if (_PersistenceUnitRef != null) {
      for (int i=0; i<_PersistenceUnitRef.length; i++) {
        if (_PersistenceUnitRef[i] != null)
          this._f_PersistenceUnitRef.add(_PersistenceUnitRef[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}persistence-unit-ref
   */
  public com.sap.engine.lib.descriptors5.javaee.PersistenceUnitRefType[] getPersistenceUnitRef() {
    com.sap.engine.lib.descriptors5.javaee.PersistenceUnitRefType[] result = new com.sap.engine.lib.descriptors5.javaee.PersistenceUnitRefType[_f_PersistenceUnitRef.size()];
    _f_PersistenceUnitRef.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}post-construct
  private java.util.ArrayList _f_PostConstruct = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}post-construct
   */
  public void setPostConstruct(com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[] _PostConstruct) {
    this._f_PostConstruct.clear();
    if (_PostConstruct != null) {
      for (int i=0; i<_PostConstruct.length; i++) {
        if (_PostConstruct[i] != null)
          this._f_PostConstruct.add(_PostConstruct[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}post-construct
   */
  public com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[] getPostConstruct() {
    com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[] result = new com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[_f_PostConstruct.size()];
    _f_PostConstruct.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}pre-destroy
  private java.util.ArrayList _f_PreDestroy = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}pre-destroy
   */
  public void setPreDestroy(com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[] _PreDestroy) {
    this._f_PreDestroy.clear();
    if (_PreDestroy != null) {
      for (int i=0; i<_PreDestroy.length; i++) {
        if (_PreDestroy[i] != null)
          this._f_PreDestroy.add(_PreDestroy[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}pre-destroy
   */
  public com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[] getPreDestroy() {
    com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[] result = new com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[_f_PreDestroy.size()];
    _f_PreDestroy.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}callback-handler
  private com.sap.engine.lib.descriptors5.javaee.FullyQualifiedClassType _f_CallbackHandler;
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}callback-handler
   */
  public void setCallbackHandler(com.sap.engine.lib.descriptors5.javaee.FullyQualifiedClassType _CallbackHandler) {
    this._f_CallbackHandler = _CallbackHandler;
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}callback-handler
   */
  public com.sap.engine.lib.descriptors5.javaee.FullyQualifiedClassType getCallbackHandler() {
    return this._f_CallbackHandler;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}message-destination
  private java.util.ArrayList _f_MessageDestination = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}message-destination
   */
  public void setMessageDestination(com.sap.engine.lib.descriptors5.javaee.MessageDestinationType[] _MessageDestination) {
    this._f_MessageDestination.clear();
    if (_MessageDestination != null) {
      for (int i=0; i<_MessageDestination.length; i++) {
        if (_MessageDestination[i] != null)
          this._f_MessageDestination.add(_MessageDestination[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}message-destination
   */
  public com.sap.engine.lib.descriptors5.javaee.MessageDestinationType[] getMessageDestination() {
    com.sap.engine.lib.descriptors5.javaee.MessageDestinationType[] result = new com.sap.engine.lib.descriptors5.javaee.MessageDestinationType[_f_MessageDestination.size()];
    _f_MessageDestination.toArray(result);
    return result;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof ApplicationClientType)) return false;
    ApplicationClientType typed = (ApplicationClientType) object;
    if (this._a_Version != null) {
      if (typed._a_Version == null) return false;
      if (!this._a_Version.equals(typed._a_Version)) return false;
    } else {
      if (typed._a_Version != null) return false;
    }
    if (this._a_MetadataComplete != null) {
      if (typed._a_MetadataComplete == null) return false;
      if (!this._a_MetadataComplete.equals(typed._a_MetadataComplete)) return false;
    } else {
      if (typed._a_MetadataComplete != null) return false;
    }
    if (this._a_Id != null) {
      if (typed._a_Id == null) return false;
      if (!this._a_Id.equals(typed._a_Id)) return false;
    } else {
      if (typed._a_Id != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.DescriptionType[] _f_Description1 = this.getDescription();
    com.sap.engine.lib.descriptors5.javaee.DescriptionType[] _f_Description2 = typed.getDescription();
    if (_f_Description1 != null) {
      if (_f_Description2 == null) return false;
      if (_f_Description1.length != _f_Description2.length) return false;
      for (int i1 = 0; i1 < _f_Description1.length ; i1++) {
        if (_f_Description1[i1] != null) {
          if (_f_Description2[i1] == null) return false;
          if (!_f_Description1[i1].equals(_f_Description2[i1])) return false;
        } else {
          if (_f_Description2[i1] != null) return false;
        }
      }
    } else {
      if (_f_Description2 != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.DisplayNameType[] _f_DisplayName1 = this.getDisplayName();
    com.sap.engine.lib.descriptors5.javaee.DisplayNameType[] _f_DisplayName2 = typed.getDisplayName();
    if (_f_DisplayName1 != null) {
      if (_f_DisplayName2 == null) return false;
      if (_f_DisplayName1.length != _f_DisplayName2.length) return false;
      for (int i1 = 0; i1 < _f_DisplayName1.length ; i1++) {
        if (_f_DisplayName1[i1] != null) {
          if (_f_DisplayName2[i1] == null) return false;
          if (!_f_DisplayName1[i1].equals(_f_DisplayName2[i1])) return false;
        } else {
          if (_f_DisplayName2[i1] != null) return false;
        }
      }
    } else {
      if (_f_DisplayName2 != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.IconType[] _f_Icon1 = this.getIcon();
    com.sap.engine.lib.descriptors5.javaee.IconType[] _f_Icon2 = typed.getIcon();
    if (_f_Icon1 != null) {
      if (_f_Icon2 == null) return false;
      if (_f_Icon1.length != _f_Icon2.length) return false;
      for (int i1 = 0; i1 < _f_Icon1.length ; i1++) {
        if (_f_Icon1[i1] != null) {
          if (_f_Icon2[i1] == null) return false;
          if (!_f_Icon1[i1].equals(_f_Icon2[i1])) return false;
        } else {
          if (_f_Icon2[i1] != null) return false;
        }
      }
    } else {
      if (_f_Icon2 != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.EnvEntryType[] _f_EnvEntry1 = this.getEnvEntry();
    com.sap.engine.lib.descriptors5.javaee.EnvEntryType[] _f_EnvEntry2 = typed.getEnvEntry();
    if (_f_EnvEntry1 != null) {
      if (_f_EnvEntry2 == null) return false;
      if (_f_EnvEntry1.length != _f_EnvEntry2.length) return false;
      for (int i1 = 0; i1 < _f_EnvEntry1.length ; i1++) {
        if (_f_EnvEntry1[i1] != null) {
          if (_f_EnvEntry2[i1] == null) return false;
          if (!_f_EnvEntry1[i1].equals(_f_EnvEntry2[i1])) return false;
        } else {
          if (_f_EnvEntry2[i1] != null) return false;
        }
      }
    } else {
      if (_f_EnvEntry2 != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.EjbRefType[] _f_EjbRef1 = this.getEjbRef();
    com.sap.engine.lib.descriptors5.javaee.EjbRefType[] _f_EjbRef2 = typed.getEjbRef();
    if (_f_EjbRef1 != null) {
      if (_f_EjbRef2 == null) return false;
      if (_f_EjbRef1.length != _f_EjbRef2.length) return false;
      for (int i1 = 0; i1 < _f_EjbRef1.length ; i1++) {
        if (_f_EjbRef1[i1] != null) {
          if (_f_EjbRef2[i1] == null) return false;
          if (!_f_EjbRef1[i1].equals(_f_EjbRef2[i1])) return false;
        } else {
          if (_f_EjbRef2[i1] != null) return false;
        }
      }
    } else {
      if (_f_EjbRef2 != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.ServiceRefType[] _f_ServiceRef1 = this.getServiceRef();
    com.sap.engine.lib.descriptors5.javaee.ServiceRefType[] _f_ServiceRef2 = typed.getServiceRef();
    if (_f_ServiceRef1 != null) {
      if (_f_ServiceRef2 == null) return false;
      if (_f_ServiceRef1.length != _f_ServiceRef2.length) return false;
      for (int i1 = 0; i1 < _f_ServiceRef1.length ; i1++) {
        if (_f_ServiceRef1[i1] != null) {
          if (_f_ServiceRef2[i1] == null) return false;
          if (!_f_ServiceRef1[i1].equals(_f_ServiceRef2[i1])) return false;
        } else {
          if (_f_ServiceRef2[i1] != null) return false;
        }
      }
    } else {
      if (_f_ServiceRef2 != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.ResourceRefType[] _f_ResourceRef1 = this.getResourceRef();
    com.sap.engine.lib.descriptors5.javaee.ResourceRefType[] _f_ResourceRef2 = typed.getResourceRef();
    if (_f_ResourceRef1 != null) {
      if (_f_ResourceRef2 == null) return false;
      if (_f_ResourceRef1.length != _f_ResourceRef2.length) return false;
      for (int i1 = 0; i1 < _f_ResourceRef1.length ; i1++) {
        if (_f_ResourceRef1[i1] != null) {
          if (_f_ResourceRef2[i1] == null) return false;
          if (!_f_ResourceRef1[i1].equals(_f_ResourceRef2[i1])) return false;
        } else {
          if (_f_ResourceRef2[i1] != null) return false;
        }
      }
    } else {
      if (_f_ResourceRef2 != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.ResourceEnvRefType[] _f_ResourceEnvRef1 = this.getResourceEnvRef();
    com.sap.engine.lib.descriptors5.javaee.ResourceEnvRefType[] _f_ResourceEnvRef2 = typed.getResourceEnvRef();
    if (_f_ResourceEnvRef1 != null) {
      if (_f_ResourceEnvRef2 == null) return false;
      if (_f_ResourceEnvRef1.length != _f_ResourceEnvRef2.length) return false;
      for (int i1 = 0; i1 < _f_ResourceEnvRef1.length ; i1++) {
        if (_f_ResourceEnvRef1[i1] != null) {
          if (_f_ResourceEnvRef2[i1] == null) return false;
          if (!_f_ResourceEnvRef1[i1].equals(_f_ResourceEnvRef2[i1])) return false;
        } else {
          if (_f_ResourceEnvRef2[i1] != null) return false;
        }
      }
    } else {
      if (_f_ResourceEnvRef2 != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.MessageDestinationRefType[] _f_MessageDestinationRef1 = this.getMessageDestinationRef();
    com.sap.engine.lib.descriptors5.javaee.MessageDestinationRefType[] _f_MessageDestinationRef2 = typed.getMessageDestinationRef();
    if (_f_MessageDestinationRef1 != null) {
      if (_f_MessageDestinationRef2 == null) return false;
      if (_f_MessageDestinationRef1.length != _f_MessageDestinationRef2.length) return false;
      for (int i1 = 0; i1 < _f_MessageDestinationRef1.length ; i1++) {
        if (_f_MessageDestinationRef1[i1] != null) {
          if (_f_MessageDestinationRef2[i1] == null) return false;
          if (!_f_MessageDestinationRef1[i1].equals(_f_MessageDestinationRef2[i1])) return false;
        } else {
          if (_f_MessageDestinationRef2[i1] != null) return false;
        }
      }
    } else {
      if (_f_MessageDestinationRef2 != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.PersistenceUnitRefType[] _f_PersistenceUnitRef1 = this.getPersistenceUnitRef();
    com.sap.engine.lib.descriptors5.javaee.PersistenceUnitRefType[] _f_PersistenceUnitRef2 = typed.getPersistenceUnitRef();
    if (_f_PersistenceUnitRef1 != null) {
      if (_f_PersistenceUnitRef2 == null) return false;
      if (_f_PersistenceUnitRef1.length != _f_PersistenceUnitRef2.length) return false;
      for (int i1 = 0; i1 < _f_PersistenceUnitRef1.length ; i1++) {
        if (_f_PersistenceUnitRef1[i1] != null) {
          if (_f_PersistenceUnitRef2[i1] == null) return false;
          if (!_f_PersistenceUnitRef1[i1].equals(_f_PersistenceUnitRef2[i1])) return false;
        } else {
          if (_f_PersistenceUnitRef2[i1] != null) return false;
        }
      }
    } else {
      if (_f_PersistenceUnitRef2 != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[] _f_PostConstruct1 = this.getPostConstruct();
    com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[] _f_PostConstruct2 = typed.getPostConstruct();
    if (_f_PostConstruct1 != null) {
      if (_f_PostConstruct2 == null) return false;
      if (_f_PostConstruct1.length != _f_PostConstruct2.length) return false;
      for (int i1 = 0; i1 < _f_PostConstruct1.length ; i1++) {
        if (_f_PostConstruct1[i1] != null) {
          if (_f_PostConstruct2[i1] == null) return false;
          if (!_f_PostConstruct1[i1].equals(_f_PostConstruct2[i1])) return false;
        } else {
          if (_f_PostConstruct2[i1] != null) return false;
        }
      }
    } else {
      if (_f_PostConstruct2 != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[] _f_PreDestroy1 = this.getPreDestroy();
    com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[] _f_PreDestroy2 = typed.getPreDestroy();
    if (_f_PreDestroy1 != null) {
      if (_f_PreDestroy2 == null) return false;
      if (_f_PreDestroy1.length != _f_PreDestroy2.length) return false;
      for (int i1 = 0; i1 < _f_PreDestroy1.length ; i1++) {
        if (_f_PreDestroy1[i1] != null) {
          if (_f_PreDestroy2[i1] == null) return false;
          if (!_f_PreDestroy1[i1].equals(_f_PreDestroy2[i1])) return false;
        } else {
          if (_f_PreDestroy2[i1] != null) return false;
        }
      }
    } else {
      if (_f_PreDestroy2 != null) return false;
    }
    if (this._f_CallbackHandler != null) {
      if (typed._f_CallbackHandler == null) return false;
      if (!this._f_CallbackHandler.equals(typed._f_CallbackHandler)) return false;
    } else {
      if (typed._f_CallbackHandler != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.MessageDestinationType[] _f_MessageDestination1 = this.getMessageDestination();
    com.sap.engine.lib.descriptors5.javaee.MessageDestinationType[] _f_MessageDestination2 = typed.getMessageDestination();
    if (_f_MessageDestination1 != null) {
      if (_f_MessageDestination2 == null) return false;
      if (_f_MessageDestination1.length != _f_MessageDestination2.length) return false;
      for (int i1 = 0; i1 < _f_MessageDestination1.length ; i1++) {
        if (_f_MessageDestination1[i1] != null) {
          if (_f_MessageDestination2[i1] == null) return false;
          if (!_f_MessageDestination1[i1].equals(_f_MessageDestination2[i1])) return false;
        } else {
          if (_f_MessageDestination2[i1] != null) return false;
        }
      }
    } else {
      if (_f_MessageDestination2 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_Version != null) {
      result+= this._a_Version.hashCode();
    }
    if (this._a_MetadataComplete != null) {
      result+= this._a_MetadataComplete.hashCode();
    }
    if (this._a_Id != null) {
      result+= this._a_Id.hashCode();
    }
    com.sap.engine.lib.descriptors5.javaee.DescriptionType[] _f_Description1 = this.getDescription();
    if (_f_Description1 != null) {
      for (int i1 = 0; i1 < _f_Description1.length ; i1++) {
        if (_f_Description1[i1] != null) {
          result+= _f_Description1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors5.javaee.DisplayNameType[] _f_DisplayName1 = this.getDisplayName();
    if (_f_DisplayName1 != null) {
      for (int i1 = 0; i1 < _f_DisplayName1.length ; i1++) {
        if (_f_DisplayName1[i1] != null) {
          result+= _f_DisplayName1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors5.javaee.IconType[] _f_Icon1 = this.getIcon();
    if (_f_Icon1 != null) {
      for (int i1 = 0; i1 < _f_Icon1.length ; i1++) {
        if (_f_Icon1[i1] != null) {
          result+= _f_Icon1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors5.javaee.EnvEntryType[] _f_EnvEntry1 = this.getEnvEntry();
    if (_f_EnvEntry1 != null) {
      for (int i1 = 0; i1 < _f_EnvEntry1.length ; i1++) {
        if (_f_EnvEntry1[i1] != null) {
          result+= _f_EnvEntry1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors5.javaee.EjbRefType[] _f_EjbRef1 = this.getEjbRef();
    if (_f_EjbRef1 != null) {
      for (int i1 = 0; i1 < _f_EjbRef1.length ; i1++) {
        if (_f_EjbRef1[i1] != null) {
          result+= _f_EjbRef1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors5.javaee.ServiceRefType[] _f_ServiceRef1 = this.getServiceRef();
    if (_f_ServiceRef1 != null) {
      for (int i1 = 0; i1 < _f_ServiceRef1.length ; i1++) {
        if (_f_ServiceRef1[i1] != null) {
          result+= _f_ServiceRef1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors5.javaee.ResourceRefType[] _f_ResourceRef1 = this.getResourceRef();
    if (_f_ResourceRef1 != null) {
      for (int i1 = 0; i1 < _f_ResourceRef1.length ; i1++) {
        if (_f_ResourceRef1[i1] != null) {
          result+= _f_ResourceRef1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors5.javaee.ResourceEnvRefType[] _f_ResourceEnvRef1 = this.getResourceEnvRef();
    if (_f_ResourceEnvRef1 != null) {
      for (int i1 = 0; i1 < _f_ResourceEnvRef1.length ; i1++) {
        if (_f_ResourceEnvRef1[i1] != null) {
          result+= _f_ResourceEnvRef1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors5.javaee.MessageDestinationRefType[] _f_MessageDestinationRef1 = this.getMessageDestinationRef();
    if (_f_MessageDestinationRef1 != null) {
      for (int i1 = 0; i1 < _f_MessageDestinationRef1.length ; i1++) {
        if (_f_MessageDestinationRef1[i1] != null) {
          result+= _f_MessageDestinationRef1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors5.javaee.PersistenceUnitRefType[] _f_PersistenceUnitRef1 = this.getPersistenceUnitRef();
    if (_f_PersistenceUnitRef1 != null) {
      for (int i1 = 0; i1 < _f_PersistenceUnitRef1.length ; i1++) {
        if (_f_PersistenceUnitRef1[i1] != null) {
          result+= _f_PersistenceUnitRef1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[] _f_PostConstruct1 = this.getPostConstruct();
    if (_f_PostConstruct1 != null) {
      for (int i1 = 0; i1 < _f_PostConstruct1.length ; i1++) {
        if (_f_PostConstruct1[i1] != null) {
          result+= _f_PostConstruct1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors5.javaee.LifecycleCallbackType[] _f_PreDestroy1 = this.getPreDestroy();
    if (_f_PreDestroy1 != null) {
      for (int i1 = 0; i1 < _f_PreDestroy1.length ; i1++) {
        if (_f_PreDestroy1[i1] != null) {
          result+= _f_PreDestroy1[i1].hashCode();
        }
      }
    }
    if (this._f_CallbackHandler != null) {
      result+= this._f_CallbackHandler.hashCode();
    }
    com.sap.engine.lib.descriptors5.javaee.MessageDestinationType[] _f_MessageDestination1 = this.getMessageDestination();
    if (_f_MessageDestination1 != null) {
      for (int i1 = 0; i1 < _f_MessageDestination1.length ; i1++) {
        if (_f_MessageDestination1[i1] != null) {
          result+= _f_MessageDestination1[i1].hashCode();
        }
      }
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
