

/*
This file is generated by Code Generator
for CIMClass SAP_ITSAMJavaSchedulerFilter
WARNING:DO NOT CHANGE THE CODE MANUALLY
*/

package com.sap.engine.services.scheduler.runtime.mbean;	

import java.util.Date;
/* 
ManagedElement is an abstract class that provides a common superclass (or top of the inheritance tree) for the non-association classes in the CIM Schema. 
@version 2.7.0	
*/	

public class SAP_ITSAMJavaSchedulerFilter{

private com.sap.engine.services.scheduler.runtime.mbean.SAP_ITSAMJavaSchedulerTime StartTime;

private com.sap.engine.services.scheduler.runtime.mbean.SAP_ITSAMJavaSchedulerTime EndTime;

public SAP_ITSAMJavaSchedulerFilter(){

}

public SAP_ITSAMJavaSchedulerFilter(com.sap.engine.services.scheduler.runtime.mbean.SAP_ITSAMJavaSchedulerTime StartTime,com.sap.engine.services.scheduler.runtime.mbean.SAP_ITSAMJavaSchedulerTime EndTime){
this.StartTime = StartTime;this.EndTime = EndTime;
}

 /*

@return com.sap.engine.services.scheduler.runtime.mbean.SAP_ITSAMJavaSchedulerTime
*/   
public com.sap.engine.services.scheduler.runtime.mbean.SAP_ITSAMJavaSchedulerTime getStartTime() 
{
return this.StartTime;
}

 /*

@return com.sap.engine.services.scheduler.runtime.mbean.SAP_ITSAMJavaSchedulerTime
*/   
public com.sap.engine.services.scheduler.runtime.mbean.SAP_ITSAMJavaSchedulerTime getEndTime() 
{
return this.EndTime;
}
	
}
