/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu May 17 10:24:39 EEST 2007
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.jmsconnector;

/**
 * Schema complexType Java representation.
 * Represents type {}destinationType
 */
public  class DestinationType implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Element field for element {}name
  private java.lang.String _f_Name;
  /**
   * Set method for element {}name
   */
  public void setName(java.lang.String _Name) {
    this._f_Name = _Name;
  }
  /**
   * Get method for element {}name
   */
  public java.lang.String getName() {
    return this._f_Name;
  }

  // Element field for element {}type
  private com.sap.engine.lib.descriptors.jmsconnector.DestinationsRestrictionType _f_Type;
  /**
   * Set method for element {}type
   */
  public void setType(com.sap.engine.lib.descriptors.jmsconnector.DestinationsRestrictionType _Type) {
    this._f_Type = _Type;
  }
  /**
   * Get method for element {}type
   */
  public com.sap.engine.lib.descriptors.jmsconnector.DestinationsRestrictionType getType() {
    return this._f_Type;
  }

  // Model group field class 
  public static class Choice1 implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

    public Choice1() {
    }


    // // Active choise field
    private int _c_validField = 0;
    private com.sap.engine.lib.descriptors.jmsconnector.SapLocalDestinationTypeType _f_SapLocalDestinationType;
    /**
     * Set method for element {}sap-local-destination-type
     */
    public void setSapLocalDestinationType(com.sap.engine.lib.descriptors.jmsconnector.SapLocalDestinationTypeType _SapLocalDestinationType) {
      if (this._c_validField != 0 && this._c_validField != 1) {
        this.unsetContent();
      }
      this._f_SapLocalDestinationType = _SapLocalDestinationType;
      this._c_validField = 1;
    }
    /**
     * Get method for element {}sap-local-destination-type
     */
    public com.sap.engine.lib.descriptors.jmsconnector.SapLocalDestinationTypeType getSapLocalDestinationType() {
      if (this._c_validField != 1) {
        return null;
      }
      return this._f_SapLocalDestinationType;
    }
    /**
     * Check method for element {}sap-local-destination-type
     */
    public boolean isSetSapLocalDestinationType() {
      return (this._c_validField ==1);
    }
    private com.sap.engine.lib.descriptors.jmsconnector.ExternalDestinationTypeType _f_ExternalDestinationType;
    /**
     * Set method for element {}external-destination-type
     */
    public void setExternalDestinationType(com.sap.engine.lib.descriptors.jmsconnector.ExternalDestinationTypeType _ExternalDestinationType) {
      if (this._c_validField != 0 && this._c_validField != 2) {
        this.unsetContent();
      }
      this._f_ExternalDestinationType = _ExternalDestinationType;
      this._c_validField = 2;
    }
    /**
     * Get method for element {}external-destination-type
     */
    public com.sap.engine.lib.descriptors.jmsconnector.ExternalDestinationTypeType getExternalDestinationType() {
      if (this._c_validField != 2) {
        return null;
      }
      return this._f_ExternalDestinationType;
    }
    /**
     * Check method for element {}external-destination-type
     */
    public boolean isSetExternalDestinationType() {
      return (this._c_validField ==2);
    }
    private com.sap.engine.lib.descriptors.jmsconnector.SjoDestinationTypeType _f_SjoDestinationType;
    /**
     * Set method for element {}sjo-destination-type
     */
    public void setSjoDestinationType(com.sap.engine.lib.descriptors.jmsconnector.SjoDestinationTypeType _SjoDestinationType) {
      if (this._c_validField != 0 && this._c_validField != 3) {
        this.unsetContent();
      }
      this._f_SjoDestinationType = _SjoDestinationType;
      this._c_validField = 3;
    }
    /**
     * Get method for element {}sjo-destination-type
     */
    public com.sap.engine.lib.descriptors.jmsconnector.SjoDestinationTypeType getSjoDestinationType() {
      if (this._c_validField != 3) {
        return null;
      }
      return this._f_SjoDestinationType;
    }
    /**
     * Check method for element {}sjo-destination-type
     */
    public boolean isSetSjoDestinationType() {
      return (this._c_validField ==3);
    }
    /**
     * Common get method for choice type.
     */
    public java.lang.Object getContent() {
      switch (this._c_validField) {
        case 1: return this.getSapLocalDestinationType();
        case 2: return this.getExternalDestinationType();
        case 3: return this.getSjoDestinationType();
      }
      return null;
    }
    /**
     * Returns true if this choice has content set.
     */
    public boolean isSetContent() {
      return (this._c_validField == 0);
    }
    /**
     * Clears choice content.
     */
    public void unsetContent() {
      switch (this._c_validField) {
        case  1: {
          this._f_SapLocalDestinationType = null;
          break;
        }
        case  2: {
          this._f_ExternalDestinationType = null;
          break;
        }
        case  3: {
          this._f_SjoDestinationType = null;
          break;
        }
      }
      this._c_validField = 0;
    }

    /**
     * Equals method implementation.
     */
    public boolean equals(Object object) {
      if (object == null) return false;
      if (!(object instanceof Choice1)) return false;
      Choice1 typed = (Choice1) object;
      if (this._c_validField != typed._c_validField) return false;
      switch (this._c_validField) {
        case 1: {
          if (this._f_SapLocalDestinationType != null) {
            if (typed._f_SapLocalDestinationType == null) return false;
            if (!this._f_SapLocalDestinationType.equals(typed._f_SapLocalDestinationType)) return false;
          } else {
            if (typed._f_SapLocalDestinationType != null) return false;
          }
          break;
        }
        case 2: {
          if (this._f_ExternalDestinationType != null) {
            if (typed._f_ExternalDestinationType == null) return false;
            if (!this._f_ExternalDestinationType.equals(typed._f_ExternalDestinationType)) return false;
          } else {
            if (typed._f_ExternalDestinationType != null) return false;
          }
          break;
        }
        case 3: {
          if (this._f_SjoDestinationType != null) {
            if (typed._f_SjoDestinationType == null) return false;
            if (!this._f_SjoDestinationType.equals(typed._f_SjoDestinationType)) return false;
          } else {
            if (typed._f_SjoDestinationType != null) return false;
          }
          break;
        }
      }
      return true;
    }

    /**
     * Hashcode method implementation.
     */
    public int hashCode() {
      int result = 0;
      switch (this._c_validField) {
        case 1: {
          if (this._f_SapLocalDestinationType != null) {
            result+= this._f_SapLocalDestinationType.hashCode();
          }
          result = result * this._c_validField;
          break;
        }
        case 2: {
          if (this._f_ExternalDestinationType != null) {
            result+= this._f_ExternalDestinationType.hashCode();
          }
          result = result * this._c_validField;
          break;
        }
        case 3: {
          if (this._f_SjoDestinationType != null) {
            result+= this._f_SjoDestinationType.hashCode();
          }
          result = result * this._c_validField;
          break;
        }
      }
      return result;
    }

    public java.lang.String get__ID() {
      return java.lang.String.valueOf(super.hashCode());
    }
  }

  private Choice1 _f_ChoiceGroup1;
  public void setChoiceGroup1(Choice1 _ChoiceGroup1) {
    this._f_ChoiceGroup1 = _ChoiceGroup1;
  }
  public Choice1 getChoiceGroup1() {
    return this._f_ChoiceGroup1;
  }

  // Element field for element {}property
  private java.util.ArrayList _f_Property = new java.util.ArrayList();
  /**
   * Set method for element {}property
   */
  public void setProperty(com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] _Property) {
    this._f_Property.clear();
    if (_Property != null) {
      for (int i=0; i<_Property.length; i++) {
        if (_Property[i] != null)
          this._f_Property.add(_Property[i]);
      }
    }
  }
  /**
   * Get method for element {}property
   */
  public com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] getProperty() {
    com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] result = new com.sap.engine.lib.descriptors.jmsconnector.PropertyType[_f_Property.size()];
    _f_Property.toArray(result);
    return result;
  }

  // Element field for element {}description
  private java.lang.String _f_Description;
  /**
   * Set method for element {}description
   */
  public void setDescription(java.lang.String _Description) {
    this._f_Description = _Description;
  }
  /**
   * Get method for element {}description
   */
  public java.lang.String getDescription() {
    return this._f_Description;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof DestinationType)) return false;
    DestinationType typed = (DestinationType) object;
    if (this._f_Name != null) {
      if (typed._f_Name == null) return false;
      if (!this._f_Name.equals(typed._f_Name)) return false;
    } else {
      if (typed._f_Name != null) return false;
    }
    if (this._f_Type != null) {
      if (typed._f_Type == null) return false;
      if (!this._f_Type.equals(typed._f_Type)) return false;
    } else {
      if (typed._f_Type != null) return false;
    }
    if (this._f_ChoiceGroup1 != null) {
      if (typed._f_ChoiceGroup1 == null) return false;
      if (!this._f_ChoiceGroup1.equals(typed._f_ChoiceGroup1)) return false;
    } else {
      if (typed._f_ChoiceGroup1 != null) return false;
    }
    com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] _f_Property1 = this.getProperty();
    com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] _f_Property2 = typed.getProperty();
    if (_f_Property1 != null) {
      if (_f_Property2 == null) return false;
      if (_f_Property1.length != _f_Property2.length) return false;
      for (int i1 = 0; i1 < _f_Property1.length ; i1++) {
        if (_f_Property1[i1] != null) {
          if (_f_Property2[i1] == null) return false;
          if (!_f_Property1[i1].equals(_f_Property2[i1])) return false;
        } else {
          if (_f_Property2[i1] != null) return false;
        }
      }
    } else {
      if (_f_Property2 != null) return false;
    }
    if (this._f_Description != null) {
      if (typed._f_Description == null) return false;
      if (!this._f_Description.equals(typed._f_Description)) return false;
    } else {
      if (typed._f_Description != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Name != null) {
      result+= this._f_Name.hashCode();
    }
    if (this._f_Type != null) {
      result+= this._f_Type.hashCode();
    }
    if (this._f_ChoiceGroup1 != null) {
      result+= this._f_ChoiceGroup1.hashCode();
    }
    com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] _f_Property1 = this.getProperty();
    if (_f_Property1 != null) {
      for (int i1 = 0; i1 < _f_Property1.length ; i1++) {
        if (_f_Property1[i1] != null) {
          result+= _f_Property1[i1].hashCode();
        }
      }
    }
    if (this._f_Description != null) {
      result+= this._f_Description.hashCode();
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
