/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu May 17 10:24:39 EEST 2007
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.jmsconnector;

/**
 * Schema complexType Java representation.
 * Represents type {}initial-context-propertiesType
 */
public  class InitialContextPropertiesType implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Element field for element {}initial-context-factory
  private java.lang.String _f_InitialContextFactory;
  /**
   * Set method for element {}initial-context-factory
   */
  public void setInitialContextFactory(java.lang.String _InitialContextFactory) {
    this._f_InitialContextFactory = _InitialContextFactory;
  }
  /**
   * Get method for element {}initial-context-factory
   */
  public java.lang.String getInitialContextFactory() {
    return this._f_InitialContextFactory;
  }

  // Element field for element {}provider-url
  private java.lang.String _f_ProviderUrl;
  /**
   * Set method for element {}provider-url
   */
  public void setProviderUrl(java.lang.String _ProviderUrl) {
    this._f_ProviderUrl = _ProviderUrl;
  }
  /**
   * Get method for element {}provider-url
   */
  public java.lang.String getProviderUrl() {
    return this._f_ProviderUrl;
  }

  // Element field for element {}security-principal
  private java.lang.String _f_SecurityPrincipal;
  /**
   * Set method for element {}security-principal
   */
  public void setSecurityPrincipal(java.lang.String _SecurityPrincipal) {
    this._f_SecurityPrincipal = _SecurityPrincipal;
  }
  /**
   * Get method for element {}security-principal
   */
  public java.lang.String getSecurityPrincipal() {
    return this._f_SecurityPrincipal;
  }

  // Element field for element {}security-credentials
  private java.lang.String _f_SecurityCredentials;
  /**
   * Set method for element {}security-credentials
   */
  public void setSecurityCredentials(java.lang.String _SecurityCredentials) {
    this._f_SecurityCredentials = _SecurityCredentials;
  }
  /**
   * Get method for element {}security-credentials
   */
  public java.lang.String getSecurityCredentials() {
    return this._f_SecurityCredentials;
  }

  // Element field for element {}property
  private java.util.ArrayList _f_Property = new java.util.ArrayList();
  /**
   * Set method for element {}property
   */
  public void setProperty(com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] _Property) {
    this._f_Property.clear();
    if (_Property != null) {
      for (int i=0; i<_Property.length; i++) {
        if (_Property[i] != null)
          this._f_Property.add(_Property[i]);
      }
    }
  }
  /**
   * Get method for element {}property
   */
  public com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] getProperty() {
    com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] result = new com.sap.engine.lib.descriptors.jmsconnector.PropertyType[_f_Property.size()];
    _f_Property.toArray(result);
    return result;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof InitialContextPropertiesType)) return false;
    InitialContextPropertiesType typed = (InitialContextPropertiesType) object;
    if (this._f_InitialContextFactory != null) {
      if (typed._f_InitialContextFactory == null) return false;
      if (!this._f_InitialContextFactory.equals(typed._f_InitialContextFactory)) return false;
    } else {
      if (typed._f_InitialContextFactory != null) return false;
    }
    if (this._f_ProviderUrl != null) {
      if (typed._f_ProviderUrl == null) return false;
      if (!this._f_ProviderUrl.equals(typed._f_ProviderUrl)) return false;
    } else {
      if (typed._f_ProviderUrl != null) return false;
    }
    if (this._f_SecurityPrincipal != null) {
      if (typed._f_SecurityPrincipal == null) return false;
      if (!this._f_SecurityPrincipal.equals(typed._f_SecurityPrincipal)) return false;
    } else {
      if (typed._f_SecurityPrincipal != null) return false;
    }
    if (this._f_SecurityCredentials != null) {
      if (typed._f_SecurityCredentials == null) return false;
      if (!this._f_SecurityCredentials.equals(typed._f_SecurityCredentials)) return false;
    } else {
      if (typed._f_SecurityCredentials != null) return false;
    }
    com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] _f_Property1 = this.getProperty();
    com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] _f_Property2 = typed.getProperty();
    if (_f_Property1 != null) {
      if (_f_Property2 == null) return false;
      if (_f_Property1.length != _f_Property2.length) return false;
      for (int i1 = 0; i1 < _f_Property1.length ; i1++) {
        if (_f_Property1[i1] != null) {
          if (_f_Property2[i1] == null) return false;
          if (!_f_Property1[i1].equals(_f_Property2[i1])) return false;
        } else {
          if (_f_Property2[i1] != null) return false;
        }
      }
    } else {
      if (_f_Property2 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_InitialContextFactory != null) {
      result+= this._f_InitialContextFactory.hashCode();
    }
    if (this._f_ProviderUrl != null) {
      result+= this._f_ProviderUrl.hashCode();
    }
    if (this._f_SecurityPrincipal != null) {
      result+= this._f_SecurityPrincipal.hashCode();
    }
    if (this._f_SecurityCredentials != null) {
      result+= this._f_SecurityCredentials.hashCode();
    }
    com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] _f_Property1 = this.getProperty();
    if (_f_Property1 != null) {
      for (int i1 = 0; i1 < _f_Property1.length ; i1++) {
        if (_f_Property1[i1] != null) {
          result+= _f_Property1[i1].hashCode();
        }
      }
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
