/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon Jun 18 09:31:26 EEST 2007
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.jmsconnector;

/**
 * Schema complexType Java representation.
 * Represents type {}sap-local-factory-typeType
 */
public  class SapLocalFactoryTypeType implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Element field for element {}type
  private com.sap.engine.lib.descriptors.jmsconnector.TypeType _f_Type;
  /**
   * Set method for element {}type
   */
  public void setType(com.sap.engine.lib.descriptors.jmsconnector.TypeType _Type) {
    this._f_Type = _Type;
  }
  /**
   * Get method for element {}type
   */
  public com.sap.engine.lib.descriptors.jmsconnector.TypeType getType() {
    return this._f_Type;
  }

  // Element field for element {}virtual-provider
  private java.lang.String _f_VirtualProvider = "default";
  /**
   * Set method for element {}virtual-provider
   */
  public void setVirtualProvider(java.lang.String _VirtualProvider) {
    this._f_VirtualProvider = _VirtualProvider;
  }
  /**
   * Get method for element {}virtual-provider
   */
  public java.lang.String getVirtualProvider() {
    return this._f_VirtualProvider;
  }

  // Element field for element {}name
  private java.lang.String _f_Name;
  /**
   * Set method for element {}name
   */
  public void setName(java.lang.String _Name) {
    this._f_Name = _Name;
  }
  /**
   * Get method for element {}name
   */
  public java.lang.String getName() {
    return this._f_Name;
  }

  // Element field for element {}user-name
  private java.lang.String _f_UserName;
  /**
   * Set method for element {}user-name
   */
  public void setUserName(java.lang.String _UserName) {
    this._f_UserName = _UserName;
  }
  /**
   * Get method for element {}user-name
   */
  public java.lang.String getUserName() {
    return this._f_UserName;
  }

  // Element field for element {}password
  private java.lang.String _f_Password;
  /**
   * Set method for element {}password
   */
  public void setPassword(java.lang.String _Password) {
    this._f_Password = _Password;
  }
  /**
   * Get method for element {}password
   */
  public java.lang.String getPassword() {
    return this._f_Password;
  }

  // Element field for element {}property
  private java.util.ArrayList _f_Property = new java.util.ArrayList();
  /**
   * Set method for element {}property
   */
  public void setProperty(com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] _Property) {
    this._f_Property.clear();
    if (_Property != null) {
      for (int i=0; i<_Property.length; i++) {
        if (_Property[i] != null)
          this._f_Property.add(_Property[i]);
      }
    }
  }
  /**
   * Get method for element {}property
   */
  public com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] getProperty() {
    com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] result = new com.sap.engine.lib.descriptors.jmsconnector.PropertyType[_f_Property.size()];
    _f_Property.toArray(result);
    return result;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof SapLocalFactoryTypeType)) return false;
    SapLocalFactoryTypeType typed = (SapLocalFactoryTypeType) object;
    if (this._f_Type != null) {
      if (typed._f_Type == null) return false;
      if (!this._f_Type.equals(typed._f_Type)) return false;
    } else {
      if (typed._f_Type != null) return false;
    }
    if (this._f_VirtualProvider != null) {
      if (typed._f_VirtualProvider == null) return false;
      if (!this._f_VirtualProvider.equals(typed._f_VirtualProvider)) return false;
    } else {
      if (typed._f_VirtualProvider != null) return false;
    }
    if (this._f_Name != null) {
      if (typed._f_Name == null) return false;
      if (!this._f_Name.equals(typed._f_Name)) return false;
    } else {
      if (typed._f_Name != null) return false;
    }
    if (this._f_UserName != null) {
      if (typed._f_UserName == null) return false;
      if (!this._f_UserName.equals(typed._f_UserName)) return false;
    } else {
      if (typed._f_UserName != null) return false;
    }
    if (this._f_Password != null) {
      if (typed._f_Password == null) return false;
      if (!this._f_Password.equals(typed._f_Password)) return false;
    } else {
      if (typed._f_Password != null) return false;
    }
    com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] _f_Property1 = this.getProperty();
    com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] _f_Property2 = typed.getProperty();
    if (_f_Property1 != null) {
      if (_f_Property2 == null) return false;
      if (_f_Property1.length != _f_Property2.length) return false;
      for (int i1 = 0; i1 < _f_Property1.length ; i1++) {
        if (_f_Property1[i1] != null) {
          if (_f_Property2[i1] == null) return false;
          if (!_f_Property1[i1].equals(_f_Property2[i1])) return false;
        } else {
          if (_f_Property2[i1] != null) return false;
        }
      }
    } else {
      if (_f_Property2 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Type != null) {
      result+= this._f_Type.hashCode();
    }
    if (this._f_VirtualProvider != null) {
      result+= this._f_VirtualProvider.hashCode();
    }
    if (this._f_Name != null) {
      result+= this._f_Name.hashCode();
    }
    if (this._f_UserName != null) {
      result+= this._f_UserName.hashCode();
    }
    if (this._f_Password != null) {
      result+= this._f_Password.hashCode();
    }
    com.sap.engine.lib.descriptors.jmsconnector.PropertyType[] _f_Property1 = this.getProperty();
    if (_f_Property1 != null) {
      for (int i1 = 0; i1 < _f_Property1.length ; i1++) {
        if (_f_Property1[i1] != null) {
          result+= _f_Property1[i1].hashCode();
        }
      }
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
