/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu May 05 11:42:02 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ws04vi;

/**
 * Schema complexType Java representation.
 * Represents type of namespace {http://xml.sap.com/2002/10/metamodel/vi} anonymous with xpath [/xsd:schema/xsd:element[4]/xsd:complexType]
 */
public  class CoreAnnotations implements java.io.Serializable,java.lang.Cloneable {

  // Element field for element {http://xml.sap.com/2002/10/metamodel/vi}Core.Annotation
  private java.util.ArrayList _f_CoreAnnotation = new java.util.ArrayList();
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}Core.Annotation
   */
  public void setCoreAnnotation(com.sap.engine.lib.descriptors.ws04vi.CoreAnnotation[] _CoreAnnotation) {
    this._f_CoreAnnotation.clear();
    if (_CoreAnnotation != null) {
      for (int i=0; i<_CoreAnnotation.length; i++) {
        if (_CoreAnnotation[i] != null)
          this._f_CoreAnnotation.add(_CoreAnnotation[i]);
      }
    }
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}Core.Annotation
   */
  public com.sap.engine.lib.descriptors.ws04vi.CoreAnnotation[] getCoreAnnotation() {
    com.sap.engine.lib.descriptors.ws04vi.CoreAnnotation[] result = new com.sap.engine.lib.descriptors.ws04vi.CoreAnnotation[_f_CoreAnnotation.size()];
    _f_CoreAnnotation.toArray(result);
    return result;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof CoreAnnotations)) return false;
    CoreAnnotations typed = (CoreAnnotations) object;
    com.sap.engine.lib.descriptors.ws04vi.CoreAnnotation[] _f_CoreAnnotation1 = this.getCoreAnnotation();
    com.sap.engine.lib.descriptors.ws04vi.CoreAnnotation[] _f_CoreAnnotation2 = typed.getCoreAnnotation();
    if (_f_CoreAnnotation1 != null) {
      if (_f_CoreAnnotation2 == null) return false;
      if (_f_CoreAnnotation1.length != _f_CoreAnnotation2.length) return false;
      for (int i1 = 0; i1 < _f_CoreAnnotation1.length ; i1++) {
        if (_f_CoreAnnotation1[i1] != null) {
          if (_f_CoreAnnotation2[i1] == null) return false;
          if (!_f_CoreAnnotation1[i1].equals(_f_CoreAnnotation2[i1])) return false;
        } else {
          if (_f_CoreAnnotation2[i1] != null) return false;
        }
      }
    } else {
      if (_f_CoreAnnotation2 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    com.sap.engine.lib.descriptors.ws04vi.CoreAnnotation[] _f_CoreAnnotation1 = this.getCoreAnnotation();
    if (_f_CoreAnnotation1 != null) {
      for (int i1 = 0; i1 < _f_CoreAnnotation1.length ; i1++) {
        if (_f_CoreAnnotation1[i1] != null) {
          result+= _f_CoreAnnotation1[i1].hashCode();
        }
      }
    }
    return result;
  }
}
