/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu May 05 11:42:02 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ws04vi;

/**
 * Schema complexType Java representation.
 * Represents type of namespace {http://xml.sap.com/2002/10/metamodel/vi} anonymous with xpath [/xsd:schema/xsd:complexType[33]/xsd:complexContent/xsd:extension/xsd:sequence/xsd:element[3]/xsd:complexType]
 */
public  class ParameterMappedTypeReference implements java.io.Serializable,java.lang.Cloneable {

  // // Active choise field
  private int _c_validField = 0;
  private com.sap.engine.lib.descriptors.ws04vi.ComplexTypeReferenceState _f_ComplexTypeReference;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}ComplexTypeReference
   */
  public void setComplexTypeReference(com.sap.engine.lib.descriptors.ws04vi.ComplexTypeReferenceState _ComplexTypeReference) {
    if (this._c_validField != 0 && this._c_validField != 1) {
      this.unsetContent();
    }
    this._f_ComplexTypeReference = _ComplexTypeReference;
    this._c_validField = 1;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}ComplexTypeReference
   */
  public com.sap.engine.lib.descriptors.ws04vi.ComplexTypeReferenceState getComplexTypeReference() {
    if (this._c_validField != 1) {
      return null;
    }
    return this._f_ComplexTypeReference;
  }
  /**
   * Check method for element {http://xml.sap.com/2002/10/metamodel/vi}ComplexTypeReference
   */
  public boolean isSetComplexTypeReference() {
    return (this._c_validField ==1);
  }
  private com.sap.engine.lib.descriptors.ws04vi.ConvertedTableReferenceState _f_ConvertedTableReference;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}ConvertedTableReference
   */
  public void setConvertedTableReference(com.sap.engine.lib.descriptors.ws04vi.ConvertedTableReferenceState _ConvertedTableReference) {
    if (this._c_validField != 0 && this._c_validField != 2) {
      this.unsetContent();
    }
    this._f_ConvertedTableReference = _ConvertedTableReference;
    this._c_validField = 2;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}ConvertedTableReference
   */
  public com.sap.engine.lib.descriptors.ws04vi.ConvertedTableReferenceState getConvertedTableReference() {
    if (this._c_validField != 2) {
      return null;
    }
    return this._f_ConvertedTableReference;
  }
  /**
   * Check method for element {http://xml.sap.com/2002/10/metamodel/vi}ConvertedTableReference
   */
  public boolean isSetConvertedTableReference() {
    return (this._c_validField ==2);
  }
  private com.sap.engine.lib.descriptors.ws04vi.ConvertedTypeReferenceState _f_ConvertedTypeReference;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}ConvertedTypeReference
   */
  public void setConvertedTypeReference(com.sap.engine.lib.descriptors.ws04vi.ConvertedTypeReferenceState _ConvertedTypeReference) {
    if (this._c_validField != 0 && this._c_validField != 3) {
      this.unsetContent();
    }
    this._f_ConvertedTypeReference = _ConvertedTypeReference;
    this._c_validField = 3;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}ConvertedTypeReference
   */
  public com.sap.engine.lib.descriptors.ws04vi.ConvertedTypeReferenceState getConvertedTypeReference() {
    if (this._c_validField != 3) {
      return null;
    }
    return this._f_ConvertedTypeReference;
  }
  /**
   * Check method for element {http://xml.sap.com/2002/10/metamodel/vi}ConvertedTypeReference
   */
  public boolean isSetConvertedTypeReference() {
    return (this._c_validField ==3);
  }
  private com.sap.engine.lib.descriptors.ws04vi.FaultState _f_Fault;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}Fault
   */
  public void setFault(com.sap.engine.lib.descriptors.ws04vi.FaultState _Fault) {
    if (this._c_validField != 0 && this._c_validField != 4) {
      this.unsetContent();
    }
    this._f_Fault = _Fault;
    this._c_validField = 4;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}Fault
   */
  public com.sap.engine.lib.descriptors.ws04vi.FaultState getFault() {
    if (this._c_validField != 4) {
      return null;
    }
    return this._f_Fault;
  }
  /**
   * Check method for element {http://xml.sap.com/2002/10/metamodel/vi}Fault
   */
  public boolean isSetFault() {
    return (this._c_validField ==4);
  }
  private com.sap.engine.lib.descriptors.ws04vi.InlineComplexTableReferenceState _f_InlineComplexTableReference;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}InlineComplexTableReference
   */
  public void setInlineComplexTableReference(com.sap.engine.lib.descriptors.ws04vi.InlineComplexTableReferenceState _InlineComplexTableReference) {
    if (this._c_validField != 0 && this._c_validField != 5) {
      this.unsetContent();
    }
    this._f_InlineComplexTableReference = _InlineComplexTableReference;
    this._c_validField = 5;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}InlineComplexTableReference
   */
  public com.sap.engine.lib.descriptors.ws04vi.InlineComplexTableReferenceState getInlineComplexTableReference() {
    if (this._c_validField != 5) {
      return null;
    }
    return this._f_InlineComplexTableReference;
  }
  /**
   * Check method for element {http://xml.sap.com/2002/10/metamodel/vi}InlineComplexTableReference
   */
  public boolean isSetInlineComplexTableReference() {
    return (this._c_validField ==5);
  }
  private com.sap.engine.lib.descriptors.ws04vi.InlinePrimitiveTableReferenceState _f_InlinePrimitiveTableReference;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}InlinePrimitiveTableReference
   */
  public void setInlinePrimitiveTableReference(com.sap.engine.lib.descriptors.ws04vi.InlinePrimitiveTableReferenceState _InlinePrimitiveTableReference) {
    if (this._c_validField != 0 && this._c_validField != 6) {
      this.unsetContent();
    }
    this._f_InlinePrimitiveTableReference = _InlinePrimitiveTableReference;
    this._c_validField = 6;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}InlinePrimitiveTableReference
   */
  public com.sap.engine.lib.descriptors.ws04vi.InlinePrimitiveTableReferenceState getInlinePrimitiveTableReference() {
    if (this._c_validField != 6) {
      return null;
    }
    return this._f_InlinePrimitiveTableReference;
  }
  /**
   * Check method for element {http://xml.sap.com/2002/10/metamodel/vi}InlinePrimitiveTableReference
   */
  public boolean isSetInlinePrimitiveTableReference() {
    return (this._c_validField ==6);
  }
  /**
   * Common get method for choice type.
   */
  public java.lang.Object getContent() {
    switch (this._c_validField) {
      case 1: return this._f_ComplexTypeReference;
      case 2: return this._f_ConvertedTableReference;
      case 3: return this._f_ConvertedTypeReference;
      case 4: return this._f_Fault;
      case 5: return this._f_InlineComplexTableReference;
      case 6: return this._f_InlinePrimitiveTableReference;
    }
    return null;
  }
  /**
   * Returns true if this choice has content set.
   */
  public boolean isSetContent() {
    return (this._c_validField == 0);
  }
  /**
   * Clears choice content.
   */
  public void unsetContent() {
    switch (this._c_validField) {
      case  1: {
        this._f_ComplexTypeReference = null;
        break;
      }
      case  2: {
        this._f_ConvertedTableReference = null;
        break;
      }
      case  3: {
        this._f_ConvertedTypeReference = null;
        break;
      }
      case  4: {
        this._f_Fault = null;
        break;
      }
      case  5: {
        this._f_InlineComplexTableReference = null;
        break;
      }
      case  6: {
        this._f_InlinePrimitiveTableReference = null;
        break;
      }
    }
    this._c_validField = 0;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof ParameterMappedTypeReference)) return false;
    ParameterMappedTypeReference typed = (ParameterMappedTypeReference) object;
    if (this._c_validField != typed._c_validField) return false;
    switch (this._c_validField) {
      case 1: {
        if (this._f_ComplexTypeReference != null) {
          if (typed._f_ComplexTypeReference == null) return false;
          if (!this._f_ComplexTypeReference.equals(typed._f_ComplexTypeReference)) return false;
        } else {
          if (typed._f_ComplexTypeReference != null) return false;
        }
        break;
      }
      case 2: {
        if (this._f_ConvertedTableReference != null) {
          if (typed._f_ConvertedTableReference == null) return false;
          if (!this._f_ConvertedTableReference.equals(typed._f_ConvertedTableReference)) return false;
        } else {
          if (typed._f_ConvertedTableReference != null) return false;
        }
        break;
      }
      case 3: {
        if (this._f_ConvertedTypeReference != null) {
          if (typed._f_ConvertedTypeReference == null) return false;
          if (!this._f_ConvertedTypeReference.equals(typed._f_ConvertedTypeReference)) return false;
        } else {
          if (typed._f_ConvertedTypeReference != null) return false;
        }
        break;
      }
      case 4: {
        if (this._f_Fault != null) {
          if (typed._f_Fault == null) return false;
          if (!this._f_Fault.equals(typed._f_Fault)) return false;
        } else {
          if (typed._f_Fault != null) return false;
        }
        break;
      }
      case 5: {
        if (this._f_InlineComplexTableReference != null) {
          if (typed._f_InlineComplexTableReference == null) return false;
          if (!this._f_InlineComplexTableReference.equals(typed._f_InlineComplexTableReference)) return false;
        } else {
          if (typed._f_InlineComplexTableReference != null) return false;
        }
        break;
      }
      case 6: {
        if (this._f_InlinePrimitiveTableReference != null) {
          if (typed._f_InlinePrimitiveTableReference == null) return false;
          if (!this._f_InlinePrimitiveTableReference.equals(typed._f_InlinePrimitiveTableReference)) return false;
        } else {
          if (typed._f_InlinePrimitiveTableReference != null) return false;
        }
        break;
      }
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    switch (this._c_validField) {
      case 1: {
        if (this._f_ComplexTypeReference != null) {
          result+= this._f_ComplexTypeReference.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
      case 2: {
        if (this._f_ConvertedTableReference != null) {
          result+= this._f_ConvertedTableReference.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
      case 3: {
        if (this._f_ConvertedTypeReference != null) {
          result+= this._f_ConvertedTypeReference.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
      case 4: {
        if (this._f_Fault != null) {
          result+= this._f_Fault.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
      case 5: {
        if (this._f_InlineComplexTableReference != null) {
          result+= this._f_InlineComplexTableReference.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
      case 6: {
        if (this._f_InlinePrimitiveTableReference != null) {
          result+= this._f_InlinePrimitiveTableReference.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
    }
    return result;
  }
}
