/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu May 05 11:42:02 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ws04vi;

/**
 * Schema complexType Java representation.
 * Represents type {http://xml.sap.com/2002/10/metamodel/vi}TableState
 */
public  class TableState extends com.sap.engine.lib.descriptors.ws04vi.TypeState implements java.io.Serializable,java.lang.Cloneable {

  // Attribute field for attribute {}isAbstract
  private boolean _a_IsAbstract = false;
  /**
   * Set method for attribute {}isAbstract
   */
  public void setIsAbstract(boolean _IsAbstract) {
    this._a_IsAbstract = _IsAbstract;
  }
  /**
   * Get method for attribute {}isAbstract
   */
  public boolean isIsAbstract() {
    return _a_IsAbstract;
  }

  // Attribute field for attribute {}isInterface
  private boolean _a_IsInterface = false;
  /**
   * Set method for attribute {}isInterface
   */
  public void setIsInterface(boolean _IsInterface) {
    this._a_IsInterface = _IsInterface;
  }
  /**
   * Get method for attribute {}isInterface
   */
  public boolean isIsInterface() {
    return _a_IsInterface;
  }

  // Attribute field for attribute {}parentTypeName
  private java.lang.String _a_ParentTypeName;
  /**
   * Set method for attribute {}parentTypeName
   */
  public void setParentTypeName(java.lang.String _ParentTypeName) {
    this._a_ParentTypeName = _ParentTypeName;
  }
  /**
   * Get method for attribute {}parentTypeName
   */
  public java.lang.String getParentTypeName() {
    return _a_ParentTypeName;
  }

  // Attribute field for attribute {}name
  private java.lang.String _a_Name;
  /**
   * Set method for attribute {}name
   */
  public void setName(java.lang.String _Name) {
    this._a_Name = _Name;
  }
  /**
   * Get method for attribute {}name
   */
  public java.lang.String getName() {
    return _a_Name;
  }

  // Element field for element {http://xml.sap.com/2002/10/metamodel/vi}Table.LineType
  private com.sap.engine.lib.descriptors.ws04vi.TableLineType _f_TableLineType;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}Table.LineType
   */
  public void setTableLineType(com.sap.engine.lib.descriptors.ws04vi.TableLineType _TableLineType) {
    this._f_TableLineType = _TableLineType;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}Table.LineType
   */
  public com.sap.engine.lib.descriptors.ws04vi.TableLineType getTableLineType() {
    return this._f_TableLineType;
  }

  // Element field for element {http://xml.sap.com/2002/10/metamodel/vi}Table.SoapExtensionTable
  private com.sap.engine.lib.descriptors.ws04vi.TableSoapExtensionTable _f_TableSoapExtensionTable;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}Table.SoapExtensionTable
   */
  public void setTableSoapExtensionTable(com.sap.engine.lib.descriptors.ws04vi.TableSoapExtensionTable _TableSoapExtensionTable) {
    this._f_TableSoapExtensionTable = _TableSoapExtensionTable;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}Table.SoapExtensionTable
   */
  public com.sap.engine.lib.descriptors.ws04vi.TableSoapExtensionTable getTableSoapExtensionTable() {
    return this._f_TableSoapExtensionTable;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (super.equals(object) == false) return false;
    if (object == null) return false;
    if (!(object instanceof TableState)) return false;
    TableState typed = (TableState) object;
    if (this._a_IsAbstract != typed._a_IsAbstract) return false;
    if (this._a_IsInterface != typed._a_IsInterface) return false;
    if (this._a_ParentTypeName != null) {
      if (typed._a_ParentTypeName == null) return false;
      if (!this._a_ParentTypeName.equals(typed._a_ParentTypeName)) return false;
    } else {
      if (typed._a_ParentTypeName != null) return false;
    }
    if (this._a_Name != null) {
      if (typed._a_Name == null) return false;
      if (!this._a_Name.equals(typed._a_Name)) return false;
    } else {
      if (typed._a_Name != null) return false;
    }
    if (this._f_TableLineType != null) {
      if (typed._f_TableLineType == null) return false;
      if (!this._f_TableLineType.equals(typed._f_TableLineType)) return false;
    } else {
      if (typed._f_TableLineType != null) return false;
    }
    if (this._f_TableSoapExtensionTable != null) {
      if (typed._f_TableSoapExtensionTable == null) return false;
      if (!this._f_TableSoapExtensionTable.equals(typed._f_TableSoapExtensionTable)) return false;
    } else {
      if (typed._f_TableSoapExtensionTable != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = super.hashCode();
    if (this._a_IsAbstract) result += 1;
    if (this._a_IsInterface) result += 1;
    if (this._a_ParentTypeName != null) {
      result+= this._a_ParentTypeName.hashCode();
    }
    if (this._a_Name != null) {
      result+= this._a_Name.hashCode();
    }
    if (this._f_TableLineType != null) {
      result+= this._f_TableLineType.hashCode();
    }
    if (this._f_TableSoapExtensionTable != null) {
      result+= this._f_TableSoapExtensionTable.hashCode();
    }
    return result;
  }
}
