/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu May 05 11:42:02 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ws04vi;

/**
 * Schema complexType Java representation.
 * Represents type of namespace {http://xml.sap.com/2002/10/metamodel/vi} anonymous with xpath [/xsd:schema/xsd:complexType[2]/xsd:complexContent/xsd:extension/xsd:sequence/xsd:element[2]/xsd:complexType]
 */
public  class TypeSoapExtensionType implements java.io.Serializable,java.lang.Cloneable {

  // Element field for element {http://xml.sap.com/2002/10/metamodel/vi}SoapExtensionType
  private com.sap.engine.lib.descriptors.ws04vi.SoapExtensionTypeState _f_SoapExtensionType;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}SoapExtensionType
   */
  public void setSoapExtensionType(com.sap.engine.lib.descriptors.ws04vi.SoapExtensionTypeState _SoapExtensionType) {
    this._f_SoapExtensionType = _SoapExtensionType;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}SoapExtensionType
   */
  public com.sap.engine.lib.descriptors.ws04vi.SoapExtensionTypeState getSoapExtensionType() {
    return this._f_SoapExtensionType;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof TypeSoapExtensionType)) return false;
    TypeSoapExtensionType typed = (TypeSoapExtensionType) object;
    if (this._f_SoapExtensionType != null) {
      if (typed._f_SoapExtensionType == null) return false;
      if (!this._f_SoapExtensionType.equals(typed._f_SoapExtensionType)) return false;
    } else {
      if (typed._f_SoapExtensionType != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_SoapExtensionType != null) {
      result+= this._f_SoapExtensionType.hashCode();
    }
    return result;
  }
}
