/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu May 05 11:42:02 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ws04vi;

/**
 * Schema complexType Java representation.
 * Represents type {http://xml.sap.com/2002/10/metamodel/vi}TypeState
 */
public  class TypeState extends com.sap.engine.lib.descriptors.ws04vi.DevelopmentObjectState implements java.io.Serializable,java.lang.Cloneable {

  // Attribute field for attribute {}isAbstract
  private boolean _a_IsAbstract = false;
  /**
   * Set method for attribute {}isAbstract
   */
  public void setIsAbstract(boolean _IsAbstract) {
    this._a_IsAbstract = _IsAbstract;
  }
  /**
   * Get method for attribute {}isAbstract
   */
  public boolean isIsAbstract() {
    return _a_IsAbstract;
  }

  // Attribute field for attribute {}isInterface
  private boolean _a_IsInterface = false;
  /**
   * Set method for attribute {}isInterface
   */
  public void setIsInterface(boolean _IsInterface) {
    this._a_IsInterface = _IsInterface;
  }
  /**
   * Get method for attribute {}isInterface
   */
  public boolean isIsInterface() {
    return _a_IsInterface;
  }

  // Attribute field for attribute {}parentTypeName
  private java.lang.String _a_ParentTypeName;
  /**
   * Set method for attribute {}parentTypeName
   */
  public void setParentTypeName(java.lang.String _ParentTypeName) {
    this._a_ParentTypeName = _ParentTypeName;
  }
  /**
   * Get method for attribute {}parentTypeName
   */
  public java.lang.String getParentTypeName() {
    return _a_ParentTypeName;
  }

  // Attribute field for attribute {}name
  private java.lang.String _a_Name;
  /**
   * Set method for attribute {}name
   */
  public void setName(java.lang.String _Name) {
    this._a_Name = _Name;
  }
  /**
   * Get method for attribute {}name
   */
  public java.lang.String getName() {
    return _a_Name;
  }

  // Element field for element {http://xml.sap.com/2002/10/metamodel/vi}Type.Original
  private com.sap.engine.lib.descriptors.ws04vi.TypeOriginal _f_TypeOriginal;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}Type.Original
   */
  public void setTypeOriginal(com.sap.engine.lib.descriptors.ws04vi.TypeOriginal _TypeOriginal) {
    this._f_TypeOriginal = _TypeOriginal;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}Type.Original
   */
  public com.sap.engine.lib.descriptors.ws04vi.TypeOriginal getTypeOriginal() {
    return this._f_TypeOriginal;
  }

  // Element field for element {http://xml.sap.com/2002/10/metamodel/vi}Type.SoapExtensionType
  private com.sap.engine.lib.descriptors.ws04vi.TypeSoapExtensionType _f_TypeSoapExtensionType;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}Type.SoapExtensionType
   */
  public void setTypeSoapExtensionType(com.sap.engine.lib.descriptors.ws04vi.TypeSoapExtensionType _TypeSoapExtensionType) {
    this._f_TypeSoapExtensionType = _TypeSoapExtensionType;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}Type.SoapExtensionType
   */
  public com.sap.engine.lib.descriptors.ws04vi.TypeSoapExtensionType getTypeSoapExtensionType() {
    return this._f_TypeSoapExtensionType;
  }

  // Element field for element {http://xml.sap.com/2002/10/metamodel/vi}Type.ParentTypes
  private com.sap.engine.lib.descriptors.ws04vi.TypeParentTypes _f_TypeParentTypes;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}Type.ParentTypes
   */
  public void setTypeParentTypes(com.sap.engine.lib.descriptors.ws04vi.TypeParentTypes _TypeParentTypes) {
    this._f_TypeParentTypes = _TypeParentTypes;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}Type.ParentTypes
   */
  public com.sap.engine.lib.descriptors.ws04vi.TypeParentTypes getTypeParentTypes() {
    return this._f_TypeParentTypes;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (super.equals(object) == false) return false;
    if (object == null) return false;
    if (!(object instanceof TypeState)) return false;
    TypeState typed = (TypeState) object;
    if (this._a_IsAbstract != typed._a_IsAbstract) return false;
    if (this._a_IsInterface != typed._a_IsInterface) return false;
    if (this._a_ParentTypeName != null) {
      if (typed._a_ParentTypeName == null) return false;
      if (!this._a_ParentTypeName.equals(typed._a_ParentTypeName)) return false;
    } else {
      if (typed._a_ParentTypeName != null) return false;
    }
    if (this._a_Name != null) {
      if (typed._a_Name == null) return false;
      if (!this._a_Name.equals(typed._a_Name)) return false;
    } else {
      if (typed._a_Name != null) return false;
    }
    if (this._f_TypeOriginal != null) {
      if (typed._f_TypeOriginal == null) return false;
      if (!this._f_TypeOriginal.equals(typed._f_TypeOriginal)) return false;
    } else {
      if (typed._f_TypeOriginal != null) return false;
    }
    if (this._f_TypeSoapExtensionType != null) {
      if (typed._f_TypeSoapExtensionType == null) return false;
      if (!this._f_TypeSoapExtensionType.equals(typed._f_TypeSoapExtensionType)) return false;
    } else {
      if (typed._f_TypeSoapExtensionType != null) return false;
    }
    if (this._f_TypeParentTypes != null) {
      if (typed._f_TypeParentTypes == null) return false;
      if (!this._f_TypeParentTypes.equals(typed._f_TypeParentTypes)) return false;
    } else {
      if (typed._f_TypeParentTypes != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = super.hashCode();
    if (this._a_IsAbstract) result += 1;
    if (this._a_IsInterface) result += 1;
    if (this._a_ParentTypeName != null) {
      result+= this._a_ParentTypeName.hashCode();
    }
    if (this._a_Name != null) {
      result+= this._a_Name.hashCode();
    }
    if (this._f_TypeOriginal != null) {
      result+= this._f_TypeOriginal.hashCode();
    }
    if (this._f_TypeSoapExtensionType != null) {
      result+= this._f_TypeSoapExtensionType.hashCode();
    }
    if (this._f_TypeParentTypes != null) {
      result+= this._f_TypeParentTypes.hashCode();
    }
    return result;
  }
}
