/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu May 05 11:42:02 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ws04vi;

/**
 * Schema complexType Java representation.
 * Represents type of namespace {http://xml.sap.com/2002/10/metamodel/vi} anonymous with xpath [/xsd:schema/xsd:complexType[23]/xsd:complexContent/xsd:extension/xsd:sequence/xsd:element[1]/xsd:complexType]
 */
public  class VirtualInterfaceEndpointReference implements java.io.Serializable,java.lang.Cloneable {

  // // Active choise field
  private int _c_validField = 0;
  private com.sap.engine.lib.descriptors.ws04vi.AbapFunctionModuleReferenceState _f_AbapFunctionModuleReference;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}AbapFunctionModuleReference
   */
  public void setAbapFunctionModuleReference(com.sap.engine.lib.descriptors.ws04vi.AbapFunctionModuleReferenceState _AbapFunctionModuleReference) {
    if (this._c_validField != 0 && this._c_validField != 1) {
      this.unsetContent();
    }
    this._f_AbapFunctionModuleReference = _AbapFunctionModuleReference;
    this._c_validField = 1;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}AbapFunctionModuleReference
   */
  public com.sap.engine.lib.descriptors.ws04vi.AbapFunctionModuleReferenceState getAbapFunctionModuleReference() {
    if (this._c_validField != 1) {
      return null;
    }
    return this._f_AbapFunctionModuleReference;
  }
  /**
   * Check method for element {http://xml.sap.com/2002/10/metamodel/vi}AbapFunctionModuleReference
   */
  public boolean isSetAbapFunctionModuleReference() {
    return (this._c_validField ==1);
  }
  private com.sap.engine.lib.descriptors.ws04vi.ClassEndpointReferenceState _f_ClassEndpointReference;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}ClassEndpointReference
   */
  public void setClassEndpointReference(com.sap.engine.lib.descriptors.ws04vi.ClassEndpointReferenceState _ClassEndpointReference) {
    if (this._c_validField != 0 && this._c_validField != 2) {
      this.unsetContent();
    }
    this._f_ClassEndpointReference = _ClassEndpointReference;
    this._c_validField = 2;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}ClassEndpointReference
   */
  public com.sap.engine.lib.descriptors.ws04vi.ClassEndpointReferenceState getClassEndpointReference() {
    if (this._c_validField != 2) {
      return null;
    }
    return this._f_ClassEndpointReference;
  }
  /**
   * Check method for element {http://xml.sap.com/2002/10/metamodel/vi}ClassEndpointReference
   */
  public boolean isSetClassEndpointReference() {
    return (this._c_validField ==2);
  }
  private com.sap.engine.lib.descriptors.ws04vi.EjbEndpointReferenceState _f_EjbEndpointReference;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}EjbEndpointReference
   */
  public void setEjbEndpointReference(com.sap.engine.lib.descriptors.ws04vi.EjbEndpointReferenceState _EjbEndpointReference) {
    if (this._c_validField != 0 && this._c_validField != 3) {
      this.unsetContent();
    }
    this._f_EjbEndpointReference = _EjbEndpointReference;
    this._c_validField = 3;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}EjbEndpointReference
   */
  public com.sap.engine.lib.descriptors.ws04vi.EjbEndpointReferenceState getEjbEndpointReference() {
    if (this._c_validField != 3) {
      return null;
    }
    return this._f_EjbEndpointReference;
  }
  /**
   * Check method for element {http://xml.sap.com/2002/10/metamodel/vi}EjbEndpointReference
   */
  public boolean isSetEjbEndpointReference() {
    return (this._c_validField ==3);
  }
  private com.sap.engine.lib.descriptors.ws04vi.ParEndpointReferenceState _f_ParEndpointReference;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/vi}ParEndpointReference
   */
  public void setParEndpointReference(com.sap.engine.lib.descriptors.ws04vi.ParEndpointReferenceState _ParEndpointReference) {
    if (this._c_validField != 0 && this._c_validField != 4) {
      this.unsetContent();
    }
    this._f_ParEndpointReference = _ParEndpointReference;
    this._c_validField = 4;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/vi}ParEndpointReference
   */
  public com.sap.engine.lib.descriptors.ws04vi.ParEndpointReferenceState getParEndpointReference() {
    if (this._c_validField != 4) {
      return null;
    }
    return this._f_ParEndpointReference;
  }
  /**
   * Check method for element {http://xml.sap.com/2002/10/metamodel/vi}ParEndpointReference
   */
  public boolean isSetParEndpointReference() {
    return (this._c_validField ==4);
  }
  /**
   * Common get method for choice type.
   */
  public java.lang.Object getContent() {
    switch (this._c_validField) {
      case 1: return this._f_AbapFunctionModuleReference;
      case 2: return this._f_ClassEndpointReference;
      case 3: return this._f_EjbEndpointReference;
      case 4: return this._f_ParEndpointReference;
    }
    return null;
  }
  /**
   * Returns true if this choice has content set.
   */
  public boolean isSetContent() {
    return (this._c_validField == 0);
  }
  /**
   * Clears choice content.
   */
  public void unsetContent() {
    switch (this._c_validField) {
      case  1: {
        this._f_AbapFunctionModuleReference = null;
        break;
      }
      case  2: {
        this._f_ClassEndpointReference = null;
        break;
      }
      case  3: {
        this._f_EjbEndpointReference = null;
        break;
      }
      case  4: {
        this._f_ParEndpointReference = null;
        break;
      }
    }
    this._c_validField = 0;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof VirtualInterfaceEndpointReference)) return false;
    VirtualInterfaceEndpointReference typed = (VirtualInterfaceEndpointReference) object;
    if (this._c_validField != typed._c_validField) return false;
    switch (this._c_validField) {
      case 1: {
        if (this._f_AbapFunctionModuleReference != null) {
          if (typed._f_AbapFunctionModuleReference == null) return false;
          if (!this._f_AbapFunctionModuleReference.equals(typed._f_AbapFunctionModuleReference)) return false;
        } else {
          if (typed._f_AbapFunctionModuleReference != null) return false;
        }
        break;
      }
      case 2: {
        if (this._f_ClassEndpointReference != null) {
          if (typed._f_ClassEndpointReference == null) return false;
          if (!this._f_ClassEndpointReference.equals(typed._f_ClassEndpointReference)) return false;
        } else {
          if (typed._f_ClassEndpointReference != null) return false;
        }
        break;
      }
      case 3: {
        if (this._f_EjbEndpointReference != null) {
          if (typed._f_EjbEndpointReference == null) return false;
          if (!this._f_EjbEndpointReference.equals(typed._f_EjbEndpointReference)) return false;
        } else {
          if (typed._f_EjbEndpointReference != null) return false;
        }
        break;
      }
      case 4: {
        if (this._f_ParEndpointReference != null) {
          if (typed._f_ParEndpointReference == null) return false;
          if (!this._f_ParEndpointReference.equals(typed._f_ParEndpointReference)) return false;
        } else {
          if (typed._f_ParEndpointReference != null) return false;
        }
        break;
      }
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    switch (this._c_validField) {
      case 1: {
        if (this._f_AbapFunctionModuleReference != null) {
          result+= this._f_AbapFunctionModuleReference.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
      case 2: {
        if (this._f_ClassEndpointReference != null) {
          result+= this._f_ClassEndpointReference.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
      case 3: {
        if (this._f_EjbEndpointReference != null) {
          result+= this._f_EjbEndpointReference.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
      case 4: {
        if (this._f_ParEndpointReference != null) {
          result+= this._f_ParEndpointReference.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
    }
    return result;
  }
}
