/*
 * Generated by SAP SchemaToJava Generator NW05 on Wed Jun 14 11:13:11 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors5.webfacesconfig;

/**
 * Enumeration Java representation.
 * Represents type {http://java.sun.com/xml/ns/javaee}faces-config-versionType
 */
public class FacesConfigVersionType implements java.io.Serializable {

  public static final java.lang.String _Enum12 = "1.2";

  public static final FacesConfigVersionType Enum12 = new FacesConfigVersionType(_Enum12);

  //  Enumeration Content
  protected java.lang.String _value;

  public FacesConfigVersionType(java.lang.String _value) {
    if (_Enum12.equals(_value)) {
      this._value = _value;
      return;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+_value+"] passed.");
  }

  public java.lang.String getValue() {
    return _value;
  }

  public static FacesConfigVersionType fromValue(java.lang.String value) {
    if (_Enum12.equals(value)) {
      return Enum12;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+value+"] passed.");
  }

  public static FacesConfigVersionType fromString(String value) {
    if ("1.2".equals(value)) {
      return Enum12;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+value+"] passed.");
  }

  public java.lang.String toString() {
    if (_Enum12.equals(_value)) {
      return "1.2";
    }
    return java.lang.String.valueOf(_value);
  }

  public boolean equals(java.lang.Object obj) {
    if (obj != null) {
      if (obj instanceof FacesConfigVersionType) {
        if (_value.equals(((FacesConfigVersionType)obj)._value)) {
          return true;
        }
      }
    }
    return false;
  }

  public int hashCode() {
    return this._value.hashCode();
  }

}
