/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Oct 19 11:20:17 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors5.ejb;

/**
 * Schema complexType Java representation.
 * Represents type {http://java.sun.com/xml/ns/javaee}named-methodType
 */
public  class NamedMethodType implements java.io.Serializable {

  private static final long serialVersionUID = 2174798832344170751L;

  // Attribute field for attribute {}id
  private java.lang.String _a_Id;
  /**
   * Set method for attribute {}id
   */
  public void setId(java.lang.String _Id) {
    this._a_Id = _Id;
  }
  /**
   * Get method for attribute {}id
   */
  public java.lang.String getId() {
    return _a_Id;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}method-name
  private com.sap.engine.lib.descriptors5.javaee.String _f_MethodName;
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}method-name
   */
  public void setMethodName(com.sap.engine.lib.descriptors5.javaee.String _MethodName) {
    this._f_MethodName = _MethodName;
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}method-name
   */
  public com.sap.engine.lib.descriptors5.javaee.String getMethodName() {
    return this._f_MethodName;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}method-params
  private com.sap.engine.lib.descriptors5.ejb.MethodParamsType _f_MethodParams;
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}method-params
   */
  public void setMethodParams(com.sap.engine.lib.descriptors5.ejb.MethodParamsType _MethodParams) {
    this._f_MethodParams = _MethodParams;
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}method-params
   */
  public com.sap.engine.lib.descriptors5.ejb.MethodParamsType getMethodParams() {
    return this._f_MethodParams;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof NamedMethodType)) return false;
    NamedMethodType typed = (NamedMethodType) object;
    if (this._a_Id != null) {
      if (typed._a_Id == null) return false;
      if (!this._a_Id.equals(typed._a_Id)) return false;
    } else {
      if (typed._a_Id != null) return false;
    }
    if (this._f_MethodName != null) {
      if (typed._f_MethodName == null) return false;
      if (!this._f_MethodName.equals(typed._f_MethodName)) return false;
    } else {
      if (typed._f_MethodName != null) return false;
    }
    if (this._f_MethodParams != null) {
      if (typed._f_MethodParams == null) return false;
      if (!this._f_MethodParams.equals(typed._f_MethodParams)) return false;
    } else {
      if (typed._f_MethodParams != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_Id != null) {
      result+= this._a_Id.hashCode();
    }
    if (this._f_MethodName != null) {
      result+= this._f_MethodName.hashCode();
    }
    if (this._f_MethodParams != null) {
      result+= this._f_MethodParams.hashCode();
    }
    return result;
  }
}
