export function getFieldLayout(){
        const detail = [
        {Id:'0', label: "Claim Number", value:''},
        {Id:'1', label: "Claim Number", value:''},
        {Id:'2', label: "Claim Number", value:''},
        {Id:'3', label: "Claim Number", value:''},
        {Id:'4', label: "Claim Number", value:''},
        {Id:'5', label: "Claim Number", value:''},
        {Id:'6', label: "Claim Number", value:''},
        {Id:'7', label: "Claim Number", value:''},
        {Id:'8', label: "Claim Number", value:''},
        {Id:'9', label: "Claim Number", value:''}, 
        {Id:'10', label: "Claim Number", value:''},
        {Id:'11', label: "Claim Number", value:''},
        {Id:'12', label: "Claim Number", value:''},
        {Id:'13', label: "Claim Number", value:''},
        {Id:'14', label: "Claim Number", value:''},
        {Id:'15', label: "Claim Number", value:''},
        {Id:'16', label: "Claim Number", value:''},
        {Id:'17', label: "Claim Number", value:''},
        {Id:'18', label: "Claim Number", value:''},
        {Id:'19', label: "Claim Number", value:''},
        {Id:'20', label: "Claim Number", value:''},
        {Id:'21', label: "Claim Number", value:''},
        {Id:'22', label: "Claim Number", value:''},
        {Id:'23', label: "Claim Number", value:''},
        {Id:'24', label: "Claim Number", value:''},
        ];
    return detail;
};