/*
 * Generated by SAP SchemaToJava Generator NW05 on Tue Jul 19 13:29:42 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.applicationj2eeengine;

/**
 * Schema complexType Java representation.
 * Represents type {}modules-additionalType
 */
public  class ModulesAdditionalType implements java.io.Serializable,java.lang.Cloneable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Element field for element {}module
  private java.util.ArrayList _f_Module = new java.util.ArrayList();
  /**
   * Set method for element {}module
   */
  public void setModule(com.sap.engine.lib.descriptors.applicationj2eeengine.ModuleType[] _Module) {
    this._f_Module.clear();
    if (_Module != null) {
      for (int i=0; i<_Module.length; i++) {
        if (_Module[i] != null)
          this._f_Module.add(_Module[i]);
      }
    }
  }
  /**
   * Get method for element {}module
   */
  public com.sap.engine.lib.descriptors.applicationj2eeengine.ModuleType[] getModule() {
    com.sap.engine.lib.descriptors.applicationj2eeengine.ModuleType[] result = new com.sap.engine.lib.descriptors.applicationj2eeengine.ModuleType[_f_Module.size()];
    _f_Module.toArray(result);
    return result;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof ModulesAdditionalType)) return false;
    ModulesAdditionalType typed = (ModulesAdditionalType) object;
    com.sap.engine.lib.descriptors.applicationj2eeengine.ModuleType[] _f_Module1 = this.getModule();
    com.sap.engine.lib.descriptors.applicationj2eeengine.ModuleType[] _f_Module2 = typed.getModule();
    if (_f_Module1 != null) {
      if (_f_Module2 == null) return false;
      if (_f_Module1.length != _f_Module2.length) return false;
      for (int i1 = 0; i1 < _f_Module1.length ; i1++) {
        if (_f_Module1[i1] != null) {
          if (_f_Module2[i1] == null) return false;
          if (!_f_Module1[i1].equals(_f_Module2[i1])) return false;
        } else {
          if (_f_Module2[i1] != null) return false;
        }
      }
    } else {
      if (_f_Module2 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    com.sap.engine.lib.descriptors.applicationj2eeengine.ModuleType[] _f_Module1 = this.getModule();
    if (_f_Module1 != null) {
      for (int i1 = 0; i1 < _f_Module1.length ; i1++) {
        if (_f_Module1[i1] != null) {
          result+= _f_Module1[i1].hashCode();
        }
      }
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
