/*
 * Generated by SAP SchemaToJava Generator NW05 on Wed Apr 26 17:41:35 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ejbj2eeengine;

/**
 * Schema complexType Java representation.
 * Represents type of namespace {} anonymous with xpath [/xs:schema/xs:element[8]/xs:complexType]
 */
public  class EjbJ2EeEngine implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Element field for element {}description
  private java.lang.String _f_Description;
  /**
   * Set method for element {}description
   */
  public void setDescription(java.lang.String _Description) {
    this._f_Description = _Description;
  }
  /**
   * Get method for element {}description
   */
  public java.lang.String getDescription() {
    return this._f_Description;
  }

  // Element field for element {}enterprise-beans
  private com.sap.engine.lib.descriptors.ejbj2eeengine.EnterpriseBeansType _f_EnterpriseBeans;
  /**
   * Set method for element {}enterprise-beans
   */
  public void setEnterpriseBeans(com.sap.engine.lib.descriptors.ejbj2eeengine.EnterpriseBeansType _EnterpriseBeans) {
    this._f_EnterpriseBeans = _EnterpriseBeans;
  }
  /**
   * Get method for element {}enterprise-beans
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.EnterpriseBeansType getEnterpriseBeans() {
    return this._f_EnterpriseBeans;
  }

  // Element field for element {}transaction-descriptor
  private com.sap.engine.lib.descriptors.ejbj2eeengine.TransactionDescriptorType _f_TransactionDescriptor;
  /**
   * Set method for element {}transaction-descriptor
   */
  public void setTransactionDescriptor(com.sap.engine.lib.descriptors.ejbj2eeengine.TransactionDescriptorType _TransactionDescriptor) {
    this._f_TransactionDescriptor = _TransactionDescriptor;
  }
  /**
   * Get method for element {}transaction-descriptor
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.TransactionDescriptorType getTransactionDescriptor() {
    return this._f_TransactionDescriptor;
  }

  // Element field for element {}security-permission
  private com.sap.engine.lib.descriptors.ejbj2eeengine.SecurityPermissionType _f_SecurityPermission;
  /**
   * Set method for element {}security-permission
   */
  public void setSecurityPermission(com.sap.engine.lib.descriptors.ejbj2eeengine.SecurityPermissionType _SecurityPermission) {
    this._f_SecurityPermission = _SecurityPermission;
  }
  /**
   * Get method for element {}security-permission
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.SecurityPermissionType getSecurityPermission() {
    return this._f_SecurityPermission;
  }

  // Element field for element {}message-destination-maps
  private com.sap.engine.lib.descriptors.ejbj2eeengine.MessageDestinationMapsType _f_MessageDestinationMaps;
  /**
   * Set method for element {}message-destination-maps
   */
  public void setMessageDestinationMaps(com.sap.engine.lib.descriptors.ejbj2eeengine.MessageDestinationMapsType _MessageDestinationMaps) {
    this._f_MessageDestinationMaps = _MessageDestinationMaps;
  }
  /**
   * Get method for element {}message-destination-maps
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.MessageDestinationMapsType getMessageDestinationMaps() {
    return this._f_MessageDestinationMaps;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof EjbJ2EeEngine)) return false;
    EjbJ2EeEngine typed = (EjbJ2EeEngine) object;
    if (this._f_Description != null) {
      if (typed._f_Description == null) return false;
      if (!this._f_Description.equals(typed._f_Description)) return false;
    } else {
      if (typed._f_Description != null) return false;
    }
    if (this._f_EnterpriseBeans != null) {
      if (typed._f_EnterpriseBeans == null) return false;
      if (!this._f_EnterpriseBeans.equals(typed._f_EnterpriseBeans)) return false;
    } else {
      if (typed._f_EnterpriseBeans != null) return false;
    }
    if (this._f_TransactionDescriptor != null) {
      if (typed._f_TransactionDescriptor == null) return false;
      if (!this._f_TransactionDescriptor.equals(typed._f_TransactionDescriptor)) return false;
    } else {
      if (typed._f_TransactionDescriptor != null) return false;
    }
    if (this._f_SecurityPermission != null) {
      if (typed._f_SecurityPermission == null) return false;
      if (!this._f_SecurityPermission.equals(typed._f_SecurityPermission)) return false;
    } else {
      if (typed._f_SecurityPermission != null) return false;
    }
    if (this._f_MessageDestinationMaps != null) {
      if (typed._f_MessageDestinationMaps == null) return false;
      if (!this._f_MessageDestinationMaps.equals(typed._f_MessageDestinationMaps)) return false;
    } else {
      if (typed._f_MessageDestinationMaps != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Description != null) {
      result+= this._f_Description.hashCode();
    }
    if (this._f_EnterpriseBeans != null) {
      result+= this._f_EnterpriseBeans.hashCode();
    }
    if (this._f_TransactionDescriptor != null) {
      result+= this._f_TransactionDescriptor.hashCode();
    }
    if (this._f_SecurityPermission != null) {
      result+= this._f_SecurityPermission.hashCode();
    }
    if (this._f_MessageDestinationMaps != null) {
      result+= this._f_MessageDestinationMaps.hashCode();
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
