/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 31 10:03:54 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ejbj2eeengine;

/**
 * Schema complexType Java representation.
 * Represents type {}enterprise-beansType
 */
public  class EnterpriseBeansType implements java.io.Serializable,java.lang.Cloneable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Element field for element {}enterprise-bean
  private java.util.ArrayList _f_EnterpriseBean = new java.util.ArrayList();
  /**
   * Set method for element {}enterprise-bean
   */
  public void setEnterpriseBean(com.sap.engine.lib.descriptors.ejbj2eeengine.EnterpriseBeanType[] _EnterpriseBean) {
    this._f_EnterpriseBean.clear();
    if (_EnterpriseBean != null) {
      for (int i=0; i<_EnterpriseBean.length; i++) {
        if (_EnterpriseBean[i] != null)
          this._f_EnterpriseBean.add(_EnterpriseBean[i]);
      }
    }
  }
  /**
   * Get method for element {}enterprise-bean
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.EnterpriseBeanType[] getEnterpriseBean() {
    com.sap.engine.lib.descriptors.ejbj2eeengine.EnterpriseBeanType[] result = new com.sap.engine.lib.descriptors.ejbj2eeengine.EnterpriseBeanType[_f_EnterpriseBean.size()];
    _f_EnterpriseBean.toArray(result);
    return result;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof EnterpriseBeansType)) return false;
    EnterpriseBeansType typed = (EnterpriseBeansType) object;
    com.sap.engine.lib.descriptors.ejbj2eeengine.EnterpriseBeanType[] _f_EnterpriseBean1 = this.getEnterpriseBean();
    com.sap.engine.lib.descriptors.ejbj2eeengine.EnterpriseBeanType[] _f_EnterpriseBean2 = typed.getEnterpriseBean();
    if (_f_EnterpriseBean1 != null) {
      if (_f_EnterpriseBean2 == null) return false;
      if (_f_EnterpriseBean1.length != _f_EnterpriseBean2.length) return false;
      for (int i1 = 0; i1 < _f_EnterpriseBean1.length ; i1++) {
        if (_f_EnterpriseBean1[i1] != null) {
          if (_f_EnterpriseBean2[i1] == null) return false;
          if (!_f_EnterpriseBean1[i1].equals(_f_EnterpriseBean2[i1])) return false;
        } else {
          if (_f_EnterpriseBean2[i1] != null) return false;
        }
      }
    } else {
      if (_f_EnterpriseBean2 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    com.sap.engine.lib.descriptors.ejbj2eeengine.EnterpriseBeanType[] _f_EnterpriseBean1 = this.getEnterpriseBean();
    if (_f_EnterpriseBean1 != null) {
      for (int i1 = 0; i1 < _f_EnterpriseBean1.length ; i1++) {
        if (_f_EnterpriseBean1[i1] != null) {
          result+= _f_EnterpriseBean1[i1].hashCode();
        }
      }
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
