/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 31 10:03:54 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ejbj2eeengine;

/**
 * Schema complexType Java representation.
 * Represents type {}enterprise-beanType
 */
public  class EnterpriseBeanType implements java.io.Serializable,java.lang.Cloneable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Element field for element {}ejb-name
  private java.lang.String _f_EjbName;
  /**
   * Set method for element {}ejb-name
   */
  public void setEjbName(java.lang.String _EjbName) {
    this._f_EjbName = _EjbName;
  }
  /**
   * Get method for element {}ejb-name
   */
  public java.lang.String getEjbName() {
    return this._f_EjbName;
  }

  // Element field for element {}jndi-name
  private java.lang.String _f_JndiName;
  /**
   * Set method for element {}jndi-name
   */
  public void setJndiName(java.lang.String _JndiName) {
    this._f_JndiName = _JndiName;
  }
  /**
   * Get method for element {}jndi-name
   */
  public java.lang.String getJndiName() {
    return this._f_JndiName;
  }

  // Element field for element {}container-size
  private java.lang.String _f_ContainerSize;
  /**
   * Set method for element {}container-size
   */
  public void setContainerSize(java.lang.String _ContainerSize) {
    this._f_ContainerSize = _ContainerSize;
  }
  /**
   * Get method for element {}container-size
   */
  public java.lang.String getContainerSize() {
    return this._f_ContainerSize;
  }

  // Element field for element {}ejb-ref
  private java.util.ArrayList _f_EjbRef = new java.util.ArrayList();
  /**
   * Set method for element {}ejb-ref
   */
  public void setEjbRef(com.sap.engine.lib.descriptors.ejbj2eeengine.EjbRefType[] _EjbRef) {
    this._f_EjbRef.clear();
    if (_EjbRef != null) {
      for (int i=0; i<_EjbRef.length; i++) {
        if (_EjbRef[i] != null)
          this._f_EjbRef.add(_EjbRef[i]);
      }
    }
  }
  /**
   * Get method for element {}ejb-ref
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.EjbRefType[] getEjbRef() {
    com.sap.engine.lib.descriptors.ejbj2eeengine.EjbRefType[] result = new com.sap.engine.lib.descriptors.ejbj2eeengine.EjbRefType[_f_EjbRef.size()];
    _f_EjbRef.toArray(result);
    return result;
  }

  // Element field for element {}ejb-local-ref
  private java.util.ArrayList _f_EjbLocalRef = new java.util.ArrayList();
  /**
   * Set method for element {}ejb-local-ref
   */
  public void setEjbLocalRef(com.sap.engine.lib.descriptors.ejbj2eeengine.EjbLocalRefType[] _EjbLocalRef) {
    this._f_EjbLocalRef.clear();
    if (_EjbLocalRef != null) {
      for (int i=0; i<_EjbLocalRef.length; i++) {
        if (_EjbLocalRef[i] != null)
          this._f_EjbLocalRef.add(_EjbLocalRef[i]);
      }
    }
  }
  /**
   * Get method for element {}ejb-local-ref
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.EjbLocalRefType[] getEjbLocalRef() {
    com.sap.engine.lib.descriptors.ejbj2eeengine.EjbLocalRefType[] result = new com.sap.engine.lib.descriptors.ejbj2eeengine.EjbLocalRefType[_f_EjbLocalRef.size()];
    _f_EjbLocalRef.toArray(result);
    return result;
  }

  // Element field for element {}resource-ref
  private java.util.ArrayList _f_ResourceRef = new java.util.ArrayList();
  /**
   * Set method for element {}resource-ref
   */
  public void setResourceRef(com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceRefType[] _ResourceRef) {
    this._f_ResourceRef.clear();
    if (_ResourceRef != null) {
      for (int i=0; i<_ResourceRef.length; i++) {
        if (_ResourceRef[i] != null)
          this._f_ResourceRef.add(_ResourceRef[i]);
      }
    }
  }
  /**
   * Get method for element {}resource-ref
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceRefType[] getResourceRef() {
    com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceRefType[] result = new com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceRefType[_f_ResourceRef.size()];
    _f_ResourceRef.toArray(result);
    return result;
  }

  // Element field for element {}resource-env-ref
  private java.util.ArrayList _f_ResourceEnvRef = new java.util.ArrayList();
  /**
   * Set method for element {}resource-env-ref
   */
  public void setResourceEnvRef(com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceEnvRefType[] _ResourceEnvRef) {
    this._f_ResourceEnvRef.clear();
    if (_ResourceEnvRef != null) {
      for (int i=0; i<_ResourceEnvRef.length; i++) {
        if (_ResourceEnvRef[i] != null)
          this._f_ResourceEnvRef.add(_ResourceEnvRef[i]);
      }
    }
  }
  /**
   * Get method for element {}resource-env-ref
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceEnvRefType[] getResourceEnvRef() {
    com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceEnvRefType[] result = new com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceEnvRefType[_f_ResourceEnvRef.size()];
    _f_ResourceEnvRef.toArray(result);
    return result;
  }

  // Element field for element {}server-component-ref
  private java.util.ArrayList _f_ServerComponentRef = new java.util.ArrayList();
  /**
   * Set method for element {}server-component-ref
   */
  public void setServerComponentRef(com.sap.engine.lib.descriptors.ejbj2eeengine.ServerComponentRefType[] _ServerComponentRef) {
    this._f_ServerComponentRef.clear();
    if (_ServerComponentRef != null) {
      for (int i=0; i<_ServerComponentRef.length; i++) {
        if (_ServerComponentRef[i] != null)
          this._f_ServerComponentRef.add(_ServerComponentRef[i]);
      }
    }
  }
  /**
   * Get method for element {}server-component-ref
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.ServerComponentRefType[] getServerComponentRef() {
    com.sap.engine.lib.descriptors.ejbj2eeengine.ServerComponentRefType[] result = new com.sap.engine.lib.descriptors.ejbj2eeengine.ServerComponentRefType[_f_ServerComponentRef.size()];
    _f_ServerComponentRef.toArray(result);
    return result;
  }

  // Element field for element {}run-as-identity-map
  private com.sap.engine.lib.descriptors.ejbj2eeengine.RunAsIdentityMapType _f_RunAsIdentityMap;
  /**
   * Set method for element {}run-as-identity-map
   */
  public void setRunAsIdentityMap(com.sap.engine.lib.descriptors.ejbj2eeengine.RunAsIdentityMapType _RunAsIdentityMap) {
    this._f_RunAsIdentityMap = _RunAsIdentityMap;
  }
  /**
   * Get method for element {}run-as-identity-map
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.RunAsIdentityMapType getRunAsIdentityMap() {
    return this._f_RunAsIdentityMap;
  }

  // Element field for element {}ior-security-config
  private java.util.ArrayList _f_IorSecurityConfig = new java.util.ArrayList();
  /**
   * Set method for element {}ior-security-config
   */
  public void setIorSecurityConfig(com.sap.engine.lib.descriptors.ejbj2eeengine.IorSecurityConfigType[] _IorSecurityConfig) {
    this._f_IorSecurityConfig.clear();
    if (_IorSecurityConfig != null) {
      for (int i=0; i<_IorSecurityConfig.length; i++) {
        if (_IorSecurityConfig[i] != null)
          this._f_IorSecurityConfig.add(_IorSecurityConfig[i]);
      }
    }
  }
  /**
   * Get method for element {}ior-security-config
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.IorSecurityConfigType[] getIorSecurityConfig() {
    com.sap.engine.lib.descriptors.ejbj2eeengine.IorSecurityConfigType[] result = new com.sap.engine.lib.descriptors.ejbj2eeengine.IorSecurityConfigType[_f_IorSecurityConfig.size()];
    _f_IorSecurityConfig.toArray(result);
    return result;
  }

  // Model group field class 
  public static class Choice1 implements java.io.Serializable,java.lang.Cloneable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

    public Choice1() {
    }


    // // Active choise field
    private int _c_validField = 0;
    private com.sap.engine.lib.descriptors.ejbj2eeengine.SessionPropsType _f_SessionProps;
    /**
     * Set method for element {}session-props
     */
    public void setSessionProps(com.sap.engine.lib.descriptors.ejbj2eeengine.SessionPropsType _SessionProps) {
      if (this._c_validField != 0 && this._c_validField != 1) {
        this.unsetContent();
      }
      this._f_SessionProps = _SessionProps;
      this._c_validField = 1;
    }
    /**
     * Get method for element {}session-props
     */
    public com.sap.engine.lib.descriptors.ejbj2eeengine.SessionPropsType getSessionProps() {
      if (this._c_validField != 1) {
        return null;
      }
      return this._f_SessionProps;
    }
    /**
     * Check method for element {}session-props
     */
    public boolean isSetSessionProps() {
      return (this._c_validField ==1);
    }
    private com.sap.engine.lib.descriptors.ejbj2eeengine.EntityPropsType _f_EntityProps;
    /**
     * Set method for element {}entity-props
     */
    public void setEntityProps(com.sap.engine.lib.descriptors.ejbj2eeengine.EntityPropsType _EntityProps) {
      if (this._c_validField != 0 && this._c_validField != 2) {
        this.unsetContent();
      }
      this._f_EntityProps = _EntityProps;
      this._c_validField = 2;
    }
    /**
     * Get method for element {}entity-props
     */
    public com.sap.engine.lib.descriptors.ejbj2eeengine.EntityPropsType getEntityProps() {
      if (this._c_validField != 2) {
        return null;
      }
      return this._f_EntityProps;
    }
    /**
     * Check method for element {}entity-props
     */
    public boolean isSetEntityProps() {
      return (this._c_validField ==2);
    }
    private com.sap.engine.lib.descriptors.ejbj2eeengine.MessagePropsType _f_MessageProps;
    /**
     * Set method for element {}message-props
     */
    public void setMessageProps(com.sap.engine.lib.descriptors.ejbj2eeengine.MessagePropsType _MessageProps) {
      if (this._c_validField != 0 && this._c_validField != 3) {
        this.unsetContent();
      }
      this._f_MessageProps = _MessageProps;
      this._c_validField = 3;
    }
    /**
     * Get method for element {}message-props
     */
    public com.sap.engine.lib.descriptors.ejbj2eeengine.MessagePropsType getMessageProps() {
      if (this._c_validField != 3) {
        return null;
      }
      return this._f_MessageProps;
    }
    /**
     * Check method for element {}message-props
     */
    public boolean isSetMessageProps() {
      return (this._c_validField ==3);
    }
    /**
     * Common get method for choice type.
     */
    public java.lang.Object getContent() {
      switch (this._c_validField) {
        case 1: return this._f_SessionProps;
        case 2: return this._f_EntityProps;
        case 3: return this._f_MessageProps;
      }
      return null;
    }
    /**
     * Returns true if this choice has content set.
     */
    public boolean isSetContent() {
      return (this._c_validField == 0);
    }
    /**
     * Clears choice content.
     */
    public void unsetContent() {
      switch (this._c_validField) {
        case  1: {
          this._f_SessionProps = null;
          break;
        }
        case  2: {
          this._f_EntityProps = null;
          break;
        }
        case  3: {
          this._f_MessageProps = null;
          break;
        }
      }
      this._c_validField = 0;
    }

    /**
     * Equals method implementation.
     */
    public boolean equals(Object object) {
      if (object == null) return false;
      if (!(object instanceof Choice1)) return false;
      Choice1 typed = (Choice1) object;
      if (this._c_validField != typed._c_validField) return false;
      switch (this._c_validField) {
        case 1: {
          if (this._f_SessionProps != null) {
            if (typed._f_SessionProps == null) return false;
            if (!this._f_SessionProps.equals(typed._f_SessionProps)) return false;
          } else {
            if (typed._f_SessionProps != null) return false;
          }
          break;
        }
        case 2: {
          if (this._f_EntityProps != null) {
            if (typed._f_EntityProps == null) return false;
            if (!this._f_EntityProps.equals(typed._f_EntityProps)) return false;
          } else {
            if (typed._f_EntityProps != null) return false;
          }
          break;
        }
        case 3: {
          if (this._f_MessageProps != null) {
            if (typed._f_MessageProps == null) return false;
            if (!this._f_MessageProps.equals(typed._f_MessageProps)) return false;
          } else {
            if (typed._f_MessageProps != null) return false;
          }
          break;
        }
      }
      return true;
    }

    /**
     * Hashcode method implementation.
     */
    public int hashCode() {
      int result = 0;
      switch (this._c_validField) {
        case 1: {
          if (this._f_SessionProps != null) {
            result+= this._f_SessionProps.hashCode();
          }
          result = result * this._c_validField;
          break;
        }
        case 2: {
          if (this._f_EntityProps != null) {
            result+= this._f_EntityProps.hashCode();
          }
          result = result * this._c_validField;
          break;
        }
        case 3: {
          if (this._f_MessageProps != null) {
            result+= this._f_MessageProps.hashCode();
          }
          result = result * this._c_validField;
          break;
        }
      }
      return result;
    }

    public java.lang.String get__ID() {
      return java.lang.String.valueOf(super.hashCode());
    }
  }

  private Choice1 _f_ChoiceGroup1;
  public void setChoiceGroup1(Choice1 _ChoiceGroup1) {
    this._f_ChoiceGroup1 = _ChoiceGroup1;
  }
  public Choice1 getChoiceGroup1() {
    return this._f_ChoiceGroup1;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof EnterpriseBeanType)) return false;
    EnterpriseBeanType typed = (EnterpriseBeanType) object;
    if (this._f_EjbName != null) {
      if (typed._f_EjbName == null) return false;
      if (!this._f_EjbName.equals(typed._f_EjbName)) return false;
    } else {
      if (typed._f_EjbName != null) return false;
    }
    if (this._f_JndiName != null) {
      if (typed._f_JndiName == null) return false;
      if (!this._f_JndiName.equals(typed._f_JndiName)) return false;
    } else {
      if (typed._f_JndiName != null) return false;
    }
    if (this._f_ContainerSize != null) {
      if (typed._f_ContainerSize == null) return false;
      if (!this._f_ContainerSize.equals(typed._f_ContainerSize)) return false;
    } else {
      if (typed._f_ContainerSize != null) return false;
    }
    com.sap.engine.lib.descriptors.ejbj2eeengine.EjbRefType[] _f_EjbRef1 = this.getEjbRef();
    com.sap.engine.lib.descriptors.ejbj2eeengine.EjbRefType[] _f_EjbRef2 = typed.getEjbRef();
    if (_f_EjbRef1 != null) {
      if (_f_EjbRef2 == null) return false;
      if (_f_EjbRef1.length != _f_EjbRef2.length) return false;
      for (int i1 = 0; i1 < _f_EjbRef1.length ; i1++) {
        if (_f_EjbRef1[i1] != null) {
          if (_f_EjbRef2[i1] == null) return false;
          if (!_f_EjbRef1[i1].equals(_f_EjbRef2[i1])) return false;
        } else {
          if (_f_EjbRef2[i1] != null) return false;
        }
      }
    } else {
      if (_f_EjbRef2 != null) return false;
    }
    com.sap.engine.lib.descriptors.ejbj2eeengine.EjbLocalRefType[] _f_EjbLocalRef1 = this.getEjbLocalRef();
    com.sap.engine.lib.descriptors.ejbj2eeengine.EjbLocalRefType[] _f_EjbLocalRef2 = typed.getEjbLocalRef();
    if (_f_EjbLocalRef1 != null) {
      if (_f_EjbLocalRef2 == null) return false;
      if (_f_EjbLocalRef1.length != _f_EjbLocalRef2.length) return false;
      for (int i1 = 0; i1 < _f_EjbLocalRef1.length ; i1++) {
        if (_f_EjbLocalRef1[i1] != null) {
          if (_f_EjbLocalRef2[i1] == null) return false;
          if (!_f_EjbLocalRef1[i1].equals(_f_EjbLocalRef2[i1])) return false;
        } else {
          if (_f_EjbLocalRef2[i1] != null) return false;
        }
      }
    } else {
      if (_f_EjbLocalRef2 != null) return false;
    }
    com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceRefType[] _f_ResourceRef1 = this.getResourceRef();
    com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceRefType[] _f_ResourceRef2 = typed.getResourceRef();
    if (_f_ResourceRef1 != null) {
      if (_f_ResourceRef2 == null) return false;
      if (_f_ResourceRef1.length != _f_ResourceRef2.length) return false;
      for (int i1 = 0; i1 < _f_ResourceRef1.length ; i1++) {
        if (_f_ResourceRef1[i1] != null) {
          if (_f_ResourceRef2[i1] == null) return false;
          if (!_f_ResourceRef1[i1].equals(_f_ResourceRef2[i1])) return false;
        } else {
          if (_f_ResourceRef2[i1] != null) return false;
        }
      }
    } else {
      if (_f_ResourceRef2 != null) return false;
    }
    com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceEnvRefType[] _f_ResourceEnvRef1 = this.getResourceEnvRef();
    com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceEnvRefType[] _f_ResourceEnvRef2 = typed.getResourceEnvRef();
    if (_f_ResourceEnvRef1 != null) {
      if (_f_ResourceEnvRef2 == null) return false;
      if (_f_ResourceEnvRef1.length != _f_ResourceEnvRef2.length) return false;
      for (int i1 = 0; i1 < _f_ResourceEnvRef1.length ; i1++) {
        if (_f_ResourceEnvRef1[i1] != null) {
          if (_f_ResourceEnvRef2[i1] == null) return false;
          if (!_f_ResourceEnvRef1[i1].equals(_f_ResourceEnvRef2[i1])) return false;
        } else {
          if (_f_ResourceEnvRef2[i1] != null) return false;
        }
      }
    } else {
      if (_f_ResourceEnvRef2 != null) return false;
    }
    com.sap.engine.lib.descriptors.ejbj2eeengine.ServerComponentRefType[] _f_ServerComponentRef1 = this.getServerComponentRef();
    com.sap.engine.lib.descriptors.ejbj2eeengine.ServerComponentRefType[] _f_ServerComponentRef2 = typed.getServerComponentRef();
    if (_f_ServerComponentRef1 != null) {
      if (_f_ServerComponentRef2 == null) return false;
      if (_f_ServerComponentRef1.length != _f_ServerComponentRef2.length) return false;
      for (int i1 = 0; i1 < _f_ServerComponentRef1.length ; i1++) {
        if (_f_ServerComponentRef1[i1] != null) {
          if (_f_ServerComponentRef2[i1] == null) return false;
          if (!_f_ServerComponentRef1[i1].equals(_f_ServerComponentRef2[i1])) return false;
        } else {
          if (_f_ServerComponentRef2[i1] != null) return false;
        }
      }
    } else {
      if (_f_ServerComponentRef2 != null) return false;
    }
    if (this._f_RunAsIdentityMap != null) {
      if (typed._f_RunAsIdentityMap == null) return false;
      if (!this._f_RunAsIdentityMap.equals(typed._f_RunAsIdentityMap)) return false;
    } else {
      if (typed._f_RunAsIdentityMap != null) return false;
    }
    com.sap.engine.lib.descriptors.ejbj2eeengine.IorSecurityConfigType[] _f_IorSecurityConfig1 = this.getIorSecurityConfig();
    com.sap.engine.lib.descriptors.ejbj2eeengine.IorSecurityConfigType[] _f_IorSecurityConfig2 = typed.getIorSecurityConfig();
    if (_f_IorSecurityConfig1 != null) {
      if (_f_IorSecurityConfig2 == null) return false;
      if (_f_IorSecurityConfig1.length != _f_IorSecurityConfig2.length) return false;
      for (int i1 = 0; i1 < _f_IorSecurityConfig1.length ; i1++) {
        if (_f_IorSecurityConfig1[i1] != null) {
          if (_f_IorSecurityConfig2[i1] == null) return false;
          if (!_f_IorSecurityConfig1[i1].equals(_f_IorSecurityConfig2[i1])) return false;
        } else {
          if (_f_IorSecurityConfig2[i1] != null) return false;
        }
      }
    } else {
      if (_f_IorSecurityConfig2 != null) return false;
    }
    if (this._f_ChoiceGroup1 != null) {
      if (typed._f_ChoiceGroup1 == null) return false;
      if (!this._f_ChoiceGroup1.equals(typed._f_ChoiceGroup1)) return false;
    } else {
      if (typed._f_ChoiceGroup1 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_EjbName != null) {
      result+= this._f_EjbName.hashCode();
    }
    if (this._f_JndiName != null) {
      result+= this._f_JndiName.hashCode();
    }
    if (this._f_ContainerSize != null) {
      result+= this._f_ContainerSize.hashCode();
    }
    com.sap.engine.lib.descriptors.ejbj2eeengine.EjbRefType[] _f_EjbRef1 = this.getEjbRef();
    if (_f_EjbRef1 != null) {
      for (int i1 = 0; i1 < _f_EjbRef1.length ; i1++) {
        if (_f_EjbRef1[i1] != null) {
          result+= _f_EjbRef1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors.ejbj2eeengine.EjbLocalRefType[] _f_EjbLocalRef1 = this.getEjbLocalRef();
    if (_f_EjbLocalRef1 != null) {
      for (int i1 = 0; i1 < _f_EjbLocalRef1.length ; i1++) {
        if (_f_EjbLocalRef1[i1] != null) {
          result+= _f_EjbLocalRef1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceRefType[] _f_ResourceRef1 = this.getResourceRef();
    if (_f_ResourceRef1 != null) {
      for (int i1 = 0; i1 < _f_ResourceRef1.length ; i1++) {
        if (_f_ResourceRef1[i1] != null) {
          result+= _f_ResourceRef1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors.ejbj2eeengine.ResourceEnvRefType[] _f_ResourceEnvRef1 = this.getResourceEnvRef();
    if (_f_ResourceEnvRef1 != null) {
      for (int i1 = 0; i1 < _f_ResourceEnvRef1.length ; i1++) {
        if (_f_ResourceEnvRef1[i1] != null) {
          result+= _f_ResourceEnvRef1[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors.ejbj2eeengine.ServerComponentRefType[] _f_ServerComponentRef1 = this.getServerComponentRef();
    if (_f_ServerComponentRef1 != null) {
      for (int i1 = 0; i1 < _f_ServerComponentRef1.length ; i1++) {
        if (_f_ServerComponentRef1[i1] != null) {
          result+= _f_ServerComponentRef1[i1].hashCode();
        }
      }
    }
    if (this._f_RunAsIdentityMap != null) {
      result+= this._f_RunAsIdentityMap.hashCode();
    }
    com.sap.engine.lib.descriptors.ejbj2eeengine.IorSecurityConfigType[] _f_IorSecurityConfig1 = this.getIorSecurityConfig();
    if (_f_IorSecurityConfig1 != null) {
      for (int i1 = 0; i1 < _f_IorSecurityConfig1.length ; i1++) {
        if (_f_IorSecurityConfig1[i1] != null) {
          result+= _f_IorSecurityConfig1[i1].hashCode();
        }
      }
    }
    if (this._f_ChoiceGroup1 != null) {
      result+= this._f_ChoiceGroup1.hashCode();
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
