/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 31 10:03:54 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ejbj2eeengine;

/**
 * Schema complexType Java representation.
 * Represents type {}isolation-levelType
 */
public  class IsolationLevelType implements java.io.Serializable,java.lang.Cloneable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Model group field class 
  public static class Choice1 implements java.io.Serializable,java.lang.Cloneable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

    public Choice1() {
    }


    // // Active choise field
    private int _c_validField = 0;
    private com.sap.engine.lib.descriptors.ejbj2eeengine.MethodType _f_Method;
    /**
     * Set method for element {}method
     */
    public void setMethod(com.sap.engine.lib.descriptors.ejbj2eeengine.MethodType _Method) {
      if (this._c_validField != 0 && this._c_validField != 1) {
        this.unsetContent();
      }
      this._f_Method = _Method;
      this._c_validField = 1;
    }
    /**
     * Get method for element {}method
     */
    public com.sap.engine.lib.descriptors.ejbj2eeengine.MethodType getMethod() {
      if (this._c_validField != 1) {
        return null;
      }
      return this._f_Method;
    }
    /**
     * Check method for element {}method
     */
    public boolean isSetMethod() {
      return (this._c_validField ==1);
    }
    private java.lang.String _f_EjbName;
    /**
     * Set method for element {}ejb-name
     */
    public void setEjbName(java.lang.String _EjbName) {
      if (this._c_validField != 0 && this._c_validField != 2) {
        this.unsetContent();
      }
      this._f_EjbName = _EjbName;
      this._c_validField = 2;
    }
    /**
     * Get method for element {}ejb-name
     */
    public java.lang.String getEjbName() {
      if (this._c_validField != 2) {
        return null;
      }
      return this._f_EjbName;
    }
    /**
     * Check method for element {}ejb-name
     */
    public boolean isSetEjbName() {
      return (this._c_validField ==2);
    }
    /**
     * Common get method for choice type.
     */
    public java.lang.Object getContent() {
      switch (this._c_validField) {
        case 1: return this._f_Method;
        case 2: return this._f_EjbName;
      }
      return null;
    }
    /**
     * Returns true if this choice has content set.
     */
    public boolean isSetContent() {
      return (this._c_validField == 0);
    }
    /**
     * Clears choice content.
     */
    public void unsetContent() {
      switch (this._c_validField) {
        case  1: {
          this._f_Method = null;
          break;
        }
        case  2: {
          this._f_EjbName = null;
          break;
        }
      }
      this._c_validField = 0;
    }

    /**
     * Equals method implementation.
     */
    public boolean equals(Object object) {
      if (object == null) return false;
      if (!(object instanceof Choice1)) return false;
      Choice1 typed = (Choice1) object;
      if (this._c_validField != typed._c_validField) return false;
      switch (this._c_validField) {
        case 1: {
          if (this._f_Method != null) {
            if (typed._f_Method == null) return false;
            if (!this._f_Method.equals(typed._f_Method)) return false;
          } else {
            if (typed._f_Method != null) return false;
          }
          break;
        }
        case 2: {
          if (this._f_EjbName != null) {
            if (typed._f_EjbName == null) return false;
            if (!this._f_EjbName.equals(typed._f_EjbName)) return false;
          } else {
            if (typed._f_EjbName != null) return false;
          }
          break;
        }
      }
      return true;
    }

    /**
     * Hashcode method implementation.
     */
    public int hashCode() {
      int result = 0;
      switch (this._c_validField) {
        case 1: {
          if (this._f_Method != null) {
            result+= this._f_Method.hashCode();
          }
          result = result * this._c_validField;
          break;
        }
        case 2: {
          if (this._f_EjbName != null) {
            result+= this._f_EjbName.hashCode();
          }
          result = result * this._c_validField;
          break;
        }
      }
      return result;
    }

    public java.lang.String get__ID() {
      return java.lang.String.valueOf(super.hashCode());
    }
  }

  private java.util.ArrayList _f_ChoiceGroup1 = new java.util.ArrayList();
  public void setChoiceGroup1(Choice1[] _ChoiceGroup1) {
    this._f_ChoiceGroup1.clear();
    if (_ChoiceGroup1 != null) {
      for (int i=0; i<_ChoiceGroup1.length; i++) {
        if (_ChoiceGroup1[i] != null)
          this._f_ChoiceGroup1.add(_ChoiceGroup1[i]);
      }
    }
  }
  public Choice1[] getChoiceGroup1() {
    Choice1[] result = new Choice1[_f_ChoiceGroup1.size()];
    _f_ChoiceGroup1.toArray(result);
    return result;
  }

  // Element field for element {}isolation-attribute
  private java.lang.String _f_IsolationAttribute;
  /**
   * Set method for element {}isolation-attribute
   */
  public void setIsolationAttribute(java.lang.String _IsolationAttribute) {
    this._f_IsolationAttribute = _IsolationAttribute;
  }
  /**
   * Get method for element {}isolation-attribute
   */
  public java.lang.String getIsolationAttribute() {
    return this._f_IsolationAttribute;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof IsolationLevelType)) return false;
    IsolationLevelType typed = (IsolationLevelType) object;
    Choice1[] _f_ChoiceGroup11 = this.getChoiceGroup1();
    Choice1[] _f_ChoiceGroup12 = typed.getChoiceGroup1();
    if (_f_ChoiceGroup11 != null) {
      if (_f_ChoiceGroup12 == null) return false;
      if (_f_ChoiceGroup11.length != _f_ChoiceGroup12.length) return false;
      for (int i1 = 0; i1 < _f_ChoiceGroup11.length ; i1++) {
        if (_f_ChoiceGroup11[i1] != null) {
          if (_f_ChoiceGroup12[i1] == null) return false;
          if (!_f_ChoiceGroup11[i1].equals(_f_ChoiceGroup12[i1])) return false;
        } else {
          if (_f_ChoiceGroup12[i1] != null) return false;
        }
      }
    } else {
      if (_f_ChoiceGroup12 != null) return false;
    }
    if (this._f_IsolationAttribute != null) {
      if (typed._f_IsolationAttribute == null) return false;
      if (!this._f_IsolationAttribute.equals(typed._f_IsolationAttribute)) return false;
    } else {
      if (typed._f_IsolationAttribute != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    Choice1[] _f_ChoiceGroup11 = this.getChoiceGroup1();
    if (_f_ChoiceGroup11 != null) {
      for (int i1 = 0; i1 < _f_ChoiceGroup11.length ; i1++) {
        if (_f_ChoiceGroup11[i1] != null) {
          result+= _f_ChoiceGroup11[i1].hashCode();
        }
      }
    }
    if (this._f_IsolationAttribute != null) {
      result+= this._f_IsolationAttribute.hashCode();
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
