/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 31 10:03:54 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ejbj2eeengine;

/**
 * Schema complexType Java representation.
 * Represents type of namespace {} anonymous with xpath [/xs:schema/xs:element[18]/xs:complexType]
 */
public  class KeepsOpenResources implements java.io.Serializable,java.lang.Cloneable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof KeepsOpenResources)) return false;
    KeepsOpenResources typed = (KeepsOpenResources) object;
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
