/*
 * Generated by SAP SchemaToJava Generator NW05 on Wed Apr 26 17:41:35 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ejbj2eeengine;

/**
 * Schema complexType Java representation.
 * Represents type {}message-destination-mapsType
 */
public  class MessageDestinationMapsType implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Element field for element {}message-destination
  private java.util.ArrayList _f_MessageDestination = new java.util.ArrayList();
  /**
   * Set method for element {}message-destination
   */
  public void setMessageDestination(com.sap.engine.lib.descriptors.ejbj2eeengine.MessageDestinationType[] _MessageDestination) {
    this._f_MessageDestination.clear();
    if (_MessageDestination != null) {
      for (int i=0; i<_MessageDestination.length; i++) {
        if (_MessageDestination[i] != null)
          this._f_MessageDestination.add(_MessageDestination[i]);
      }
    }
  }
  /**
   * Get method for element {}message-destination
   */
  public com.sap.engine.lib.descriptors.ejbj2eeengine.MessageDestinationType[] getMessageDestination() {
    com.sap.engine.lib.descriptors.ejbj2eeengine.MessageDestinationType[] result = new com.sap.engine.lib.descriptors.ejbj2eeengine.MessageDestinationType[_f_MessageDestination.size()];
    _f_MessageDestination.toArray(result);
    return result;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof MessageDestinationMapsType)) return false;
    MessageDestinationMapsType typed = (MessageDestinationMapsType) object;
    com.sap.engine.lib.descriptors.ejbj2eeengine.MessageDestinationType[] _f_MessageDestination1 = this.getMessageDestination();
    com.sap.engine.lib.descriptors.ejbj2eeengine.MessageDestinationType[] _f_MessageDestination2 = typed.getMessageDestination();
    if (_f_MessageDestination1 != null) {
      if (_f_MessageDestination2 == null) return false;
      if (_f_MessageDestination1.length != _f_MessageDestination2.length) return false;
      for (int i1 = 0; i1 < _f_MessageDestination1.length ; i1++) {
        if (_f_MessageDestination1[i1] != null) {
          if (_f_MessageDestination2[i1] == null) return false;
          if (!_f_MessageDestination1[i1].equals(_f_MessageDestination2[i1])) return false;
        } else {
          if (_f_MessageDestination2[i1] != null) return false;
        }
      }
    } else {
      if (_f_MessageDestination2 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    com.sap.engine.lib.descriptors.ejbj2eeengine.MessageDestinationType[] _f_MessageDestination1 = this.getMessageDestination();
    if (_f_MessageDestination1 != null) {
      for (int i1 = 0; i1 < _f_MessageDestination1.length ; i1++) {
        if (_f_MessageDestination1[i1] != null) {
          result+= _f_MessageDestination1[i1].hashCode();
        }
      }
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
