/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon Jan 30 18:27:10 EET 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.connectorj2eeengine;

/**
 * Schema complexType Java representation.
 * Represents type {}expiration-controlType
 */
public  class ExpirationControlType implements java.io.Serializable,java.lang.Cloneable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Element field for element {}connection-lifetime
  private java.math.BigInteger _f_ConnectionLifetime;
  /**
   * Set method for element {}connection-lifetime
   */
  public void setConnectionLifetime(java.math.BigInteger _ConnectionLifetime) {
    this._f_ConnectionLifetime = _ConnectionLifetime;
  }
  /**
   * Get method for element {}connection-lifetime
   */
  public java.math.BigInteger getConnectionLifetime() {
    return this._f_ConnectionLifetime;
  }

  // Element field for element {}run-cleanup-thread-interval
  private java.math.BigInteger _f_RunCleanupThreadInterval;
  /**
   * Set method for element {}run-cleanup-thread-interval
   */
  public void setRunCleanupThreadInterval(java.math.BigInteger _RunCleanupThreadInterval) {
    this._f_RunCleanupThreadInterval = _RunCleanupThreadInterval;
  }
  /**
   * Get method for element {}run-cleanup-thread-interval
   */
  public java.math.BigInteger getRunCleanupThreadInterval() {
    return this._f_RunCleanupThreadInterval;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof ExpirationControlType)) return false;
    ExpirationControlType typed = (ExpirationControlType) object;
    if (this._f_ConnectionLifetime != null) {
      if (typed._f_ConnectionLifetime == null) return false;
      if (!this._f_ConnectionLifetime.equals(typed._f_ConnectionLifetime)) return false;
    } else {
      if (typed._f_ConnectionLifetime != null) return false;
    }
    if (this._f_RunCleanupThreadInterval != null) {
      if (typed._f_RunCleanupThreadInterval == null) return false;
      if (!this._f_RunCleanupThreadInterval.equals(typed._f_RunCleanupThreadInterval)) return false;
    } else {
      if (typed._f_RunCleanupThreadInterval != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_ConnectionLifetime != null) {
      result+= this._f_ConnectionLifetime.hashCode();
    }
    if (this._f_RunCleanupThreadInterval != null) {
      result+= this._f_RunCleanupThreadInterval.hashCode();
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
