/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon Jan 30 18:27:10 EET 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.connectorj2eeengine;

/**
 * Schema complexType Java representation.
 * Represents type {}resource-principalType
 */
public  class ResourcePrincipalType implements java.io.Serializable,java.lang.Cloneable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Element field for element {}user-name
  private java.lang.String _f_UserName;
  /**
   * Set method for element {}user-name
   */
  public void setUserName(java.lang.String _UserName) {
    this._f_UserName = _UserName;
  }
  /**
   * Get method for element {}user-name
   */
  public java.lang.String getUserName() {
    return this._f_UserName;
  }

  // Element field for element {}user-password
  private java.lang.String _f_UserPassword;
  /**
   * Set method for element {}user-password
   */
  public void setUserPassword(java.lang.String _UserPassword) {
    this._f_UserPassword = _UserPassword;
  }
  /**
   * Get method for element {}user-password
   */
  public java.lang.String getUserPassword() {
    return this._f_UserPassword;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof ResourcePrincipalType)) return false;
    ResourcePrincipalType typed = (ResourcePrincipalType) object;
    if (this._f_UserName != null) {
      if (typed._f_UserName == null) return false;
      if (!this._f_UserName.equals(typed._f_UserName)) return false;
    } else {
      if (typed._f_UserName != null) return false;
    }
    if (this._f_UserPassword != null) {
      if (typed._f_UserPassword == null) return false;
      if (!this._f_UserPassword.equals(typed._f_UserPassword)) return false;
    } else {
      if (typed._f_UserPassword != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_UserName != null) {
      result+= this._f_UserName.hashCode();
    }
    if (this._f_UserPassword != null) {
      result+= this._f_UserPassword.hashCode();
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
