export const phoneBookConstants = {
    QUEUE_NAME: 'Queue Name',
    CALL_REASON: 'Call Reason',
    QUEUE_FIELD: 'QueueName',
    REASON_FIELD: 'CallReason',
    SELECT: 'Select',
    MEMBER: 'Member',
    GROUP: 'Group',
    AGENT: 'Agent',
    PROVIDER: 'Provider',
    BROKER: 'Broker',
    EMPLOYER: 'Employer',
    AGENCY: 'Agency',
    UNKNOWN: 'Unknown',
    TRANSFER_PHONE_BOOK: 'Transfer Phone Book',
    ISMANUAL_N: 'N',
    ISMANUAL_Y: 'Y',
    MEMBER_M: 'M',
    PROVIDER_P: 'P',
    GROUP_G: 'G',
    EMPLOYER_E: 'E',
    AGENT_A: 'A',
    BROKER_B: 'B',
    UNKNOWN_U: 'U',
    CATEGORY_CD: 'CategoryCd',
    WARM: 'WARM',
    CONSULT: 'consultTransfer',
    COLD: 'COLD',
    BLIND: 'blindTransfer',
    CONTACT_ASSISTANCE: 'contact the help desk for assistance',
    INQR_TYP: 'INQR_TYP',
    INQR_ID: 'INQR_ID',
    INQR_FIRST: 'INQR_FIRST',
    INQR_LAST: 'INQR_LAST',
    INQR_DOB: 'INQR_DOB',
    INQA_TYP: 'INQA_TYP',
    INQA_ID: 'INQA_ID',
    INQA_FIRST: 'INQA_FIRST',
    INQA_LAST: 'INQA_LAST',
    INQA_DOB: 'INQA_DOB',
    INQA_GRP_ID : 'INQA_GRP_ID',
    TRANSFER_TYPE: 'TRANSFER_TYPE',
    TRANSFER_ETIM: 'TRANSFER_ETIM',
    CRM_STRIDE: 'CRM Strides || ',
    AWC_COMPLETED: 'ACW Completed',
    ROUTING_STATUS: 'Routing Status_',
    CALL_DISCONNECTED: 'Call Disconnected',
    INTERACTION_CONNECTED: 'Interaction: connected',
    INTERACTION_SECURE_TRANSFER: 'Interaction : Secure Transfer',
    STATION: 'Station',
    STATUS_CHANGED: 'Status changed to ',
    OUTBOUND: 'Outbound',
    INBOUND: 'Inbound',
    LOGGED_IN: 'User logged in',
    LOGGED_OUT: 'User logged out',
    SUCCESS_CREDITCARD: 'The credit card has been added successfully',
    SF_StatusPayment: 'Participant.SF_StatusPayment',
    SF_FailureReason: 'Participant.SF_FailureReason',
    SF_TimeStamp: 'Participant.SF_TimeStamp',
    Participant_uuiData: 'Participant.uuiData',
    UUIDATA: 'uuiData',
    ISMANUAL_TRANSFER: 'ISMANUAL_TRANSFER',
    NUMBER_OF_TRANSFERS: 'NUMBER_OF_TRANSFERS',
    MEMBER_S: 'S',
    PROVIDER_PPI: 'PPI',
    Participant_CampaignName:'participant.campaign name',
    Participant_Keycode:'participant.keycode',
    updateCampaignNameAndKeycodeSwitch: 'Switch_3980680',
    MemberDOBFormatSwitch: 'Switch_4144165',
    UniversalTimezone:'T00:00:00.000',
    InvalidDateCheck:'Invalid Date',
    Switch_List: ['5602717'],
    INQR_NPI: 'INQR_NPI'
}