/**
   @Author      : Pradeepkumar Dani
   @name        : Alerts_T_HUM
   @CreateDate  : 02/09/2016
   @Description : This class serves as abstarct controller.
   @Version     : 1.0 
   @reference   : Alerts_C_HUM
   
Modification Log: 
 * Developer Name           Code Review                 Date                         Description
 *------------------------------------------------------------------------------------------------------------------------------
 * Pradeepkumar Dani                                  02/09/2016                    Original version
 * Chaitanya Kumar									  								03/05/2017										Added SaveOffers Test methods
 * Chaitanya Vegendla					82921										04/07/2017										Added code for End session code test Coverage
********************************************************************************************************************************/
Public with sharing class Alerts_T_HUM 
{
	 
}