/********************************************************************************************************************************************************
Apex Class Name  : CaseManagement_Constants_HUM
Version          : 1.0 
Created Date     : MAY 27 2021
Test Class       : CaseManagement_Constants_HUM
Function         : Constants declaration here that are going to be used across the org.
Modification Log :       
* Developer                       Code review              Date                 Description
* -------------------------------------------------------------------------------------------------------------------------------------------------------               
 * Pooja Kumbhar                                          06/07/2021            User Story 2270747: T1PRJ0002606/PR00094268 - MF1 - Architectural Remediation - Case Management Global Constant Class Changes - Case History 
 * Pooja Kumbhar                                          02/02/2022            User Story 2270747: T1PRJ0272555 - MF1 - Architectural Remediation - Global Constant -DF-4182 - Additional Changes Global Comstamt Changes
*******************/

Public class CaseManagement_Constants_HUM
{
    Public Static final String GROUP_RECORDTYPE_HUM = 'GROUP'; 
    Public Static final String MEMBER_RECORDTYPE_HUM = 'Member'; 
    Public Static final String CLOSEDCASE_AGENTBROKER_HUM = 'Agent/Broker'; 
    Public Static final Integer NUMBER_CONSTANT_SEVENTHOUSAND_HUM = 7000;
    Public Static final String CASESERVICE_ACCOUNTGROUPTYPEID = 'GroupID';
    Public Static final String HumHPRecType = 'HP';
    Public Static final String MRDOCID = '1';
    Public Static final String HYPHEN_HUM = '-';
    Public Static final String TRACKSERVICE_TRACKINFO_OTRACKID_Y_HUM = 'Y';
    Public Static final String TRACKSERVICE_TRACKINFO_OTRACKID_N_HUM = 'N';
    Public Static final String Sort_Expression_DESC_HUM = 'DESC';
    Public Static final String SORTDATE_HUM ='CreatedDate';
    Public Static final String CASE_CONSTANT_HUM = 'Case';
    Public Static final String ID_HUM = 'id';
    Public Static final String HUMObjectType = 'objectType';
    Public Static final String HUMobjectNumber = 'objectNumber';
    Public Static final String HUMActionType = 'Error';
    Public Static final String HUMQueueYesForEdit = 'YesForEdit';
    Public Static final String OBJECT_CASE = 'Case';
    Public Static final String OBJECT_TASK = 'Task';
    Public Static final String HUMNextPage = 'nextPage';
    Public Static final String HUMRecordType = 'RecordType';
    Public Static final String HUMWebChatText = 'Web Chat';
    Public Static final String HUMQueueYesFromAccountRelatedList = 'YesFromAccountRelatedList';
    Public Static final String HUMcaseRecordType = 'caseRecordType';
    Public Static final String HUMAccRecordTypeName = 'Account RecordType';
    Public Static final String HUMQueueYesFromCaseHistory = 'YesFromCaseHistory';
    Public Static final String HUMApexinURL = '/apex/';
    Public Static final String HUMObjectId = 'objectId';
    Public Static final String HUMId = 'Id';
    Public Static final String CASE_CLASSIFICATION_TYPE_MEDICAID_CALLS = 'Medicaid Calls';
}