/**************************************************************************** 
Apex Class Name  : DCNServiceResponseHelperHumI 
Version          : 1.0  
Created Date     : Sepetember 21, 2015
Function         : Response Helper class for DCN Service
Test Class       : DCNServiceResponseHelperTestHumI
****************************************************************************
Modification Log:
* Developer Name          Code Review #         Date                       Description
*------------------------------------------------------------------------------------------------------------
* Gargey Sharma		         26705           09/21/2015                    Original Version
***************************************************************************************************/
public with sharing class DCNServiceResponseHelperHumI 
{
	public string Success = '';
	public string ErrorMsg = '';
	public list<string> DCNList;
}