/**************************************************************************** 
Apex Class Name  : DocumentURL_DTO_HUM
Version          : 1.0
Created Date     : 09/02/2022
Function         : 
Test Class       : DocumentURL_DTO_HUM
***********************************************************************************
Modification Log:
* Developer Name          Code Review #         Date                       Description
*--------------------------------------------------------------------------------------------------
* Kalyani Pachpol                              09/02/2022                   original Version
***************************************************************************************************/

public with sharing class DocumentURL_DTO_HUM {
    public string sMedhokUrl{get; set;}
    public string sMethod{get; set;}
    public string sAppKey{get; set;}
}