/************************************************************************************************************
Apex Class Name  : HUMMemWebActDetailsServiceResponseHelper
Version          : 1.0  
Created Date     : July 22, 2015
Function         : This class is used to hold Member Activity Details Service Response
Test Class       : HUMMemWebActDetailsSerResponseHelperTest
*************************************************************************************************************
Modification Log:
* Developer Name           Code Review #        Date            Description
*------------------------------------------------------------------------------------------------------------
* Adil Mohammed               24997            07/22/2015      Original Version  
************************************************************************************************************/
public with sharing class HUMMemWebActDetailsServiceResponseHelper
{
    public string sVitalityEntityID = '2511000602';
    public string sMemberVitalityIndicator = '';
    public string sMemberGenKey = '';    
    public string sLastLoginDateTime= '';
    public string sIsWebRegistered= '';
    public string sErrorMemberWebActivity='';
    public string sError='';
}