/***************************************************************************************************************************************************************************
Apex Class Name  : HUMUpdateCaseServiceResponseHelper
Version          : 1.0
Created Date     : December 22 2014
Function         : This class is used as response for update case  HUMCaseService.
Test Class       : HUMUpdateCaseServiceResponseHelperTest
 ****************************************************************************************************************************************************************************

Modification Log:

 * Developer Name        Code Review                Date                        Description
 *---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Vishal Verma           20294                    12/22/2014                   Original Version
 ****************************************************************************************************************************************************************************/

global with sharing class HUMUpdateCaseServiceResponseHelper 
{
    webservice HUMStatusMessageHelper updateServiceResponse = null;
}