public class ImagingService_LDTO_HUM {

    @AuraEnabled public String sDCN {get; set;} 
    @AuraEnabled public String sECN {get; set;} 
    @AuraEnabled public String Receipt_Date {get; set;} 
    @AuraEnabled public String bRepriced {get; set;} 
    @AuraEnabled public String dTotal_Billed_Charges {get; set;} 
    @AuraEnabled public String sBilling_Provider_Last_Facility_Name {get; set;} 
    @AuraEnabled public String sBilling_provider_id {get; set;} 
    @AuraEnabled public String sRendering_Provider_Last_Facility_Name {get; set;} 
    @AuraEnabled public String sRendering_Provider_Id {get; set;} 
    @AuraEnabled public String sClaim_Frequency_Code {get; set;} 
    @AuraEnabled public String sClaimURL {get; set;} 
    @AuraEnabled public String sECNOrDCN {get; set;}
}