/***********************************************************************************************************************************
Apex Class Name  : MemberPreferencesLink_H_HUM 
Version          : 
Created Date     : 03/05/2018   
Function         : Request helper for Encrypt method in EncrytRest Service
Test Class       : MemberPreferencesLink_T_HUM
****************************************************************************
Modification Log:
* Developer Name               Code Review #         Date                       Description
*---------------------------------------------------------------------------------------------------------------------------------
 *  Shivam Anand                                      03/05/2018           REQ349581- Add Member Preferences Link to CRM Service Person Account Page
 *  Vijaya Koriprolu                                  03/06/2018           REQ - 349580- Add Member Preferences Link on CRM Policy Member Page
 *  Satyam Malviya							          5/21/2020			   DF 766 Corrected Application key that have been passes to MemberPreference Link Fix
**********************************************************************************************************************************/

public class MemberPreferencesLink_H_HUM 
{
public Encrypt Encrypt;

   /*
     * Value : member gen key
    */       
    
  public Class Encrypt
  {
    public String Value ='';
	public String Application = '';
  }


}