public with sharing class MemberVitalityDataHelper 
{
        public String MemberEntityNumber;   //2503765337
        public String VitalityAge;  //45
        public VitalityBucksBalancesHelper VitalityBucksBalances;
        public VitalityStatusesHelper VitalityStatuses;
        public String IsHraCompleted;   //false
        public MemberGoalsHelper MemberGoals= new MemberGoalsHelper();          
 }