/*******************************************************************************************************************************
Apex Class Name : PharmacyOMSLogNotes_DTO_HUM.cls
Version         : 1.0
Created On      : 2016
Function        : DTO Class for OMS Log Notes.

Modification Log:
* Developer Name            Code Review                Date                       Description
*------------------------------------------------------------------------------------------------------------------------------
* Shiva Pasumarty           60234                      01/12/2017                  Original Version
*********************************************************************************************************************************/

public with sharing class PharmacyOMSLogNotes_DTO_HUM{
        public String LogNoteCode = '';
        public String LogNoteDate = ''; 
        public String LogNoteKey = '';  
        public String LogNoteMessage = '';  
        public String LogNoteUser = ''; 
}