export const providerDisputesListLayout = [
    {
        label : "",
        isExpand: true,
        ExpandIcon : '',
        CollapseIcon : '',
        style : 'width:5%;'
    },{
        label : "Case Number",
        value : '',
        mappingField : 'sCase',
        style : 'width:15%;cursor: pointer;',
        sorting : true,
        desc : false,
        asc : true,
        iconname : 'utility:arrowup',
        mousehover : false,
        mousehovericon : '',
        id : 'sCase',
    },{
        label : "Type",
        value : '',
        mappingField : 'sType',
        style : 'width:15%;cursor: pointer;',
        sorting : false,
        desc : false,
        asc : true,
        iconname : 'utility:arrowup',
        mousehover : false,
        mousehovericon : '',
        id : 'sType',
    },{
        label : "Category",
        value : '',
        mappingField : 'sCategory',
        style : 'width:15%;cursor: pointer;',
        sorting : false,
        desc : false,
        asc : true,
        iconname : 'utility:arrowup',
        mousehover : false,
        mousehovericon : '',
        id : 'sCategory',
    },{
        label : "Status",
        value : '',
        mappingField : 'sStatus',
        style : 'width:20%;cursor: pointer;',
        sorting : false,
        desc : false,
        asc : true,
        iconname : 'utility:arrowup',
        mousehover : false,
        mousehovericon : '',
        id : 'sStatus',
    },{
        label : "Priority",
        value : '',
        mappingField : 'sPriority',
        style : 'width:10%;cursor: pointer;',
        sorting : false,
        desc : false,
        asc : true,
        iconname : 'utility:arrowup',
        mousehover : false,
        mousehovericon : '',
        id : 'sPriority',
    },{
        label : "Due Date",
        value : '',
        mappingField : 'sDueDate',
        style : 'width:10%;cursor: pointer;',
        sorting : false,
        desc : false,
        asc : true,
        iconname : 'utility:arrowup',
        mousehover : false,
        mousehovericon : '',
        id : 'sDueDate',
    },{
        label : "Provider Name",
        value : '',
        mappingField : 'sProviderName',
        style : 'width:20%;cursor: pointer;',
        sorting : false,
        desc : false,
        asc : true,
        iconname : 'utility:arrowup',
        mousehover : false,
        mousehovericon : '',
        id : 'sProviderName',
    },
]

export  function getModal() {    
    return providerDisputesListLayout;    
}