/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon Jun 26 13:55:46 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors5.webservices;

/**
 * Schema complexType Java representation.
 * Represents type {http://java.sun.com/xml/ns/javaee}port-component-refType
 */
public  class PortComponentRefType implements java.io.Serializable {

  // Attribute field for attribute {}id
  private java.lang.String _a_Id;
  /**
   * Set method for attribute {}id
   */
  public void setId(java.lang.String _Id) {
    this._a_Id = _Id;
  }
  /**
   * Get method for attribute {}id
   */
  public java.lang.String getId() {
    return _a_Id;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}service-endpoint-interface
  private com.sap.engine.lib.descriptors5.webservices.FullyQualifiedClassType _f_ServiceEndpointInterface;
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}service-endpoint-interface
   */
  public void setServiceEndpointInterface(com.sap.engine.lib.descriptors5.webservices.FullyQualifiedClassType _ServiceEndpointInterface) {
    this._f_ServiceEndpointInterface = _ServiceEndpointInterface;
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}service-endpoint-interface
   */
  public com.sap.engine.lib.descriptors5.webservices.FullyQualifiedClassType getServiceEndpointInterface() {
    return this._f_ServiceEndpointInterface;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}enable-mtom
  private com.sap.engine.lib.descriptors5.webservices.TrueFalseType _f_EnableMtom;
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}enable-mtom
   */
  public void setEnableMtom(com.sap.engine.lib.descriptors5.webservices.TrueFalseType _EnableMtom) {
    this._f_EnableMtom = _EnableMtom;
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}enable-mtom
   */
  public com.sap.engine.lib.descriptors5.webservices.TrueFalseType getEnableMtom() {
    return this._f_EnableMtom;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}port-component-link
  private com.sap.engine.lib.descriptors5.webservices.String _f_PortComponentLink;
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}port-component-link
   */
  public void setPortComponentLink(com.sap.engine.lib.descriptors5.webservices.String _PortComponentLink) {
    this._f_PortComponentLink = _PortComponentLink;
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}port-component-link
   */
  public com.sap.engine.lib.descriptors5.webservices.String getPortComponentLink() {
    return this._f_PortComponentLink;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof PortComponentRefType)) return false;
    PortComponentRefType typed = (PortComponentRefType) object;
    if (this._a_Id != null) {
      if (typed._a_Id == null) return false;
      if (!this._a_Id.equals(typed._a_Id)) return false;
    } else {
      if (typed._a_Id != null) return false;
    }
    if (this._f_ServiceEndpointInterface != null) {
      if (typed._f_ServiceEndpointInterface == null) return false;
      if (!this._f_ServiceEndpointInterface.equals(typed._f_ServiceEndpointInterface)) return false;
    } else {
      if (typed._f_ServiceEndpointInterface != null) return false;
    }
    if (this._f_EnableMtom != null) {
      if (typed._f_EnableMtom == null) return false;
      if (!this._f_EnableMtom.equals(typed._f_EnableMtom)) return false;
    } else {
      if (typed._f_EnableMtom != null) return false;
    }
    if (this._f_PortComponentLink != null) {
      if (typed._f_PortComponentLink == null) return false;
      if (!this._f_PortComponentLink.equals(typed._f_PortComponentLink)) return false;
    } else {
      if (typed._f_PortComponentLink != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_Id != null) {
      result+= this._a_Id.hashCode();
    }
    if (this._f_ServiceEndpointInterface != null) {
      result+= this._f_ServiceEndpointInterface.hashCode();
    }
    if (this._f_EnableMtom != null) {
      result+= this._f_EnableMtom.hashCode();
    }
    if (this._f_PortComponentLink != null) {
      result+= this._f_PortComponentLink.hashCode();
    }
    return result;
  }
}
