/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu May 05 11:42:02 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ws04vi.frm;

/**
 * Schema complexType Java representation.
 * Represents type {http://xml.sap.com/2002/10/metamodel/vi}VirtualInterfaceState
 */
public  class VirtualInterfaceStateSD extends com.sap.engine.lib.descriptors.ws04vi.frm.DevelopmentObjectStateSD {

  public java.lang.String _d_originalUri() {
    return "http://xml.sap.com/2002/10/metamodel/vi";
  }

  public java.lang.String _d_originalLocalName() {
    return "VirtualInterfaceState";
  }

  private static com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] ATTRIBUTEINFO;

  private synchronized static void initAttribs() {
    // Creating attribute fields
    if (ATTRIBUTEINFO != null) return;
    ATTRIBUTEINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[9];
    ATTRIBUTEINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    ATTRIBUTEINFO[1] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    ATTRIBUTEINFO[2] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    ATTRIBUTEINFO[3] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    ATTRIBUTEINFO[4] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    ATTRIBUTEINFO[5] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    ATTRIBUTEINFO[6] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    ATTRIBUTEINFO[7] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    ATTRIBUTEINFO[8] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    // Attribute 0
    ATTRIBUTEINFO[0].fieldLocalName = "name";
    ATTRIBUTEINFO[0].fieldUri = "";
    ATTRIBUTEINFO[0].fieldJavaName = "Name";
    ATTRIBUTEINFO[0].typeName = "string";
    ATTRIBUTEINFO[0].typeUri = "http://www.w3.org/2001/XMLSchema";
    ATTRIBUTEINFO[0].typeJavaName = "java.lang.String";
    ATTRIBUTEINFO[0].defaultValue = null;
    ATTRIBUTEINFO[0].required = true;
    ATTRIBUTEINFO[0].setterMethod = "setName";
    ATTRIBUTEINFO[0].getterMethod = "getName";
    ATTRIBUTEINFO[0].checkMethod = null;
    // Attribute 1
    ATTRIBUTEINFO[1].fieldLocalName = "changeable";
    ATTRIBUTEINFO[1].fieldUri = "";
    ATTRIBUTEINFO[1].fieldJavaName = "Changeable";
    ATTRIBUTEINFO[1].typeName = "boolean";
    ATTRIBUTEINFO[1].typeUri = "http://www.w3.org/2001/XMLSchema";
    ATTRIBUTEINFO[1].typeJavaName = "boolean";
    ATTRIBUTEINFO[1].defaultValue = "true";
    ATTRIBUTEINFO[1].required = false;
    ATTRIBUTEINFO[1].setterMethod = "setChangeable";
    ATTRIBUTEINFO[1].getterMethod = "isChangeable";
    ATTRIBUTEINFO[1].checkMethod = null;
    // Attribute 2
    ATTRIBUTEINFO[2].fieldLocalName = "mmVersion";
    ATTRIBUTEINFO[2].fieldUri = "";
    ATTRIBUTEINFO[2].fieldJavaName = "MmVersion";
    ATTRIBUTEINFO[2].typeName = "string";
    ATTRIBUTEINFO[2].typeUri = "http://www.w3.org/2001/XMLSchema";
    ATTRIBUTEINFO[2].typeJavaName = "java.lang.String";
    ATTRIBUTEINFO[2].defaultValue = null;
    ATTRIBUTEINFO[2].required = true;
    ATTRIBUTEINFO[2].setterMethod = "setMmVersion";
    ATTRIBUTEINFO[2].getterMethod = "getMmVersion";
    ATTRIBUTEINFO[2].checkMethod = null;
    // Attribute 3
    ATTRIBUTEINFO[3].fieldLocalName = "mmRelease";
    ATTRIBUTEINFO[3].fieldUri = "";
    ATTRIBUTEINFO[3].fieldJavaName = "MmRelease";
    ATTRIBUTEINFO[3].typeName = "string";
    ATTRIBUTEINFO[3].typeUri = "http://www.w3.org/2001/XMLSchema";
    ATTRIBUTEINFO[3].typeJavaName = "java.lang.String";
    ATTRIBUTEINFO[3].defaultValue = null;
    ATTRIBUTEINFO[3].required = true;
    ATTRIBUTEINFO[3].setterMethod = "setMmRelease";
    ATTRIBUTEINFO[3].getterMethod = "getMmRelease";
    ATTRIBUTEINFO[3].checkMethod = null;
    // Attribute 4
    ATTRIBUTEINFO[4].fieldLocalName = "interfaceType";
    ATTRIBUTEINFO[4].fieldUri = "";
    ATTRIBUTEINFO[4].fieldJavaName = "InterfaceType";
    ATTRIBUTEINFO[4].typeName = "InterfaceType";
    ATTRIBUTEINFO[4].typeUri = "http://xml.sap.com/2002/10/metamodel/vi";
    ATTRIBUTEINFO[4].typeJavaName = "com.sap.engine.lib.descriptors.ws04vi.InterfaceType";
    ATTRIBUTEINFO[4].defaultValue = "ejb";
    ATTRIBUTEINFO[4].required = false;
    ATTRIBUTEINFO[4].setterMethod = "setInterfaceType";
    ATTRIBUTEINFO[4].getterMethod = "getInterfaceType";
    ATTRIBUTEINFO[4].checkMethod = null;
    // Attribute 5
    ATTRIBUTEINFO[5].fieldLocalName = "package";
    ATTRIBUTEINFO[5].fieldUri = "";
    ATTRIBUTEINFO[5].fieldJavaName = "Package";
    ATTRIBUTEINFO[5].typeName = "string";
    ATTRIBUTEINFO[5].typeUri = "http://www.w3.org/2001/XMLSchema";
    ATTRIBUTEINFO[5].typeJavaName = "java.lang.String";
    ATTRIBUTEINFO[5].defaultValue = null;
    ATTRIBUTEINFO[5].required = true;
    ATTRIBUTEINFO[5].setterMethod = "setPackage";
    ATTRIBUTEINFO[5].getterMethod = "getPackage";
    ATTRIBUTEINFO[5].checkMethod = null;
    // Attribute 6
    ATTRIBUTEINFO[6].fieldLocalName = "masterLanguage";
    ATTRIBUTEINFO[6].fieldUri = "";
    ATTRIBUTEINFO[6].fieldJavaName = "MasterLanguage";
    ATTRIBUTEINFO[6].typeName = "string";
    ATTRIBUTEINFO[6].typeUri = "http://www.w3.org/2001/XMLSchema";
    ATTRIBUTEINFO[6].typeJavaName = "java.lang.String";
    ATTRIBUTEINFO[6].defaultValue = null;
    ATTRIBUTEINFO[6].required = true;
    ATTRIBUTEINFO[6].setterMethod = "setMasterLanguage";
    ATTRIBUTEINFO[6].getterMethod = "getMasterLanguage";
    ATTRIBUTEINFO[6].checkMethod = null;
    // Attribute 7
    ATTRIBUTEINFO[7].fieldLocalName = "guid";
    ATTRIBUTEINFO[7].fieldUri = "";
    ATTRIBUTEINFO[7].fieldJavaName = "Guid";
    ATTRIBUTEINFO[7].typeName = "string";
    ATTRIBUTEINFO[7].typeUri = "http://www.w3.org/2001/XMLSchema";
    ATTRIBUTEINFO[7].typeJavaName = "java.lang.String";
    ATTRIBUTEINFO[7].defaultValue = null;
    ATTRIBUTEINFO[7].required = false;
    ATTRIBUTEINFO[7].setterMethod = "setGuid";
    ATTRIBUTEINFO[7].getterMethod = "getGuid";
    ATTRIBUTEINFO[7].checkMethod = null;
    // Attribute 8
    ATTRIBUTEINFO[8].fieldLocalName = "mmTimestamp";
    ATTRIBUTEINFO[8].fieldUri = "";
    ATTRIBUTEINFO[8].fieldJavaName = "MmTimestamp";
    ATTRIBUTEINFO[8].typeName = "string";
    ATTRIBUTEINFO[8].typeUri = "http://www.w3.org/2001/XMLSchema";
    ATTRIBUTEINFO[8].typeJavaName = "java.lang.String";
    ATTRIBUTEINFO[8].defaultValue = null;
    ATTRIBUTEINFO[8].required = true;
    ATTRIBUTEINFO[8].setterMethod = "setMmTimestamp";
    ATTRIBUTEINFO[8].getterMethod = "getMmTimestamp";
    ATTRIBUTEINFO[8].checkMethod = null;
  }

  // Field information
  private static com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] FIELDINFO;

  private synchronized static void initFields() {
    // Creating fields
    if (FIELDINFO != null) return;
    FIELDINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[4];
    FIELDINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    FIELDINFO[1] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    FIELDINFO[2] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    FIELDINFO[3] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    // Field 0
    FIELDINFO[0].defaultValue = null;
    FIELDINFO[0].fieldJavaName = "VirtualInterfaceEndpointReference";
    FIELDINFO[0].fieldLocalName = "VirtualInterface.EndpointReference";
    FIELDINFO[0].fieldModel = 1;
    FIELDINFO[0].fieldUri = "http://xml.sap.com/2002/10/metamodel/vi";
    FIELDINFO[0].isSoapArray = false;
    FIELDINFO[0].maxOccurs = 1;
    FIELDINFO[0].minOccurs = 1;
    FIELDINFO[0].nillable = false;
    FIELDINFO[0].soapArrayDimensions = 0;
    FIELDINFO[0].soapArrayItemTypeJavaName = null;
    FIELDINFO[0].soapArrayItemTypeLocalName = null;
    FIELDINFO[0].soapArrayItemTypeUri = null;
    FIELDINFO[0].typeJavaName = "com.sap.engine.lib.descriptors.ws04vi.VirtualInterfaceEndpointReference";
    FIELDINFO[0].typeLocalName = "/xsd:schema/xsd:complexType[23]/xsd:complexContent/xsd:extension/xsd:sequence/xsd:element[1]/xsd:complexType";
    FIELDINFO[0].typeUri = "http://xml.sap.com/2002/10/metamodel/vi";
    FIELDINFO[0].getterMethod = "getVirtualInterfaceEndpointReference";
    FIELDINFO[0].setterMethod = "setVirtualInterfaceEndpointReference";
    FIELDINFO[0].checkMethod = null;
    // Field 1
    FIELDINFO[1].defaultValue = null;
    FIELDINFO[1].fieldJavaName = "VirtualInterfaceFunctions";
    FIELDINFO[1].fieldLocalName = "VirtualInterface.Functions";
    FIELDINFO[1].fieldModel = 1;
    FIELDINFO[1].fieldUri = "http://xml.sap.com/2002/10/metamodel/vi";
    FIELDINFO[1].isSoapArray = false;
    FIELDINFO[1].maxOccurs = 1;
    FIELDINFO[1].minOccurs = 1;
    FIELDINFO[1].nillable = false;
    FIELDINFO[1].soapArrayDimensions = 0;
    FIELDINFO[1].soapArrayItemTypeJavaName = null;
    FIELDINFO[1].soapArrayItemTypeLocalName = null;
    FIELDINFO[1].soapArrayItemTypeUri = null;
    FIELDINFO[1].typeJavaName = "com.sap.engine.lib.descriptors.ws04vi.VirtualInterfaceFunctions";
    FIELDINFO[1].typeLocalName = "/xsd:schema/xsd:complexType[23]/xsd:complexContent/xsd:extension/xsd:sequence/xsd:element[2]/xsd:complexType";
    FIELDINFO[1].typeUri = "http://xml.sap.com/2002/10/metamodel/vi";
    FIELDINFO[1].getterMethod = "getVirtualInterfaceFunctions";
    FIELDINFO[1].setterMethod = "setVirtualInterfaceFunctions";
    FIELDINFO[1].checkMethod = null;
    // Field 2
    FIELDINFO[2].defaultValue = null;
    FIELDINFO[2].fieldJavaName = "VirtualInterfaceSoapExtensionVI";
    FIELDINFO[2].fieldLocalName = "VirtualInterface.SoapExtensionVI";
    FIELDINFO[2].fieldModel = 1;
    FIELDINFO[2].fieldUri = "http://xml.sap.com/2002/10/metamodel/vi";
    FIELDINFO[2].isSoapArray = false;
    FIELDINFO[2].maxOccurs = 1;
    FIELDINFO[2].minOccurs = 0;
    FIELDINFO[2].nillable = false;
    FIELDINFO[2].soapArrayDimensions = 0;
    FIELDINFO[2].soapArrayItemTypeJavaName = null;
    FIELDINFO[2].soapArrayItemTypeLocalName = null;
    FIELDINFO[2].soapArrayItemTypeUri = null;
    FIELDINFO[2].typeJavaName = "com.sap.engine.lib.descriptors.ws04vi.VirtualInterfaceSoapExtensionVI";
    FIELDINFO[2].typeLocalName = "/xsd:schema/xsd:complexType[23]/xsd:complexContent/xsd:extension/xsd:sequence/xsd:element[3]/xsd:complexType";
    FIELDINFO[2].typeUri = "http://xml.sap.com/2002/10/metamodel/vi";
    FIELDINFO[2].getterMethod = "getVirtualInterfaceSoapExtensionVI";
    FIELDINFO[2].setterMethod = "setVirtualInterfaceSoapExtensionVI";
    FIELDINFO[2].checkMethod = null;
    // Field 3
    FIELDINFO[3].defaultValue = null;
    FIELDINFO[3].fieldJavaName = "VirtualInterfaceTypes";
    FIELDINFO[3].fieldLocalName = "VirtualInterface.Types";
    FIELDINFO[3].fieldModel = 1;
    FIELDINFO[3].fieldUri = "http://xml.sap.com/2002/10/metamodel/vi";
    FIELDINFO[3].isSoapArray = false;
    FIELDINFO[3].maxOccurs = 1;
    FIELDINFO[3].minOccurs = 0;
    FIELDINFO[3].nillable = false;
    FIELDINFO[3].soapArrayDimensions = 0;
    FIELDINFO[3].soapArrayItemTypeJavaName = null;
    FIELDINFO[3].soapArrayItemTypeLocalName = null;
    FIELDINFO[3].soapArrayItemTypeUri = null;
    FIELDINFO[3].typeJavaName = "com.sap.engine.lib.descriptors.ws04vi.VirtualInterfaceTypes";
    FIELDINFO[3].typeLocalName = "/xsd:schema/xsd:complexType[23]/xsd:complexContent/xsd:extension/xsd:sequence/xsd:element[4]/xsd:complexType";
    FIELDINFO[3].typeUri = "http://xml.sap.com/2002/10/metamodel/vi";
    FIELDINFO[3].getterMethod = "getVirtualInterfaceTypes";
    FIELDINFO[3].setterMethod = "setVirtualInterfaceTypes";
    FIELDINFO[3].checkMethod = null;
  }


  // Returns model Group Type
  public int _getModelType() {
    return 3;
  }

  private static boolean init = false;
  public synchronized com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] _getFields() {
    if (init == false) {
      com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] parent = super._getFields();
      FIELDINFO =  _insertFieldInfo(parent,FIELDINFO);
      init = true;
    }
    return FIELDINFO;
  }

  public int _getNumberOfFields() {
    return (FIELDINFO.length+super._getNumberOfFields());
  }

  public com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] _getAttributes() {
    return ATTRIBUTEINFO;
  }

  public int _getNumberOfAttributes() {
    return ATTRIBUTEINFO.length;
  }

  static {
    initFields();
    initAttribs();
  }
}
