// Class generated by SAP Labs Bulgaria Generator
// Don't change it !!


/**
 * Copyright (c) 2000 by SAP AG, Walldorf.,
 * url: http:////www.sap.com
 * All rights reserved.
 *
 * This software is the confidential and proprietary information
 * of SAP AG, Walldorf.. You shall not disclose such Confidential
 * Information and shall use it only in accordance with the terms
 * of the license agreement you entered into with SAP.
 */
package com.sap.engine.services.rmi_p4;

import java.rmi.server.Operation;


/**
*
* @author  RMIC Generator
* @version 6.30
*/
public class ContextObjectClassReceiver_Stub  extends com.sap.engine.services.rmi_p4.StubBase 
		implements com.sap.engine.services.rmi_p4.ContextObjectClassReceiver {

	private static final Operation[] operations = {
			new Operation("getClassByName(java.lang.String)")};

	public Operation[] getOperations() {
		return operations;
	}

	public java.lang.Class getClassByName(java.lang.String _param0) throws java.rmi.RemoteException {

		Object state = null;
		if (isLocal) {
			java.rmi.Remote remote;
			if (p4remote == null) {
				throw new java.rmi.NoSuchObjectException("");
			} else {
				remote = p4remote.delegate();
				p4remote.checkPermission("getClassByName(java.lang.String)");
			}
			try {
				com.sap.engine.services.rmi_p4.ContextObjectClassReceiver remoteInterface = (com.sap.engine.services.rmi_p4.ContextObjectClassReceiver) remote;
				return (java.lang.Class) broker.narrow(replicate(remoteInterface.getClassByName( _param0)), java.lang.Class.class);
			} catch (java.lang.ClassCastException rex) {
				Object[] params = new Object[]{_param0};
				Class[] p = new Class[]{java.lang.String.class};
				try { 
					return (java.lang.Class)broker.narrow(replicate(invokeReflect(remote,"getClassByName",params,p)),java.lang.Class.class);
				} catch (NoSuchMethodException nsme) {
					throw (P4RuntimeException)P4ObjectBroker.init().getException(P4ObjectBroker.P4_RuntimeException,com.sap.engine.services.rmi_p4.exception.P4BaseRuntimeException.No_Such_Method,nsme);
				} catch (IllegalAccessException iae) {
					throw (P4RuntimeException)P4ObjectBroker.init().getException(P4ObjectBroker.P4_RuntimeException,com.sap.engine.services.rmi_p4.exception.P4BaseRuntimeException.Illegal_Access,iae);
				} catch (java.lang.reflect.InvocationTargetException ite) {
					Throwable target = (Throwable)replicate(ite.getTargetException());
					if (target instanceof java.rmi.RemoteException) {
					 throw (java.rmi.RemoteException)target;
					} else { 
					 throw (P4RuntimeException)P4ObjectBroker.init().getException(P4ObjectBroker.P4_RuntimeException,com.sap.engine.services.rmi_p4.exception.P4BaseRuntimeException.InvocationTarget, target);
					}
				} 
			} catch (RuntimeException rex) {
				broker.log("P4 Call exception: Exception in execute <getClassByName>", broker.debug);
				broker.log(rex, broker.debug);
					throw rex;
			} catch (java.rmi.RemoteException ex) {
				broker.log("P4 Call exception: Exception in execute <getClassByName>", broker.debug);
				broker.log(ex, broker.debug);
				throw (java.rmi.RemoteException) replicate(ex);
			}
		}
	  com.sap.engine.services.rmi_p4.Call call = null;
		try {
		  call = newCall(0);
			P4ObjectOutput out = call.getOutputStream();
			out.writeObject( _param0);
			invoke(call);
			P4ObjectInput in = call.getResultStream();
		  Object obj;
			obj = in.readObject();
      if(obj == null){
        return null;
      }

      if (obj instanceof com.sap.engine.services.rmi_p4.P4ClassWrapper) {
        ((com.sap.engine.services.rmi_p4.P4ClassWrapper)obj).setStub(this);
         return  ((com.sap.engine.services.rmi_p4.P4ClassWrapper)obj).getCarriedClass();
      } else {
        return (Class) obj;
      }
    } catch (java.rmi.RemoteException ex) {
			throw (java.rmi.RemoteException) ex;
		} catch (java.lang.Exception tr) {
			  //ex.printStackTrace();
			if ( java.lang.RuntimeException.class.isAssignableFrom(tr.getClass()) ) {
				throw (RuntimeException)tr;
			} else {
				throw (P4RuntimeException)P4ObjectBroker.init().getException(P4ObjectBroker.P4_RuntimeException, com.sap.engine.services.rmi_p4.exception.P4BaseRuntimeException.Unexpexted_exception, tr);
			}
		} finally {
			done(call);
		}
	}


}
