/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 09 16:24:16 EET 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors5.webjsptld;

/**
 * Schema complexType Java representation.
 * Represents type {http://java.sun.com/xml/ns/javaee}tld-deferred-valueType
 */
public  class TldDeferredValueType implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Attribute field for attribute {}id
  private java.lang.String _a_Id;
  /**
   * Set method for attribute {}id
   */
  public void setId(java.lang.String _Id) {
    this._a_Id = _Id;
  }
  /**
   * Get method for attribute {}id
   */
  public java.lang.String getId() {
    return _a_Id;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}type
  private com.sap.engine.lib.descriptors5.javaee.FullyQualifiedClassType _f_Type;
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}type
   */
  public void setType(com.sap.engine.lib.descriptors5.javaee.FullyQualifiedClassType _Type) {
    this._f_Type = _Type;
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}type
   */
  public com.sap.engine.lib.descriptors5.javaee.FullyQualifiedClassType getType() {
    return this._f_Type;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof TldDeferredValueType)) return false;
    TldDeferredValueType typed = (TldDeferredValueType) object;
    if (this._a_Id != null) {
      if (typed._a_Id == null) return false;
      if (!this._a_Id.equals(typed._a_Id)) return false;
    } else {
      if (typed._a_Id != null) return false;
    }
    if (this._f_Type != null) {
      if (typed._f_Type == null) return false;
      if (!this._f_Type.equals(typed._f_Type)) return false;
    } else {
      if (typed._f_Type != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_Id != null) {
      result+= this._a_Id.hashCode();
    }
    if (this._f_Type != null) {
      result+= this._f_Type.hashCode();
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
