export const hcConstants = {
    MED_POLICY: 'MED',
    VIS_POLICY: 'VIS',
    DEN_POLICY: 'DEN',
    STATUS_ACTIVE: 'Active',
    STATUS_FUTURE: 'Future',
    STATUS_TERMED: 'Termed',
    TES: 'Track Enrollment Status',
    CBIS: 'CBIS',
    CIM: 'Customer Interface/Metavance',
    MARKETSEARCH: 'H1 Marketplace Search',
    AUTOENROLL: 'Automated Enrollment (AE) History',
    TRR: 'Transaction Reply Report (TRR)',
    APPSEARCH: 'Application Search',
    MIN_RECORDS: 5,
    MAX_RECORDS: 100,
    DEFAULT_AGENCYTYPE: 'Agency',
    OPTION_NONE: '-None-',
    PROVIDER: 'Provider',
    PASSWORD: 'Password',
    ANSWER: 'Answer',
    RELATIONSHIP: 'Relationship',
    SECURITY_QUESTION: 'Security Question',
    LEVEL_OF_CONSENT: 'Level Of Consent',
    SUBMISSION_METHOD: 'Method of Submission',
    DATES_OF_SERVICE: 'Dates of Service',
    LINES_OF_COVERAGE: 'Line of Coverage Applicable',
    LIMITED_DISCLOSURE: 'Limited Disclosure Details',
    GUARDIAN_ADDRESS: 'Guardian Address',
    CONSENT_FOR_PHI: 'Consent for PHI',
    MEDICAL_ORDER:'Medical Child Support Order',
    LEGAL_GUARDIAN: 'Legal Guardian',
    POWER_OF_ATTORNEY: 'Power of Attorney',
    EVENT_POA_INFO: 'eventaccountdetailpoainfo',
    CLOSE: 'close',
    SAVE: 'save',
    RESET: 'reset',
    DELETE: 'delete',
    CONTINUE: 'continue'
}