// Class generated by InQMy Generator
// Don't change it !!


/**
 * Copyright (c) 2000 by SAP AG, Walldorf.,
 * url: http:////www.sap.com
 * All rights reserved.
 *
 * This software is the confidential and proprietary information
 * of SAP AG, Walldorf.. You shall not disclose such Confidential
 * Information and shall use it only in accordance with the terms
 * of the license agreement you entered into with SAP.
 */
package com.sap.engine.services.security.remoteimpl.sessions;

import java.rmi.server.Operation;

import com.sap.engine.services.rmi_p4.*;

/**
 *
 * @author Georgy Stanev 
 * @version 4.0
 */
public class RemoteSecuritySessionsImplp4_Skel extends P4RemoteObject  implements com.sap.engine.services.rmi_p4.Skeleton, java.rmi.Remote {

	public P4ObjectBroker broker = P4ObjectBroker.init();
	private static final Operation[] operations = {
			new Operation("removeSecuritySession(com.sap.engine.services.security.login.SecuritySession)"),
			new Operation("listSecuritySessions()")};

	public RemoteSecuritySessionsImplp4_Skel () {
	}

	public Operation[] getOperations() {
		return operations;
	}

	private static final String[] _implements = {
			"com.sap.engine.services.security.remote.sessions.RemoteSecuritySessions"};

	public String[] getImplemntsObjects() {
		return _implements;
	}

	public void dispatch(java.rmi.Remote remote, Dispatch call, int opnum) throws Exception {

		com.sap.engine.services.security.remoteimpl.sessions.RemoteSecuritySessionsImpl impl = (com.sap.engine.services.security.remoteimpl.sessions.RemoteSecuritySessionsImpl) getDelegate();
		P4ObjectInput in = call.getInputStream();

		switch (opnum) {

			case 0 : {  //method public abstract void com.sap.engine.services.security.remote.sessions.RemoteSecuritySessions.removeSecuritySession(com.sap.engine.services.security.login.SecuritySession) throws java.rmi.RemoteException
				try {
					Object obj0;
					com.sap.engine.services.security.login.SecuritySession param0;
					obj0 = in.readObject();
					try {
						 param0 = (com.sap.engine.services.security.login.SecuritySession)obj0;
					} catch (ClassCastException ex) {
						 param0 = (com.sap.engine.services.security.login.SecuritySession) broker.narrow(obj0,com.sap.engine.services.security.login.SecuritySession.class);
					}
					impl.removeSecuritySession(param0);
					P4ObjectOutput out = call.getOutputStream();
				} catch (Exception ex) {
					throw ex;
				}
				break;
			}
			case 1 : {  //method public abstract com.sap.engine.services.security.login.SecuritySession[] com.sap.engine.services.security.remote.sessions.RemoteSecuritySessions.listSecuritySessions() throws java.rmi.RemoteException
				try {
					com.sap.engine.services.security.login.SecuritySession[] _result = impl.listSecuritySessions();
					P4ObjectOutput out = call.getOutputStream();
					out.writeObject( _result);
					out.flush();
				} catch (Exception ex) {
					throw ex;
				}
				break;
			}
		}
	}

}
