// Class generated by SAP Labs Bulgaria Generator
// Don't change it !!


/**
 * Copyright (c) 2000 by SAP AG, Walldorf.,
 * url: http:////www.sap.com
 * All rights reserved.
 *
 * This software is the confidential and proprietary information
 * of SAP AG, Walldorf.. You shall not disclose such Confidential
 * Information and shall use it only in accordance with the terms
 * of the license agreement you entered into with SAP.
 */
package com.sap.engine.services.security.remoteimpl;

import java.rmi.server.Operation;

import com.sap.engine.services.rmi_p4.*;

/**
 *
 * @author RMIC Generator 
 * @version 6.30
 */
public class RemoteAuthorizationImplp4_Skel extends P4RemoteObject  implements com.sap.engine.services.rmi_p4.Skeleton, java.rmi.Remote {

	public P4ObjectBroker broker = P4ObjectBroker.init();
	private static final Operation[] operations = {
			new Operation("getResources()"),
			new Operation("getSecurityRoles()"),
			new Operation("getSecurityRoles(java.lang.String)")};

	public RemoteAuthorizationImplp4_Skel () {
	}

	public Operation[] getOperations() {
		return operations;
	}

	private static final String[] _implements = {
			"com.sap.engine.services.security.remote.RemoteAuthorization"};

	public String[] getImplemntsObjects() {
		return _implements;
	}

	public void dispatch(java.rmi.Remote remote, Dispatch call, int opnum) throws Exception {

		com.sap.engine.services.security.remoteimpl.RemoteAuthorizationImpl impl = (com.sap.engine.services.security.remoteimpl.RemoteAuthorizationImpl) delegate();
		P4ObjectInput in = call.getInputStream();

		switch (opnum) {

			case 0 : {  //method public abstract com.sap.engine.services.security.remote.resource.RemoteSecurityResources com.sap.engine.services.security.remote.RemoteAuthorization.getResources() throws java.rmi.RemoteException
				try {
					com.sap.engine.services.security.remote.resource.RemoteSecurityResources _result = impl.getResources();
					P4ObjectOutput out = call.getOutputStream();
					out.writeObject( _result);
					out.flush();
				} catch (Exception ex) {
					throw ex;
				}
				break;
			}
			case 1 : {  //method public abstract com.sap.engine.services.security.remote.roles.RemoteSecurityRoles com.sap.engine.services.security.remote.RemoteAuthorization.getSecurityRoles() throws java.rmi.RemoteException
				try {
					com.sap.engine.services.security.remote.roles.RemoteSecurityRoles _result = impl.getSecurityRoles();
					P4ObjectOutput out = call.getOutputStream();
					out.writeObject( _result);
					out.flush();
				} catch (Exception ex) {
					throw ex;
				}
				break;
			}
			case 2 : {  //method public abstract com.sap.engine.services.security.remote.roles.RemoteSecurityRoles com.sap.engine.services.security.remote.RemoteAuthorization.getSecurityRoles(java.lang.String) throws java.rmi.RemoteException
				try {
					Object obj0;
					java.lang.String param0;
					obj0 = in.readObject();
					try {
						 param0 = (java.lang.String)obj0;
					} catch (ClassCastException ex) {
						 param0 = (java.lang.String) broker.narrow(obj0,java.lang.String.class);
					}
					com.sap.engine.services.security.remote.roles.RemoteSecurityRoles _result = impl.getSecurityRoles(param0);
					P4ObjectOutput out = call.getOutputStream();
					out.writeObject( _result);
					out.flush();
				} catch (Exception ex) {
					throw ex;
				}
				break;
			}
		}
	}

}
