export const hcConstants = {
    MED_POLICY: 'MED',
    VIS_POLICY: 'VIS',
    DEN_POLICY: 'DEN',
    MES_POLICY: 'MES',
    STATUS_ACTIVE: 'Active',
    STATUS_FUTURE: 'Future',
    STATUS_TERMED: 'Termed',
    STATUS_OPENED: 'Open',
    STATUS_CLOSED: 'Closed',
    STATUS_PENDING: 'Pending - Response',
    TES: 'Track Enrollment Status',
    CBIS: 'CBIS',
    CIM: 'Customer Interface/Metavance',
    MARKETSEARCH: 'H1 Marketplace Search',
    AUTOENROLL: 'Automated Enrollment (AE) History',
    TRR: 'Transaction Reply Report (TRR)',
    APPSEARCH:'Application Search',
    MIN_RECORDS: 5,
    MAX_RECORDS: 100,
    DEFAULT_AGENCYTYPE: 'Agency',
    OPTION_NONE: '-None-',
    PROVIDER: 'Provider',
    AGENCY: 'Agent/Broker',
    GROUP: 'Group',
    MEMBER: 'Member',
    INQUIRED_ABOUT:'Inquired About',
    DCN: 'sDCN',
    MIN_SEARCH_CHAR: 2,
    LEGACY_TYPE: 'sType',
    LEGACY_POLICY: 'sPolicy',
    QUESTION: 'Question',
    PASS: 'Password',
    ANSWER: 'Answer',
    EXECUTOR: 'Executor of Estate',
    RELATIONSHIP: 'Relationship',
    SECURITY_QUESTION: 'Security Question',
    LEVEL_OF_CONSENT: 'Level Of Consent',
    SUBMISSION_METHOD: 'Method of Submission',
    DATES_OF_SERVICE: 'Dates of Service',
    LINES_OF_COVERAGE: 'Line of Coverage Applicable',
    LIMITED_DISCLOSURE: 'Limited Disclosure Details',
    GUARDIAN_ADDRESS: 'Guardian Address',
    CONSENT_FOR_PHI: 'Consent for PHI',
    MEDICAL_ORDER:'Medical Child Support Order',
    LEGAL_GUARDIAN: 'Legal Guardian',
    POWER_OF_ATTORNEY: 'Power of Attorney',
    EVENT_POA_INFO: 'eventaccountdetailpoainfo',
    CLOSE: 'close',
    SAVE: 'save',
    RESET: 'reset',
    DELETE: 'delete',
    CONTINUE: 'continue',
    CLOSEOVERLAY: 'closeoverlay',
    Date_2K19 : '2009',
    MAXDATEYEAR: 2.001368925393566,
    LEGACY_TABLE: 'Legacy Contact History',
    STATUS_PROGRESS: 'In Progress',
    LEGACY_SDATE: '01/01/2019',
    LEGACY_EDATE: '12/31/2020',
    TASK_NOTES: 'tasknotes',
    TASK_AUDIT_TRAIL: 'taskaudittrail',
    TASK_ATTACHMENTS: 'taskattachments',
    TASK_DETAILS: 'taskdetails',
    INQUIRY_NOTES: 'inquirynotes',
    INQUIRY_AUDIT_TRAIL: 'inquiryaudittrail',
    INQUIRY_ATTACHEMNTS: 'inquiryattachments',
    INQUIRY_DETAILS: 'inquirydetails',
    INQUIRY_TASK_LIST: 'inquirytasklist',
    DATE_MDY: 'MM/DD/YYYY',
    DATE_YMD: 'YYYY/MM/DD',
    MEMBER_POLICY_ID: 'MEMBER_POLICY_ID',
    ADDITIONAL_PLAN: 'Additional Plan Information',
    MEDICAID_PLAN: 'Medicaid Plan Information',
    SNP_DE: 'DE',
    SNP_CC: 'CC',
    SNP_IN: 'IN',
    LIS_HELP_PAGE: 'https://dctm.humana.com/Mentor/xWeb/viewtopic.aspx?sChronicleID=09000929828c89b8',
    MTM_HELP_PAGE: 'https://dctm.humana.com/Mentor/xWeb/viewtopic.aspx?sChronicleID=0900092980d269db&dl=0&searchID=VI-8d8fa978a7f1c83&row=0&mode=Mentor',
    YES: 'Yes',
    NO: 'No',
    NO_VAL: 'No Value',
    MEMBER_ID: 'Member IDs',
    DUAL_STATUS: 'dual-status',
    OTHER_INSURANCE: 'other-insurance',
    RECENT_FIRST: 'RECENT_FIRST',
    OLDER_FIRST: 'OLDER_FIRST',
    OTHER_INSURANCE_ICON: 'OtherInsurance',
    PHARMACY_SPECIALIST_PROFILE_NAME :'Humana Pharmacy Specialist',
    Customer_Care_Specialist :'Customer Care Specialist',
    Benefits_Information_section :'Benefits Information',
    Health_Indicators_section    :'Health Indicators',
    Primary_care_phsician        :'Primary care phsician',
	CLAIM_PAGE : 'Claim_Details_LWC',
	Member_Search: 'Member Search',
    Group_Search : 'Group Search',
    Provider_Search :'providerResutls',
    Agency_Search : 'agencyResults',
    CUSTOMER_CARE_SUPERVISOR : 'Customer Care Supervisor',
    MEDICARE_PART_D: 'Medicare Part D Redetermination',
    MEDICARE_PART_D_API:'Medicare_Part_D_Redetermination_Request_Lightning',
    MEDICARE_GOOD_CAUSE:'Medicare Good Cause Reinstatement Form',
    MEDICARE_GOOD_CAUSE_API:'Medicare_Good_Cause_Reinstatement_Flow_Lightning1',
    MEDICARE_EXPEDITED_APPEAL: 'Medicare/Medicaid Expedited Appeal',
    MEDICARE_EXPEDITED_APPEAL_API: 'Medicare_Process_Medicare_Expedited_Appeals_Request_Lightning',
    MEDICARE_EXPEDITED_APPEAL_HDR:'Medicare and Medicaid Other Insurance Form',
    UPDATE_PLAN_DEMOGRAPHIC:'Update Plan Demographic',
    UPDATE_PLAN_DEMOGRAPHIC_API:'Update_Plan_Demographic',
    CASE_PROVIDER_API:'Provider_Case',
    CASE_AGENT_API:'Agent_Broker_Case',
    BIRTH_DATE_NOT_FUTURE:"Birth Date cannot be a today's/future date",
	hLimit : 4,
	CASE_GROUP_API:'Group_Case',
    CASE_MEMBER_API:'Member_Case',	
    CREDITABLE_COVERAGE: 'Medicare Creditable Coverage Attestation',
    CREDITABLE_COVERAGE_API:'Creditable_Coverage_Attestation_lghtning',
    DEAA_Member_Opt_Out :'DEAA Medicare Opt Out',
    MEDICAID_PAR_PROVIDER_NOT_ACCEPTING:'Medicaid PAR Provider Not Accepting',
    QAA_COMPLAINT:'QAA Complaint',
	Closed_Member_Case_API:'Closed_Member_Case',
    Medicare_Case_API:'Medicare_Case',
    Closed_Medicare_Case_API:'Closed_Medicare_Case',
    System_Admin:'System Administrator',
	open_App_Detail_Page: 'openAppDetailPage',
    Member_Detail: 'Member Detail',
    Detail: 'Detail',
	MEMBER_PLAN_INFORMATION: 'Member Plan Information',
	POLICY_DETAILS: 'Policy Details',
	MEMBER_IDS: 'Member Ids',
	POLICY_TAB: 'PolicyTab',
	MEMBER_TAB: 'MemberTab',
	SUBSCRIBER_TAB: 'SubscriberTab',
	PLAN_TAB: 'PlanTab',
	MEMBER_PLAN_INFORMATION_CCS: 'Member Plan Information CCS',
	enrollmentMemberDetailPageHUM:'enrollmentMemberDetailPageHUM',
	openH1App_Detail_Page:'openH1AppDetailPage',
    H1MarketPlaceMemberDetailPageHUM:'H1MarketPlaceMemberDetailPageHUM',
    MarketPlace_Details:'Market Place Details',
    START_DATE_DIFF:'48',
    END_DATE_DIFF:'24',
    OLD_DATE_LIMIT:'01/01/2014',
    ARCHIVALSEARCH_MIN_REC: 50,
    ARCHIVALSEARCH_MAX_REC: 500,
    ARCHIVALDETAIL_MIN_REC: 25,
    NO_RECORDS: 0,
	DualEligiblity:'DualEligiblity'
}