/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 09 16:24:16 EET 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors5.web;

/**
 * Schema complexType Java representation.
 * Represents type {http://java.sun.com/xml/ns/javaee}filter-mappingType
 */
public  class FilterMappingType implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Attribute field for attribute {}id
  private java.lang.String _a_Id;
  /**
   * Set method for attribute {}id
   */
  public void setId(java.lang.String _Id) {
    this._a_Id = _Id;
  }
  /**
   * Get method for attribute {}id
   */
  public java.lang.String getId() {
    return _a_Id;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}filter-name
  private com.sap.engine.lib.descriptors5.web.FilterNameType _f_FilterName;
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}filter-name
   */
  public void setFilterName(com.sap.engine.lib.descriptors5.web.FilterNameType _FilterName) {
    this._f_FilterName = _FilterName;
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}filter-name
   */
  public com.sap.engine.lib.descriptors5.web.FilterNameType getFilterName() {
    return this._f_FilterName;
  }

  // Model group field class 
  public static class Choice1 implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

    public Choice1() {
    }


    // // Active choise field
    private int _c_validField = 0;
    private com.sap.engine.lib.descriptors5.javaee.UrlPatternType _f_UrlPattern;
    /**
     * Set method for element {http://java.sun.com/xml/ns/javaee}url-pattern
     */
    public void setUrlPattern(com.sap.engine.lib.descriptors5.javaee.UrlPatternType _UrlPattern) {
      if (this._c_validField != 0 && this._c_validField != 1) {
        this.unsetContent();
      }
      this._f_UrlPattern = _UrlPattern;
      this._c_validField = 1;
    }
    /**
     * Get method for element {http://java.sun.com/xml/ns/javaee}url-pattern
     */
    public com.sap.engine.lib.descriptors5.javaee.UrlPatternType getUrlPattern() {
      if (this._c_validField != 1) {
        return null;
      }
      return this._f_UrlPattern;
    }
    /**
     * Check method for element {http://java.sun.com/xml/ns/javaee}url-pattern
     */
    public boolean isSetUrlPattern() {
      return (this._c_validField ==1);
    }
    private com.sap.engine.lib.descriptors5.web.ServletNameType _f_ServletName;
    /**
     * Set method for element {http://java.sun.com/xml/ns/javaee}servlet-name
     */
    public void setServletName(com.sap.engine.lib.descriptors5.web.ServletNameType _ServletName) {
      if (this._c_validField != 0 && this._c_validField != 2) {
        this.unsetContent();
      }
      this._f_ServletName = _ServletName;
      this._c_validField = 2;
    }
    /**
     * Get method for element {http://java.sun.com/xml/ns/javaee}servlet-name
     */
    public com.sap.engine.lib.descriptors5.web.ServletNameType getServletName() {
      if (this._c_validField != 2) {
        return null;
      }
      return this._f_ServletName;
    }
    /**
     * Check method for element {http://java.sun.com/xml/ns/javaee}servlet-name
     */
    public boolean isSetServletName() {
      return (this._c_validField ==2);
    }
    /**
     * Common get method for choice type.
     */
    public java.lang.Object getContent() {
      switch (this._c_validField) {
        case 1: return this.getUrlPattern();
        case 2: return this.getServletName();
      }
      return null;
    }
    /**
     * Returns true if this choice has content set.
     */
    public boolean isSetContent() {
      return (this._c_validField == 0);
    }
    /**
     * Clears choice content.
     */
    public void unsetContent() {
      switch (this._c_validField) {
        case  1: {
          this._f_UrlPattern = null;
          break;
        }
        case  2: {
          this._f_ServletName = null;
          break;
        }
      }
      this._c_validField = 0;
    }

    /**
     * Equals method implementation.
     */
    public boolean equals(Object object) {
      if (object == null) return false;
      if (!(object instanceof Choice1)) return false;
      Choice1 typed = (Choice1) object;
      if (this._c_validField != typed._c_validField) return false;
      switch (this._c_validField) {
        case 1: {
          if (this._f_UrlPattern != null) {
            if (typed._f_UrlPattern == null) return false;
            if (!this._f_UrlPattern.equals(typed._f_UrlPattern)) return false;
          } else {
            if (typed._f_UrlPattern != null) return false;
          }
          break;
        }
        case 2: {
          if (this._f_ServletName != null) {
            if (typed._f_ServletName == null) return false;
            if (!this._f_ServletName.equals(typed._f_ServletName)) return false;
          } else {
            if (typed._f_ServletName != null) return false;
          }
          break;
        }
      }
      return true;
    }

    /**
     * Hashcode method implementation.
     */
    public int hashCode() {
      int result = 0;
      switch (this._c_validField) {
        case 1: {
          if (this._f_UrlPattern != null) {
            result+= this._f_UrlPattern.hashCode();
          }
          result = result * this._c_validField;
          break;
        }
        case 2: {
          if (this._f_ServletName != null) {
            result+= this._f_ServletName.hashCode();
          }
          result = result * this._c_validField;
          break;
        }
      }
      return result;
    }

    public java.lang.String get__ID() {
      return java.lang.String.valueOf(super.hashCode());
    }
  }

  private java.util.ArrayList _f_ChoiceGroup1 = new java.util.ArrayList();
  public void setChoiceGroup1(Choice1[] _ChoiceGroup1) {
    this._f_ChoiceGroup1.clear();
    if (_ChoiceGroup1 != null) {
      for (int i=0; i<_ChoiceGroup1.length; i++) {
        if (_ChoiceGroup1[i] != null)
          this._f_ChoiceGroup1.add(_ChoiceGroup1[i]);
      }
    }
  }
  public Choice1[] getChoiceGroup1() {
    Choice1[] result = new Choice1[_f_ChoiceGroup1.size()];
    _f_ChoiceGroup1.toArray(result);
    return result;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}dispatcher
  private java.util.ArrayList _f_Dispatcher = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}dispatcher
   */
  public void setDispatcher(com.sap.engine.lib.descriptors5.web.DispatcherType[] _Dispatcher) {
    this._f_Dispatcher.clear();
    if (_Dispatcher != null) {
      for (int i=0; i<_Dispatcher.length; i++) {
        if (_Dispatcher[i] != null)
          this._f_Dispatcher.add(_Dispatcher[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}dispatcher
   */
  public com.sap.engine.lib.descriptors5.web.DispatcherType[] getDispatcher() {
    com.sap.engine.lib.descriptors5.web.DispatcherType[] result = new com.sap.engine.lib.descriptors5.web.DispatcherType[_f_Dispatcher.size()];
    _f_Dispatcher.toArray(result);
    return result;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof FilterMappingType)) return false;
    FilterMappingType typed = (FilterMappingType) object;
    if (this._a_Id != null) {
      if (typed._a_Id == null) return false;
      if (!this._a_Id.equals(typed._a_Id)) return false;
    } else {
      if (typed._a_Id != null) return false;
    }
    if (this._f_FilterName != null) {
      if (typed._f_FilterName == null) return false;
      if (!this._f_FilterName.equals(typed._f_FilterName)) return false;
    } else {
      if (typed._f_FilterName != null) return false;
    }
    Choice1[] _f_ChoiceGroup11 = this.getChoiceGroup1();
    Choice1[] _f_ChoiceGroup12 = typed.getChoiceGroup1();
    if (_f_ChoiceGroup11 != null) {
      if (_f_ChoiceGroup12 == null) return false;
      if (_f_ChoiceGroup11.length != _f_ChoiceGroup12.length) return false;
      for (int i1 = 0; i1 < _f_ChoiceGroup11.length ; i1++) {
        if (_f_ChoiceGroup11[i1] != null) {
          if (_f_ChoiceGroup12[i1] == null) return false;
          if (!_f_ChoiceGroup11[i1].equals(_f_ChoiceGroup12[i1])) return false;
        } else {
          if (_f_ChoiceGroup12[i1] != null) return false;
        }
      }
    } else {
      if (_f_ChoiceGroup12 != null) return false;
    }
    com.sap.engine.lib.descriptors5.web.DispatcherType[] _f_Dispatcher1 = this.getDispatcher();
    com.sap.engine.lib.descriptors5.web.DispatcherType[] _f_Dispatcher2 = typed.getDispatcher();
    if (_f_Dispatcher1 != null) {
      if (_f_Dispatcher2 == null) return false;
      if (_f_Dispatcher1.length != _f_Dispatcher2.length) return false;
      for (int i1 = 0; i1 < _f_Dispatcher1.length ; i1++) {
        if (_f_Dispatcher1[i1] != null) {
          if (_f_Dispatcher2[i1] == null) return false;
          if (!_f_Dispatcher1[i1].equals(_f_Dispatcher2[i1])) return false;
        } else {
          if (_f_Dispatcher2[i1] != null) return false;
        }
      }
    } else {
      if (_f_Dispatcher2 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_Id != null) {
      result+= this._a_Id.hashCode();
    }
    if (this._f_FilterName != null) {
      result+= this._f_FilterName.hashCode();
    }
    Choice1[] _f_ChoiceGroup11 = this.getChoiceGroup1();
    if (_f_ChoiceGroup11 != null) {
      for (int i1 = 0; i1 < _f_ChoiceGroup11.length ; i1++) {
        if (_f_ChoiceGroup11[i1] != null) {
          result+= _f_ChoiceGroup11[i1].hashCode();
        }
      }
    }
    com.sap.engine.lib.descriptors5.web.DispatcherType[] _f_Dispatcher1 = this.getDispatcher();
    if (_f_Dispatcher1 != null) {
      for (int i1 = 0; i1 < _f_Dispatcher1.length ; i1++) {
        if (_f_Dispatcher1[i1] != null) {
          result+= _f_Dispatcher1[i1].hashCode();
        }
      }
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
