/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 09 16:24:16 EET 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors5.web;

/**
 * Schema complexType Java representation.
 * Represents type {http://java.sun.com/xml/ns/javaee}login-configType
 */
public  class LoginConfigType implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Attribute field for attribute {}id
  private java.lang.String _a_Id;
  /**
   * Set method for attribute {}id
   */
  public void setId(java.lang.String _Id) {
    this._a_Id = _Id;
  }
  /**
   * Get method for attribute {}id
   */
  public java.lang.String getId() {
    return _a_Id;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}auth-method
  private com.sap.engine.lib.descriptors5.web.AuthMethodType _f_AuthMethod;
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}auth-method
   */
  public void setAuthMethod(com.sap.engine.lib.descriptors5.web.AuthMethodType _AuthMethod) {
    this._f_AuthMethod = _AuthMethod;
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}auth-method
   */
  public com.sap.engine.lib.descriptors5.web.AuthMethodType getAuthMethod() {
    return this._f_AuthMethod;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}realm-name
  private com.sap.engine.lib.descriptors5.javaee.String _f_RealmName;
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}realm-name
   */
  public void setRealmName(com.sap.engine.lib.descriptors5.javaee.String _RealmName) {
    this._f_RealmName = _RealmName;
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}realm-name
   */
  public com.sap.engine.lib.descriptors5.javaee.String getRealmName() {
    return this._f_RealmName;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}form-login-config
  private com.sap.engine.lib.descriptors5.web.FormLoginConfigType _f_FormLoginConfig;
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}form-login-config
   */
  public void setFormLoginConfig(com.sap.engine.lib.descriptors5.web.FormLoginConfigType _FormLoginConfig) {
    this._f_FormLoginConfig = _FormLoginConfig;
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}form-login-config
   */
  public com.sap.engine.lib.descriptors5.web.FormLoginConfigType getFormLoginConfig() {
    return this._f_FormLoginConfig;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof LoginConfigType)) return false;
    LoginConfigType typed = (LoginConfigType) object;
    if (this._a_Id != null) {
      if (typed._a_Id == null) return false;
      if (!this._a_Id.equals(typed._a_Id)) return false;
    } else {
      if (typed._a_Id != null) return false;
    }
    if (this._f_AuthMethod != null) {
      if (typed._f_AuthMethod == null) return false;
      if (!this._f_AuthMethod.equals(typed._f_AuthMethod)) return false;
    } else {
      if (typed._f_AuthMethod != null) return false;
    }
    if (this._f_RealmName != null) {
      if (typed._f_RealmName == null) return false;
      if (!this._f_RealmName.equals(typed._f_RealmName)) return false;
    } else {
      if (typed._f_RealmName != null) return false;
    }
    if (this._f_FormLoginConfig != null) {
      if (typed._f_FormLoginConfig == null) return false;
      if (!this._f_FormLoginConfig.equals(typed._f_FormLoginConfig)) return false;
    } else {
      if (typed._f_FormLoginConfig != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_Id != null) {
      result+= this._a_Id.hashCode();
    }
    if (this._f_AuthMethod != null) {
      result+= this._f_AuthMethod.hashCode();
    }
    if (this._f_RealmName != null) {
      result+= this._f_RealmName.hashCode();
    }
    if (this._f_FormLoginConfig != null) {
      result+= this._f_FormLoginConfig.hashCode();
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
