/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 09 16:24:16 EET 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors5.web;

/**
 * Enumeration Java representation.
 * Represents type {http://java.sun.com/xml/ns/javaee}null-charType
 */
public class NullCharType implements java.io.Serializable {

  public static final java.lang.String _EMPTY_STRING = "";

  public static final NullCharType EMPTY_STRING = new NullCharType(_EMPTY_STRING);

  //  Enumeration Content
  protected java.lang.String _value;

  public NullCharType(java.lang.String _value) {
    if (_EMPTY_STRING.equals(_value)) {
      this._value = _value;
      return;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+_value+"] passed.");
  }

  public java.lang.String getValue() {
    return _value;
  }

  public static NullCharType fromValue(java.lang.String value) {
    if (_EMPTY_STRING.equals(value)) {
      return EMPTY_STRING;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+value+"] passed.");
  }

  public static NullCharType fromString(String value) {
    if ("".equals(value)) {
      return EMPTY_STRING;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+value+"] passed.");
  }

  public java.lang.String toString() {
    if (_EMPTY_STRING.equals(_value)) {
      return "";
    }
    return java.lang.String.valueOf(_value);
  }

  public boolean equals(java.lang.Object obj) {
    if (obj != null) {
      if (obj instanceof NullCharType) {
        if (_value.equals(((NullCharType)obj)._value)) {
          return true;
        }
      }
    }
    return false;
  }

  public int hashCode() {
    return this._value.hashCode();
  }

}
