/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 09 16:24:16 EET 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors5.web;

/**
 * Schema complexType Java representation.
 * Represents type {http://java.sun.com/xml/ns/javaee}servlet-mappingType
 */
public  class ServletMappingType implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  // Attribute field for attribute {}id
  private java.lang.String _a_Id;
  /**
   * Set method for attribute {}id
   */
  public void setId(java.lang.String _Id) {
    this._a_Id = _Id;
  }
  /**
   * Get method for attribute {}id
   */
  public java.lang.String getId() {
    return _a_Id;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}servlet-name
  private com.sap.engine.lib.descriptors5.web.ServletNameType _f_ServletName;
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}servlet-name
   */
  public void setServletName(com.sap.engine.lib.descriptors5.web.ServletNameType _ServletName) {
    this._f_ServletName = _ServletName;
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}servlet-name
   */
  public com.sap.engine.lib.descriptors5.web.ServletNameType getServletName() {
    return this._f_ServletName;
  }

  // Element field for element {http://java.sun.com/xml/ns/javaee}url-pattern
  private java.util.ArrayList _f_UrlPattern = new java.util.ArrayList();
  /**
   * Set method for element {http://java.sun.com/xml/ns/javaee}url-pattern
   */
  public void setUrlPattern(com.sap.engine.lib.descriptors5.javaee.UrlPatternType[] _UrlPattern) {
    this._f_UrlPattern.clear();
    if (_UrlPattern != null) {
      for (int i=0; i<_UrlPattern.length; i++) {
        if (_UrlPattern[i] != null)
          this._f_UrlPattern.add(_UrlPattern[i]);
      }
    }
  }
  /**
   * Get method for element {http://java.sun.com/xml/ns/javaee}url-pattern
   */
  public com.sap.engine.lib.descriptors5.javaee.UrlPatternType[] getUrlPattern() {
    com.sap.engine.lib.descriptors5.javaee.UrlPatternType[] result = new com.sap.engine.lib.descriptors5.javaee.UrlPatternType[_f_UrlPattern.size()];
    _f_UrlPattern.toArray(result);
    return result;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof ServletMappingType)) return false;
    ServletMappingType typed = (ServletMappingType) object;
    if (this._a_Id != null) {
      if (typed._a_Id == null) return false;
      if (!this._a_Id.equals(typed._a_Id)) return false;
    } else {
      if (typed._a_Id != null) return false;
    }
    if (this._f_ServletName != null) {
      if (typed._f_ServletName == null) return false;
      if (!this._f_ServletName.equals(typed._f_ServletName)) return false;
    } else {
      if (typed._f_ServletName != null) return false;
    }
    com.sap.engine.lib.descriptors5.javaee.UrlPatternType[] _f_UrlPattern1 = this.getUrlPattern();
    com.sap.engine.lib.descriptors5.javaee.UrlPatternType[] _f_UrlPattern2 = typed.getUrlPattern();
    if (_f_UrlPattern1 != null) {
      if (_f_UrlPattern2 == null) return false;
      if (_f_UrlPattern1.length != _f_UrlPattern2.length) return false;
      for (int i1 = 0; i1 < _f_UrlPattern1.length ; i1++) {
        if (_f_UrlPattern1[i1] != null) {
          if (_f_UrlPattern2[i1] == null) return false;
          if (!_f_UrlPattern1[i1].equals(_f_UrlPattern2[i1])) return false;
        } else {
          if (_f_UrlPattern2[i1] != null) return false;
        }
      }
    } else {
      if (_f_UrlPattern2 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_Id != null) {
      result+= this._a_Id.hashCode();
    }
    if (this._f_ServletName != null) {
      result+= this._f_ServletName.hashCode();
    }
    com.sap.engine.lib.descriptors5.javaee.UrlPatternType[] _f_UrlPattern1 = this.getUrlPattern();
    if (_f_UrlPattern1 != null) {
      for (int i1 = 0; i1 < _f_UrlPattern1.length ; i1++) {
        if (_f_UrlPattern1[i1] != null) {
          result+= _f_UrlPattern1[i1].hashCode();
        }
      }
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
