/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Mar 09 16:24:16 EET 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors5.web;

/**
 * Enumeration Java representation.
 * Represents type {http://java.sun.com/xml/ns/javaee}web-app-versionType
 */
public class WebAppVersionType implements java.io.Serializable {

  public static final java.lang.String _Enum24 = "2.4";
  public static final java.lang.String _Enum25 = "2.5";

  public static final WebAppVersionType Enum24 = new WebAppVersionType(_Enum24);
  public static final WebAppVersionType Enum25 = new WebAppVersionType(_Enum25);

  //  Enumeration Content
  protected java.lang.String _value;

  public WebAppVersionType(java.lang.String _value) {
    if (_Enum24.equals(_value)) {
      this._value = _value;
      return;
    }
    if (_Enum25.equals(_value)) {
      this._value = _value;
      return;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+_value+"] passed.");
  }

  public java.lang.String getValue() {
    return _value;
  }

  public static WebAppVersionType fromValue(java.lang.String value) {
    if (_Enum24.equals(value)) {
      return Enum24;
    }
    if (_Enum25.equals(value)) {
      return Enum25;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+value+"] passed.");
  }

  public static WebAppVersionType fromString(String value) {
    if ("2.4".equals(value)) {
      return Enum24;
    }
    if ("2.5".equals(value)) {
      return Enum25;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+value+"] passed.");
  }

  public java.lang.String toString() {
    if (_Enum24.equals(_value)) {
      return "2.4";
    }
    if (_Enum25.equals(_value)) {
      return "2.5";
    }
    return java.lang.String.valueOf(_value);
  }

  public boolean equals(java.lang.Object obj) {
    if (obj != null) {
      if (obj instanceof WebAppVersionType) {
        if (_value.equals(((WebAppVersionType)obj)._value)) {
          return true;
        }
      }
    }
    return false;
  }

  public int hashCode() {
    return this._value.hashCode();
  }

}
