export const phoneBookConstants = {
    QUEUE_NAME: 'Queue Name',
    CALL_REASON: 'Call Reason',
    QUEUE_FIELD: 'QueueName',
    REASON_FIELD: 'CallReason',
    SELECT: 'Select',
    MEMBER: 'Member',
    GROUP: 'Group',
    AGENT: 'Agent',
    PROVIDER: 'Provider',
    BROKER: 'Broker',
    EMPLOYER: 'Employer',
    AGENCY: 'Agency',
    UNKNOWN: 'Unknown',
    TRANSFER_PHONE_BOOK: 'Transfer Phone Book',
    ISMANUAL_N: 'N',
    ISMANUAL_Y: 'Y',
    MEMBER_M: 'M',
    PROVIDER_P: 'P',
    GROUP_G: 'G',
    EMPLOYER_E: 'E',
    AGENT_A: 'A',
    UNKNOWN_U: 'U',
    CATEGORY_CD: 'CategoryCd',
    WARM: 'WARM',
    CONSULT: 'consultTransfer',
    COLD: 'COLD',
    BLIND: 'blindTransfer',
    CONTACT_ASSISTANCE: 'contact the help desk for assistance',
    INQR_TYP: 'INQR_TYP',
    INQR_ID: 'INQR_ID',
    INQR_FIRST: 'INQR_FIRST',
    INQR_LAST: 'INQR_LAST',
    INQR_DOB: 'INQR_DOB',
    INQA_TYP: 'INQA_TYP',
    INQA_ID: 'INQA_ID',
    INQA_FIRST: 'INQA_FIRST',
    INQA_LAST: 'INQA_LAST',
    INQA_DOB: 'INQA_DOB',
    INQA_GRP_ID : 'INQA_GRP_ID',
    TRANSFER_TYPE: 'TRANSFER_TYPE',
    TRANSFER_ETIM: 'TRANSFER_ETIM',
    CRM_STRIDE: 'CRM Strides || ',
    AWC_COMPLETED: 'ACW Completed',
    ROUTING_STATUS: 'Routing Status_',
    CALL_DISCONNECTED: 'Call Disconnected',
    INTERACTION_CONNECTED: 'Interaction: connected',
    STATION: 'Station',
    STATUS_CHANGED: 'Status changed to ',
    OUTBOUND: 'Outbound',
    INBOUND: 'Inbound',
    LOGGED_IN: 'User logged in',
    LOGGED_OUT: 'User logged out',
    OUTBOUND_CALL: 'Outbound Call',
    CRMS_685_PCC_Access_HUM: 'CRMS_685_PCC_Customer_Service_Access',
    IsSoftPhoneIndicator:'Y',
    Protected_Message: 'Transfer phonebook not available for this transfer.  Please follow your LOB Mentor process.'
}