/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu May 05 11:45:02 EEST 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.lib.descriptors.ws04wsd;

/**
 * Schema complexType Java representation.
 * Represents type {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinitionState
 */
public  class WebServiceDefinitionState implements java.io.Serializable,java.lang.Cloneable {

  // Attribute field for attribute {}mmTimestamp
  private java.lang.String _a_MmTimestamp;
  /**
   * Set method for attribute {}mmTimestamp
   */
  public void setMmTimestamp(java.lang.String _MmTimestamp) {
    this._a_MmTimestamp = _MmTimestamp;
  }
  /**
   * Get method for attribute {}mmTimestamp
   */
  public java.lang.String getMmTimestamp() {
    return _a_MmTimestamp;
  }

  // Attribute field for attribute {}mmRelease
  private java.lang.String _a_MmRelease;
  /**
   * Set method for attribute {}mmRelease
   */
  public void setMmRelease(java.lang.String _MmRelease) {
    this._a_MmRelease = _MmRelease;
  }
  /**
   * Get method for attribute {}mmRelease
   */
  public java.lang.String getMmRelease() {
    return _a_MmRelease;
  }

  // Attribute field for attribute {}mmVersion
  private java.lang.String _a_MmVersion;
  /**
   * Set method for attribute {}mmVersion
   */
  public void setMmVersion(java.lang.String _MmVersion) {
    this._a_MmVersion = _MmVersion;
  }
  /**
   * Get method for attribute {}mmVersion
   */
  public java.lang.String getMmVersion() {
    return _a_MmVersion;
  }

  // Attribute field for attribute {}masterLanguage
  private java.lang.String _a_MasterLanguage;
  /**
   * Set method for attribute {}masterLanguage
   */
  public void setMasterLanguage(java.lang.String _MasterLanguage) {
    this._a_MasterLanguage = _MasterLanguage;
  }
  /**
   * Get method for attribute {}masterLanguage
   */
  public java.lang.String getMasterLanguage() {
    return _a_MasterLanguage;
  }

  // Attribute field for attribute {}package
  private java.lang.String _a_Package;
  /**
   * Set method for attribute {}package
   */
  public void setPackage(java.lang.String _Package) {
    this._a_Package = _Package;
  }
  /**
   * Get method for attribute {}package
   */
  public java.lang.String getPackage() {
    return _a_Package;
  }

  // Attribute field for attribute {}name
  private java.lang.String _a_Name;
  /**
   * Set method for attribute {}name
   */
  public void setName(java.lang.String _Name) {
    this._a_Name = _Name;
  }
  /**
   * Get method for attribute {}name
   */
  public java.lang.String getName() {
    return _a_Name;
  }

  // Attribute field for attribute {}guid
  private java.lang.String _a_Guid;
  /**
   * Set method for attribute {}guid
   */
  public void setGuid(java.lang.String _Guid) {
    this._a_Guid = _Guid;
  }
  /**
   * Get method for attribute {}guid
   */
  public java.lang.String getGuid() {
    return _a_Guid;
  }

  // Element field for element {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinition.Documentation
  private com.sap.engine.lib.descriptors.ws04wsd.WebServiceDefinitionDocumentation _f_WebServiceDefinitionDocumentation;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinition.Documentation
   */
  public void setWebServiceDefinitionDocumentation(com.sap.engine.lib.descriptors.ws04wsd.WebServiceDefinitionDocumentation _WebServiceDefinitionDocumentation) {
    this._f_WebServiceDefinitionDocumentation = _WebServiceDefinitionDocumentation;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinition.Documentation
   */
  public com.sap.engine.lib.descriptors.ws04wsd.WebServiceDefinitionDocumentation getWebServiceDefinitionDocumentation() {
    return this._f_WebServiceDefinitionDocumentation;
  }

  // Element field for element {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinition.SoapApplications
  private com.sap.engine.lib.descriptors.ws04wsd.WebServiceDefinitionSoapApplications _f_WebServiceDefinitionSoapApplications;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinition.SoapApplications
   */
  public void setWebServiceDefinitionSoapApplications(com.sap.engine.lib.descriptors.ws04wsd.WebServiceDefinitionSoapApplications _WebServiceDefinitionSoapApplications) {
    this._f_WebServiceDefinitionSoapApplications = _WebServiceDefinitionSoapApplications;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinition.SoapApplications
   */
  public com.sap.engine.lib.descriptors.ws04wsd.WebServiceDefinitionSoapApplications getWebServiceDefinitionSoapApplications() {
    return this._f_WebServiceDefinitionSoapApplications;
  }

  // Element field for element {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinition.VirtualInterfaceReferences
  private com.sap.engine.lib.descriptors.ws04wsd.WebServiceDefinitionVirtualInterfaceReferences _f_WebServiceDefinitionVirtualInterfaceReferences;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinition.VirtualInterfaceReferences
   */
  public void setWebServiceDefinitionVirtualInterfaceReferences(com.sap.engine.lib.descriptors.ws04wsd.WebServiceDefinitionVirtualInterfaceReferences _WebServiceDefinitionVirtualInterfaceReferences) {
    this._f_WebServiceDefinitionVirtualInterfaceReferences = _WebServiceDefinitionVirtualInterfaceReferences;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinition.VirtualInterfaceReferences
   */
  public com.sap.engine.lib.descriptors.ws04wsd.WebServiceDefinitionVirtualInterfaceReferences getWebServiceDefinitionVirtualInterfaceReferences() {
    return this._f_WebServiceDefinitionVirtualInterfaceReferences;
  }

  // Element field for element {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinition.uddiTModelPublications
  private com.sap.engine.lib.descriptors.ws04wsd.WebServiceDefinitionUddiTModelPublications _f_WebServiceDefinitionUddiTModelPublications;
  /**
   * Set method for element {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinition.uddiTModelPublications
   */
  public void setWebServiceDefinitionUddiTModelPublications(com.sap.engine.lib.descriptors.ws04wsd.WebServiceDefinitionUddiTModelPublications _WebServiceDefinitionUddiTModelPublications) {
    this._f_WebServiceDefinitionUddiTModelPublications = _WebServiceDefinitionUddiTModelPublications;
  }
  /**
   * Get method for element {http://xml.sap.com/2002/10/metamodel/wsd}WebServiceDefinition.uddiTModelPublications
   */
  public com.sap.engine.lib.descriptors.ws04wsd.WebServiceDefinitionUddiTModelPublications getWebServiceDefinitionUddiTModelPublications() {
    return this._f_WebServiceDefinitionUddiTModelPublications;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof WebServiceDefinitionState)) return false;
    WebServiceDefinitionState typed = (WebServiceDefinitionState) object;
    if (this._a_MmTimestamp != null) {
      if (typed._a_MmTimestamp == null) return false;
      if (!this._a_MmTimestamp.equals(typed._a_MmTimestamp)) return false;
    } else {
      if (typed._a_MmTimestamp != null) return false;
    }
    if (this._a_MmRelease != null) {
      if (typed._a_MmRelease == null) return false;
      if (!this._a_MmRelease.equals(typed._a_MmRelease)) return false;
    } else {
      if (typed._a_MmRelease != null) return false;
    }
    if (this._a_MmVersion != null) {
      if (typed._a_MmVersion == null) return false;
      if (!this._a_MmVersion.equals(typed._a_MmVersion)) return false;
    } else {
      if (typed._a_MmVersion != null) return false;
    }
    if (this._a_MasterLanguage != null) {
      if (typed._a_MasterLanguage == null) return false;
      if (!this._a_MasterLanguage.equals(typed._a_MasterLanguage)) return false;
    } else {
      if (typed._a_MasterLanguage != null) return false;
    }
    if (this._a_Package != null) {
      if (typed._a_Package == null) return false;
      if (!this._a_Package.equals(typed._a_Package)) return false;
    } else {
      if (typed._a_Package != null) return false;
    }
    if (this._a_Name != null) {
      if (typed._a_Name == null) return false;
      if (!this._a_Name.equals(typed._a_Name)) return false;
    } else {
      if (typed._a_Name != null) return false;
    }
    if (this._a_Guid != null) {
      if (typed._a_Guid == null) return false;
      if (!this._a_Guid.equals(typed._a_Guid)) return false;
    } else {
      if (typed._a_Guid != null) return false;
    }
    if (this._f_WebServiceDefinitionDocumentation != null) {
      if (typed._f_WebServiceDefinitionDocumentation == null) return false;
      if (!this._f_WebServiceDefinitionDocumentation.equals(typed._f_WebServiceDefinitionDocumentation)) return false;
    } else {
      if (typed._f_WebServiceDefinitionDocumentation != null) return false;
    }
    if (this._f_WebServiceDefinitionSoapApplications != null) {
      if (typed._f_WebServiceDefinitionSoapApplications == null) return false;
      if (!this._f_WebServiceDefinitionSoapApplications.equals(typed._f_WebServiceDefinitionSoapApplications)) return false;
    } else {
      if (typed._f_WebServiceDefinitionSoapApplications != null) return false;
    }
    if (this._f_WebServiceDefinitionVirtualInterfaceReferences != null) {
      if (typed._f_WebServiceDefinitionVirtualInterfaceReferences == null) return false;
      if (!this._f_WebServiceDefinitionVirtualInterfaceReferences.equals(typed._f_WebServiceDefinitionVirtualInterfaceReferences)) return false;
    } else {
      if (typed._f_WebServiceDefinitionVirtualInterfaceReferences != null) return false;
    }
    if (this._f_WebServiceDefinitionUddiTModelPublications != null) {
      if (typed._f_WebServiceDefinitionUddiTModelPublications == null) return false;
      if (!this._f_WebServiceDefinitionUddiTModelPublications.equals(typed._f_WebServiceDefinitionUddiTModelPublications)) return false;
    } else {
      if (typed._f_WebServiceDefinitionUddiTModelPublications != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_MmTimestamp != null) {
      result+= this._a_MmTimestamp.hashCode();
    }
    if (this._a_MmRelease != null) {
      result+= this._a_MmRelease.hashCode();
    }
    if (this._a_MmVersion != null) {
      result+= this._a_MmVersion.hashCode();
    }
    if (this._a_MasterLanguage != null) {
      result+= this._a_MasterLanguage.hashCode();
    }
    if (this._a_Package != null) {
      result+= this._a_Package.hashCode();
    }
    if (this._a_Name != null) {
      result+= this._a_Name.hashCode();
    }
    if (this._a_Guid != null) {
      result+= this._a_Guid.hashCode();
    }
    if (this._f_WebServiceDefinitionDocumentation != null) {
      result+= this._f_WebServiceDefinitionDocumentation.hashCode();
    }
    if (this._f_WebServiceDefinitionSoapApplications != null) {
      result+= this._f_WebServiceDefinitionSoapApplications.hashCode();
    }
    if (this._f_WebServiceDefinitionVirtualInterfaceReferences != null) {
      result+= this._f_WebServiceDefinitionVirtualInterfaceReferences.hashCode();
    }
    if (this._f_WebServiceDefinitionUddiTModelPublications != null) {
      result+= this._f_WebServiceDefinitionUddiTModelPublications.hashCode();
    }
    return result;
  }
}
